### ISSUE TITLE
 `isFocusVisible` value from the `useFocusRing` hook is `true` after closing an alert box that has been opened by a mouse click on the button

### ISSUE THREAD

**Issue by augustalfredsson** [adobe/react-spectrum#1009]
# 🐛 Bug Report 

The `isFocusVisible` value from the `useFocusRing` hook is `true` after closing an alert box that has been opened by a mouse click on the button. 

## 🤔 Expected Behavior

After closing an alert box that has been opened by a mouse click on the button, focus should be returned to the button but `isFocusVisible` should be false since the user isn't navigating with the keyboard.

## 😯 Current Behavior

The `isFocusVisible` value from the `useFocusRing` hook is `true` after closing an alert box that has been opened by a mouse click on the button.

## 💻 Code Sample

https://codesandbox.io/s/charming-snowflake-d8v9h

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| @react-aria/focus  | 3.2.0 |
| Browser          | Chrome 84.0.4147.125 / Firefox 78.0.2 / Safari 13.1.2 (MacOS) |
| Operating System | MacOS 10.15.6 |

**Comment by LFDanLu** [comment]
@augustalfredsson Thanks for filing this issue. I believe this is actually intentional behavior (https://github.com/adobe/react-spectrum/blob/main/packages/@react-aria/interactions/src/useFocusVisible.ts#L88-L110) since clicking the alert causes you to blur from the window. 

The reason for this behavior is so that a user can see where the focus is if they switched tabs or navigating through a form in iOS.

**Comment by augustalfredsson** [comment]
The behaviour seems a little strange to me since no keyboard navigation has been performed before (or after) blurring from the window. From [this text](https://react-spectrum.adobe.com/react-aria/useFocusVisible.html#features) it would seem like the focus is always not visible "when the user interacts via a mouse or touch", but that is not always true then.

**Comment by LFDanLu** [comment]
@augustalfredsson Yeah, perhaps that text can be updated to reflect the window blur specific behavior. @majornista @jnurthen would you like to comment on feasibility  the above?

**Comment by majornista** [comment]
I'm not sure that I understand the issue as reported. If you look at https://react-spectrum.adobe.com/react-spectrum/AlertDialog.html, opening an AlertDialog using either keyboard or mouse, and then closing the dialog using a mouse press on a Confirm of Cancel button within the dialog will not display the `isFocusVisible` style when focus is restored to the button. However, if you close a dialog that was opened using either keyboard or mouse using the `Esc` key, the `isFocusVisible` style will render because the dialog was closed using the keyboard. 

If you shift to another window or tab in the browser, and come back to the page, the `isFocusVisible` style will be restored to show where focus was when you left off. The default input modality when the window has not yet been interacted with or has been blurred, is to assume keyboard interaction. This allows us to display the `isFocusVisible` style on the element that receives focus when the user navigates into the web page using the keyboard from the browser chrome, which is an instance where we will be unable to detect keyboard interaction within the web page before the element receives focus.

**Comment by LFDanLu** [comment]
Gonna close this for now, feel free to reopen if you have any additional questions.
