### ISSUE TITLE
`useFocusRing` returning true for `isFocusVisible` when clicking a checkbox inside dialog

### ISSUE THREAD

**Issue by karlpetersson** [adobe/react-spectrum#1050]
# 🐛 Bug Report 

Clicking a checkbox inside a dialog causes `useFocusRing` to trigger `isFocusVisible`. It seems somewhat inconsistent - if the cursor is completely still, following clicks stops triggering it, but whenever the cursor is moved it again triggers the focus ring. See gif for what this looks like.
![Kapture 2020-09-04 at 01 03 59](https://user-images.githubusercontent.com/3764441/92183266-268f3280-ee4e-11ea-8e9b-a35a9461bcd1.gif)

Code used was copy-pasted from the examples for [useCheckbox](https://react-spectrum.adobe.com/react-aria/useCheckbox.html) and [useDialog](https://react-spectrum.adobe.com/react-aria/useDialog.html) (gist attached further down).
## 🤔 Expected Behavior

isFocusVisible to not trigger when clicking the checkbox

## 😯 Current Behavior

isFocusVisible triggers when clicking the checkbox, specifically the first time after opening the dialog or whenever cursor is moved between clicks

## 💻 Code Sample

https://gist.github.com/karlpetersson/d725b8a1ebcaa4e1d8917d337e6f2117

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| OS | Catalina 10.15.2 |
| Chrome | 85 |
| "@react-aria/button" | "3.2.1" |
| "@react-aria/checkbox" | "3.2.0" |
| "@react-aria/dialog" | "3.1.1" |
| "@react-aria/focus" | "3.2.0" |
| "@react-aria/overlays" | "3.3.0" |
| "@react-aria/visually-hidden" | "3.2.0" |
| "@react-stately/dialog" | "3.1.1" |
| "@react-stately/overlays" | "3.3.0" |
| "@react-stately/toggle" | "3.2.0" |

## 🧢 Your Company/Team
Visly

**Comment by LFDanLu** [comment]
@karlpetersson Looks like this is happening because there are two focus events being captured by `isFocusVisible` on each click event, one for the Dialog div and the other for the Checkbox input itself, causing this block of code (https://github.com/adobe/react-spectrum/blob/main/packages/@react-aria/interactions/src/useFocusVisible.ts#L98-L103) to flip keyboard modality. You can prevent the extra Dialog focus event by adding a `onMouseDown={(e) => e.preventDefault()}` to your Dialog div, but that feels kinda hacky, I'll need to dig into why this doesn't happen for the spectrum dialogs

**Comment by karlpetersson** [comment]
@LFDanLu Ah, that makes sense. Thanks, that solves the issue for me at least.

**Comment by LFDanLu** [comment]
Cool, I'll close this issue for now then. Will keep digging into why this doesn't happen for spectrum dialogs.

**Comment by VapidLinus** [comment]
For people who find this issue through Google (like me) when troubleshooting this problem; LFDanLu suggested a better fix [over in another comment](https://github.com/adobe/react-spectrum/issues/2380#issuecomment-931642320) than the one they suggest here:

> An alternative hacky fix to the one mentioned in https://github.com/adobe/react-spectrum/issues/1050 is to add a usePress to the Switch and spread the pressProps onto the Switch label element but that prevents text selection of the switch label...

Dan's initial suggestion in this thread fixed the immediate issue for me but made it so that any react-aria text fields inside the component wouldn't be clickable, so users couldn't click to type in them without using the keyboard to focus it. The `usePress()` fixed both problems for me, like this:

```
function Checkbox(props: ...) {
    // ... useCheckbox hooks etc

    // TODO: https://github.com/adobe/react-spectrum/issues/2380#issuecomment-931642320
    const { pressProps } = usePress({})

    return (
        <label {...mergeProps(myOtherProps, pressProps)}>
            {/* ... checkbox appearance etc */}
            {children}
        </label>
    )
}
```
