### ISSUE TITLE
OverlayContainer createPortal(contents, document.body) before document is ready(for SSR)

### ISSUE THREAD

**Issue by matamatanot** [adobe/react-spectrum#1055]
# 🐛 Bug Report 

An error occurred when using OverlayContainer and Next.js in combination. Of course, I also use SSRProvider.

```
Unhandled error during request: ReferenceError: document is not defined
at OverlayContainer (/vercel/4bfb0cda/node_modules/@react-aria/overlays/dist/main.js:672:43)
at d (/vercel/4bfb0cda/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:498)
...

```

The following seems to be the cause.
https://github.com/adobe/react-spectrum/blob/9d3b925ee5bbea9d63db95a53a32d03e9a1a686e/packages/%40react-aria/overlays/src/useModal.tsx#L118

## 🤔 Expected Behavior

Make sure the OverlayContainer component support SSR.

## 😯 Current Behavior

Not working for SSR.

## 💁 Possible Solution

check `document.readyState !== 'loading'`

## 🔦 Context
ref: #1052

## 💻 Code Sample

"next": "^9.5.3"
pages/_app.tsx
```
const MyApp = ({ Component, pageProps }: AppProps) => {
  return (
    <SSRProvider>
      <OverlayContainer>
        <Component {...pageProps} />
      </OverlayContainer>
    </SSRProvider>
  );
};
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| @react-aria/overlays   | 3.3.0 |
| Next.js   | 9.5.3 |

**Comment by LFDanLu** [comment]
@matamatanot I'm curious how your script is being loaded before the document is ready. How does Next.js usually handle cases like this?

**Comment by matamatanot** [comment]
A with-portals example exists in the Next.js repo.
https://github.com/vercel/next.js/tree/canary/examples/with-portals

HTMLDivElement for Modal is created in _document.js.
```
import Document, { Head, Main, NextScript } from 'next/document'

export default class extends Document {
  render () {
    return (
      <html>
        <Head />
        <body>
          <Main />
          {/* here we will mount our modal portal */}
          <div id='modal' />
          <NextScript />
        </body>
      </html>
    )
  }
}
```

If Element can be specified by #1013, Next.js should be able to solve the problem. I think it's a bit hacky, though.

**Comment by LFDanLu** [comment]
@matamatanot Gotcha, I think your suggestion of checking for `document.readyState` in `OverlayContainer` sounds good. I guess we'd return nothing if `document` isn't defined?

**Comment by travigd** [comment]
I ran into this while trying to tweak some styling inside a `<Picker />`; I set the `open={true}` prop (to be able to actually keep the menu open) and then when I refreshed, I got the `document is not defined` error from NextJS.

In that case, the answer is just "don't set `open={true}` in prod."

More generally...

I don't think returning nothing is the answer, unfortunately (you'll get warnings along the lines of _Expected server HTML to contain a matching XYZ node_ since the client-hydrated DOM tree differs from the server-generated tree).

The common thing I see is a hook that creates a mountpoint as an effect.

```tsx
export function useLazyMountpoint(options: {
  label: string;
}): HTMLDivElement | null {
  const { label } = options;
  const [mountpoint, setMountpoint] = React.useState<HTMLDivElement>();

  // Mount it into the DOM
  React.useEffect(() => {
    const mountpoint = document.createElement("div");
    document.body.appendChild(mountpoint);
    mountpoint.dataset.mountpointFor = label;
    setMountpoint(mountpoint);
    return () => void document.body.removeChild(mountpoint);
  }, [label]);

  return mountpoint;
}

// usage
export const MyPortal = () => {
  const mountpoint = useMointpoint();
  if (!mountpoint) return null;
  return ReactDOM.createPortal(<p>hi</p>, mountpoint);
}
```

This works since the initial render agrees between server and client (and the effect only runs on the client). The obvious downside is that the portals aren't actually included in the initial render, but for most(?) use-cases, that seems fine (e.g., for use in a `<Picker />`).

The **other alternative** is described above (which involves kind of "hoisting" the container creating through React context).

**Comment by abacon** [comment]
Hi! I'm happy to contribute a solution to this issue (it's affecting me too), but I'm not sure which of the described solutions is best. Can anyone (@travigd?) provide some guidance? Thanks!
