### ISSUE TITLE
Show tooltip on touch devices

### ISSUE THREAD

**Issue by bitworking** [adobe/react-spectrum#1136]
# 🙋 Feature Request

Tooltips should also be shown on touch devices.

## 🤔 Expected Behavior

When I long-press on the trigger button the tooltip should be shown.

## 😯 Current Behavior

Tooltips do not appear on touch devices. The trigger button is shown but nothing happens if you press it.

## 💁 Possible Solution

The most obvious solution would be a long-press on the trigger button. The delay should be the same as for hovering.

## 🔦 Context

A tooltip shows further information which might not be interesting for every user (form fields for example). So you do not always need to display it. But if it does not work on touch devices, you need another solution for example hide the button and show the text under the form field. But since the space on mobile devices is already limited, this is suboptimal and also would involve a lot of work.

## 💻 Examples

The design guide of Material Design for example also recommends to show the tooltip on hover, focus or long-press: https://material.io/components/tooltips

## 🧢 Your Company/Team

I'm building a component library (nx-kit) for my company nexum AG: https://github.com/nexumAG
The repo is still private but will be openend if we are out of the early phase. The first components are on npm for testing, though: https://www.npmjs.com/search?q=%40nx-kit

**Comment by devongovett** [comment]
I think we won't do this by default because there may already be long-press gestures associated with an element, but I think it makes sense as an option for certain use cases.

**Comment by Andarist** [comment]
Question - if we treat tooltips as accessibility feature then shouldnt favoring other press-based actions on elements with tooltips be discouraged?

**Comment by devongovett** [comment]
I think for cases where the element's only purpose is to display a tooltip it might make sense to make them appear on touch. e.g. a help icon like this: https://spectrum.adobe.com/page/tooltip/#Immediate-or-delayed-appearance

**Comment by Andarist** [comment]
Right - I got this from your earlier comment. Im just wondering if making a component with tooltip and other pressable action just shouldnt be allowed (or heavily discouraged) as *not* showing the tooltip makes the whole thing less accessible. I dont have a strong opinion about this one myself - just posing a question.

**Comment by devongovett** [comment]
Yeah I agree it should be avoided I think. Long press is especially problematic with touch screen readers.

**Comment by well1791** [comment]
@Andarist @devongovett is there any good solution to support a11y for touch devices?

I've tried the [tooltip example](https://react-spectrum.adobe.com/react-aria/useTooltipTrigger.html) using android TalkBack, and it the result is:
 - the reader gets to the button but
 - it doesn't trigger on focus
 - it doesn't trigger on click

So, I'm wondering if fixing this issue on touch devices is part of the a11y scope.

**Comment by snowystinger** [comment]
You can always use an aria-label.

You could also place a button with a popover next to the element you want the tooltip on, this popover could then contain the extra information. We will be releasing an alpha soon for a component called "Contextual Help" that is for this purpose.

**Comment by well1791** [comment]
@snowystinger That's a good idea indeed, in my case I'm displaying the information on touch devices.

Also, I believe that this information should reach the docs, like: "Notice, for touch devices tooltip won't work as expected due to ..., check this codepen/repository (link here) for an alternative solution"

Let me know if I can be of help with that.

**Comment by snowystinger** [comment]
Sure, we'd welcome a contribution. I think my first note would be to change the message from won't work as expected, since no one expects tooltips on touch, to something along the lines of "See usage guidelines for tooltips here https://spectrum.adobe.com/page/tooltip/#Use-tooltips-to-describe-icons. Keep in mind that tooltips do not appear on touch devices because there is no hover and there is no keyboard focus. If you have information that is critical, consider using help text descriptions as in the guidelines or a button that opens a popover with the extra information directly to the side."

Tooltip docs are here https://github.com/adobe/react-spectrum/blob/main/packages/%40react-spectrum/tooltip/docs/Tooltip.mdx
and here https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/tooltip/docs/useTooltipTrigger.mdx

**Comment by well1791** [comment]
@snowystinger it makes total sense. I think I'm going to go for the popover, thanks replying.

**Comment by devongovett** [comment]
Here's a reference for our implementation in Spectrum if you're curious https://react-spectrum.adobe.com/react-spectrum/ContextualHelp.html

**Comment by dannify** [comment]
Closing as stale. This is not work that the team is able to take on in the near future.
