### ISSUE TITLE
useSelect should select the option based on the last keystrokes

### ISSUE THREAD

**Issue by souporserious** [adobe/react-spectrum#1151]
# 🐛 Bug Report 

The `useSelect` hook does not select the option based on the last keystrokes when the button is focused and menu is closed.

## 🤔 Expected Behavior

The `useSelect` hook should select the option based on the last keystrokes when closed and focused similar to how a native select works:

![type-to-select](https://user-images.githubusercontent.com/2762082/95386945-e8e65500-08a4-11eb-993d-e5993f0e3c24.gif)

## 😯 Current Behavior

Right now nothing happens when the select box is focused and typing occurs.

## 💁 Possible Solution

I haven't looked into the architecture of `useSelect` yet, but at work we had to do some interesting things to mimic this, we render an invisible menu to collect the options and select them when the button is focused. There's a demo [here](https://ministrycentered.github.io/ui-kit/select) if curious as to how it's working. I'll try to get a PR together when I get a chance 😊

**Comment by devongovett** [comment]
Hmm... that should work. Maybe a bug in the example? It works on https://react-spectrum.adobe.com/react-spectrum/Picker.html

**Comment by souporserious** [comment]
Oh, interesting! Yeah, the example [here](https://react-spectrum.adobe.com/react-aria/useSelect.html#example) doesn't seem to be working. Is there option that needs to be configured?

**Comment by LFDanLu** [comment]
@souporserious  Did some digging and the reason the `onKeyDownCapture` from `useTypeSelect` doesn't make it onto the `button` is that `useButton` essentially filters it out. It uses `usePress` and `useFocusable` to create the set of buttonProps it returns and neither pass `onKeyDownCapture` through. Picker works because it sends the `onKeyDownCapture` to the Button via context (PressResponder).

Not sure the best way to go about solving this (`useKeyboard` change to pass through `onKeyDownCapture`?) happy to discuss.

**Comment by kamal** [comment]
I had the same exact issue. @devongovett replied my tweet with this workaround 

> There's a bug currently I believe. We changed it to use a capturing listener in the last release, but that doesn't get passed through `useButton`. As a workaround, you need to copy `onKeyDownCapture` from triggerProps to buttonProps manually

https://twitter.com/devongovett/status/1298033200644513793?s=20
