### ISSUE TITLE
useFocusRing - disable autofocus ring when switching between browser tabs

### ISSUE THREAD

**Issue by binhxn** [adobe/react-spectrum#1157]
# ❔ Question

Hello!

I was wondering if it was possible to disable the focus ring (to the last applied focused element) when switching between browser tabs. I tried to pass in `autofocus: false` as an option to useFocusRing, but that didn't do anything. I was wondering if there was a way to do that?

## 🔦 Context
I'm creating a custom Pagination component using [Material UI's usePaginationHook](https://material-ui.com/components/pagination/#usepagination). When I applied the useFocusRing hook to each (mapped) paginated button, I was getting unintended focus behavior:
- When I tab from the Previous Button to the Numbered Page Button, then switch tabs and back, I noticed both the Previous Button and the last-focused Numbered Page Button were autofocused.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| @react-aria/focus   | v3.2.2,
| Browser          | Chrome Version 86.0.4240.75
| Operating System | MacBook Pro (15-inch, 2018), Catalina, v10.15.6

edit: updated environment

**Comment by snowystinger** [comment]
Do you know if it's some interference from Material UI? I took a quick scan through usePaginationHook but didn't see anything immediately.
Are you able to demonstrate it in a codesandbox? that'd be very helpful

**Comment by binhxn** [comment]
@snowystinger I'm having trouble pinpointing that, but I do have a [CodeSandbox available](https://codesandbox.io/s/material-demo-forked-iqsco?file=/demo.js). For clarity, my goal is to use the CSS property `box-shadow` instead of `outline` to display the focus ring. I'm unable to replicate the autofocus on browser-tab change as described in the initial post. However, the pagination button still retains the focus ring when tabbing out of a disabled button.

To replicate:
1. Tab to any numbered button and press the Space key until **previous** is not disabled.
2. Tab back to **previous** button and press the Space key until **previous** is disabled (you'll notice the focus ring is still visible on the disabled button.)
3a. Now tab to any numbered button and you'll see two focus rings - one on **previous** and one on numbered button.
3b. Complete steps 1-2. Then clear the currently visible focus ring by clicking away from the buttons, then pressing tab. You should also observe two focus rings.

**Comment by snowystinger** [comment]
The root of this issue seems to be that useFocusRing, when passed isDisabled, removes all event listeners. So it will never get the memo to remove the focus ring. Now, you could add `boxShadow: isFocusVisible && !isDisabled ? focusRingStyle : "none"` or something along those lines. That still doesn't take care of moving the focus though.

For the case where the previous button is disabled out from under the user, focus should be moved to whatever page is selected probably. A disabled item can't be focused.
Unfortunately, we don't know where the focus should go at that point, it's application/component specific. So you will need to wire that up.
There might be an improvement we could make around this line https://github.com/adobe/react-spectrum/blob/main/packages/@react-aria/interactions/src/useFocus.ts#L36 where we still listen for onBlur so that you don't need the logic I mentioned above with `!isDisabled`.

For how you might approach this:
useFocusWithin on the whole pagination component. If focus is within and the onChange from the usePagination hook goes to the min/max values, then move focus to the first/last number button. For how you do that, maybe a useEffect in the item that calls focus on itself if it's the selected and the min/max value is met.
The reason for the useFocusWithin is so that if some external thing changes the page (a different set of buttons at the top for example), then it won't yank focus from there into the Pagination component.

I also noticed in item on the button you spread two objects, I didn't look to see what was in those, but if there are on* handlers or anything else, you probably want to use `{...mergeProps(focusProps, item)}` so that those get chained together.
