### ISSUE TITLE
FocusScope wont move past elements inside the FocusScope unless mounted and unmounted first.

### ISSUE THREAD

**Issue by DivMode** [adobe/react-spectrum#1189]
# 🐛 Bug Report 

1. Focus ends at FocusScope element in the navbar and wont move onto next focus which in this case is the yellow "contact" link.

2. Probably unrelated bug but on Firefox nothing else focuses except the navigation button in mobile screen size.

## 🤔 Expected Behavior

Should focus on the contact element instead of cycling through the header.

## 😯 Current Behavior

When tabbing through the links the focus cycles throughout the header, first going to the logo then the navigation but wont move past navigation. In order to move past navigation I need to open up the nav menu and close it and then the focus cycle works properly.

Attached video:
https://www.loom.com/share/19689a8ead594f05a456856edf64ac5e?from_recorder=1

## 💻 Code Sample

https://codesandbox.io/s/vibrant-platform-cmvre?file=/components/Navbar.js

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.2.0
| Browser          | Chrome, Safari, and Firefox but focus doesnt cycle through anything except the nav menu.
| Operating System | OSX Catalina 10.15.7

**Comment by majornista** [comment]
To workaround this issue, you may want to only include the `FocusScope` wrapper and hamburger menu button when  `!isWide`, as in this fork: https://codesandbox.io/s/great-lovelace-7o3vc?file=/components/Navbar.js. 

The problem is that when the page loads, `FocusScope` initializes with the `document.body` as the [`nodeToRestore`](https://github.com/adobe/react-spectrum/blob/6e9f55a7cebf5f61cdd89057f7cc8b00d021d4d7/packages/%40react-aria/focus/src/FocusScope.tsx#L328) when focus is leaving last item in the scope, which calls this loop at [FocusScope.tsx#L354-L359](https://github.com/adobe/react-spectrum/blob/6e9f55a7cebf5f61cdd89057f7cc8b00d021d4d7/packages/%40react-aria/focus/src/FocusScope.tsx#L354-L359) to determine the next element to focus, resulting in the first element in the `document.body`. 

This does seem like a valid issue we should fix in `FocusScope`.

**Comment by DivMode** [comment]
Workaround works great.

Now only on mobile does it still cycle through the header but I doubt many people are tabbing through stuff on mobile screen sizes.

**Comment by devongovett** [comment]
I think this is probably working as intended. You could also only set `restoreFocus` to true if the mobile menu is open.

**Comment by DivMode** [comment]
Ive tried using restoreFocus to true while menu is open but it isnt working as expected. Ive spent a lot of time on this.

I realized the previous solution causes server mismatch errors since I am using ssr and isWide is getting the values from clientside.

Is there another solution to this problem I am possibly missing?

**Comment by agg23** [comment]
If this is intended, it is not documented well. The `useRestoreFocus` `useLayoutEffect` will trigger regardless of `restoreFocus`, which has some pretty significant side effects. In my case, I expected to keep `FocusScope` always mounted, with no additional props set, with the intention of using it exclusively for `useFocusManager`.

However, since `useRestoreFocus` will grab the body as `nodeToRestore`, tabbing past the end of the scope results in restoring the `nodeToRestore`, which is incorrect. Removing `useRestoreFocus` altogether works for my use case, but I would expect this functionality in `react-spectrum`.
