### ISSUE TITLE
interaction with native html `<form>`s

### ISSUE THREAD

**Issue by stefanprobst** [adobe/react-spectrum#1219]
# ❔ Question

It looks like `react-spectrum` components are working well with native html `<form>`s. For example, the following code sample seems to work correctly because 'react-spectrum' actually renders hidden 'input', 'select'` etc. From the docs it wasn't 100% clear if this is intentional, and guaranteed to work in the future, or if this is just an implementation detail that might change and should not be relied upon.

## 💻 Code Sample

```js
import { Button, Checkbox, Item, Picker } from '@adobe/react-spectrum';

export default function Page() {
  return (
    <form
      onSubmit={(event) => {
        event.preventDefault();
        console.log(Array.from(new FormData(event.currentTarget)));
      }}
    >
      <Picker label="Choose fruit" name="fruit">
        <Item key="apple">Apple</Item>
        <Item key="orange">Orange</Item>
        <Item key="banana">Banana</Item>
      </Picker>
      <Checkbox name="tasty">Tasty</Checkbox>
      <Button type="submit">Submit</Button>
    </form>
  );
}
```

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum  | latest |

**Comment by LFDanLu** [comment]
@stefanprobst Yep those hidden selects/input are intentional and were added with native form submission in mind (as well as autofill and mobile focus navigation). We even provide a `HiddenSelect` element if you'd like to use it in your own components, see https://react-spectrum.adobe.com/react-aria/useSelect.html#example for an example of how this may be done.

**Comment by stefanprobst** [comment]
awesome, thanks!
