### ISSUE TITLE
Focus handling broken in nested overlays

### ISSUE THREAD

**Issue by RubenStoesser** [adobe/react-spectrum#1220]
# 🐛 Bug Report 

After updating `@react-aria/overlays` to `3.5.0` from `3.4.0` we are experiencing the issue that elements which are part of a nested Overlay can no longer be focused with a left-click of the mouse. However, they are still focusable using the TAB key or when right-clicking.

The issue does not occur when using `@react-aria/overlays` version `3.4.0`.

## 🤔 Expected Behavior

Elements in the nested overlay should be focusable when left clicking.

## 😯 Current Behavior

In a nested overlay where both the nested and parent overlay use their own `FocusScope` with `contain={true}` it is no longer possible to focus elements using the left click of the mouse. Funnily enough, right-click works and clicking the associated `<label>` element of an input also works.

Once any element has focus it is no longer possible to focus anything else using left click.

## 💻 Code Sample

Codepen showing the issue based on the `useDialog` example from the docs:
https://codesandbox.io/s/friendly-einstein-suxnx?file=/src/App.js

(Switching the `@react-aria/overlays` dependency to version `3.4.0` fixes the issue in the codepen.)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-aria/overlays | 3.5.0
| Browser          | Chrome Version 86.0.4240.111
| Operating System | Windows 10

**Comment by LFDanLu** [comment]
@RubenStoesser Thanks for catching this, looks like this was a side effect of the following pull: https://github.com/adobe/react-spectrum/pull/1187.

**Comment by chungwu** [comment]
Slightly off-topic, but... it looks like `useOverlay()` always calls `useInteractOutside()`, which installs the event handlers that led to the bug...  Would it make sense to also let `useInteractOutside()` take in some kind of `isDisabled` flag, and for `useOverlay()` to call it like `useInteractOutside({isDisabled: !isOpen})`?

Incidentally, my code was _always_ calling `useOverlay()`, not just when an overlay was visible, which led to focus being broken by this bug even when there are no overlays shown.  Is `useOverlay()` only supposed to be called when the overlay is visible?  I didn't expect so, since `useOverlay()` takes in `isOpen` as a prop...

**Comment by snowystinger** [comment]
@chungwu where are you seeing that this is always called? I'm not seeing it in the DialogTrigger stories, it's only getting called once I open it.

**Comment by chungwu** [comment]
@snowystinger Ah sorry, to clarify -- **I** am always calling `useOverlay()` in my own implementations of modals / selects / etc (not Spectrum).  It was not clear to me that `useOverlay()` should only be called when the overlay is open (since `useOverlay()` takes in `isOpen` as a prop after all).

**Comment by snowystinger** [comment]
Thanks for the clarification, let me ask in our team and take a look.

**Comment by snowystinger** [comment]
Thanks @chungwu we've opened an issue for this here https://github.com/adobe/react-spectrum/issues/1262
