### ISSUE TITLE
Support Arrow-Keys in Picker for improved keyboard interactions

### ISSUE THREAD

**Issue by tomsontom** [adobe/react-spectrum#1265]
# 🙋 Feature Request

Native Browser-Select-Elements support the following keyboard interactions:
* Arrow Up / Down:
  * OSX: opens the Popup
  * Windows: selects next/previous entry
* Arrow Left / Right
  * OSX: selects next/previous entry
  * Windows: selects next/previous entry

The current picker does not honor them hence keyboard interaction does not follow well known patterns.

## 🤔 Expected Behavior

Keyboard interactions behave similar to native selects 

## 😯 Current Behavior

No handling

## 💁 Possible Solution

Once #1229 is done I'd like to address this if you agree that Picker should support arrow keys, my current guess is that this should be addressed in useTypeSelect() but I could be wrong. 

One thing I'm not sure about is which arrow behavior should be implemted for up/down as the native platforms differ (i don't have linux). `ComboBox` currently support Up/Down and just opens the Popup and to me that feels better (but I'm an OS-X user).

**Comment by snowystinger** [comment]
This is part of the spec we based our Picker off of https://www.w3.org/TR/wai-aria-practices/examples/listbox/listbox-collapsible.html it has no mention of right/left arrows. The other part being Spectrum, our design system, which outlines behavior as follows https://spectrum.adobe.com/page/picker/#Keyboard-interactions

I do see that if you tab to our Picker and press the up/down arrow, it does open the Picker https://react-spectrum.adobe.com/react-spectrum/Picker.html.
We do favor out design system in what item is selected when opened this way. We open to the currently selected one instead of open and moving the selection to the next or previous item. I'll bring this up with our design team and let you know what they say.

**Comment by tomsontom** [comment]
hm maybe I've broke this locally with my changes to #1229

**Comment by tomsontom** [comment]
right I'm the one to blame - in my change I've disabled the onkeydown/onkeyup from "useMenuTrigger" - I'll fix in the PR

**Comment by tomsontom** [comment]
so the current implementation is somewhere in the middle - Is it an oversight in https://spectrum.adobe.com/page/picker/#Keyboard-interactions that `Arrow Up` does not open the popup?

**Comment by snowystinger** [comment]
I think that's an oversight, but I'll let you know after we meet with the design team on tuesday.

**Comment by devongovett** [comment]
Hmm arrow up opens the popup for me on https://react-spectrum.adobe.com/react-spectrum/Picker.html

**Comment by tomsontom** [comment]
right but the Spectrum-spec only talks about Arrow-Down

**Comment by devongovett** [comment]
Oh - The design site is often covering just the basics and might be missing many keyboard interaction details that we get from ARIA.

**Comment by devongovett** [comment]
Leaving this issue open for the left/right arrow support given that this is widely supported by native selects.
