### ISSUE TITLE
How to use Virtualizer with a ListLayout where items have dynamic height?

### ISSUE THREAD

**Issue by karlpetersson** [adobe/react-spectrum#1288]
# ❔ Question

I'm implemented a Select component, using a Virtualizer with a ListLayout (much like the react-spectrum Picker component). However I don't want to set a static height on items, I need the height to be stylable (or derived from the contents of the item). This is causing me some issues.

I don't know what to set `estimatedRowHeight` to in the ListLayout constructor. If I set it to 0, the popover menu will not flip position correctly when there's no room (since items and thus the menu gets a 0 height on initial render). If I set it to some value or leave it default, it seems the items will always have that size. Both `rowHeight` and `estimatedRowHeight` seems to set the actual height of the item, I assumed that If I set `estimated*` it would measure the real size of the item and update this internally, but it only seems to do this if I pass it a value of 0.

I've tried to manually measure items and reinitialize the ListLayout with the correct `estimatedRowHeight`, but then I get flickering. Am I missing something here? Is this achievable using the Virtualizer or do I need to specify a static row height? 

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

## 🧢 Your Company/Team

Visly

**Comment by devongovett** [comment]
So, here's how it works, and I believe where the possible issue lies. On initial render, we set the `height` of the item to the `estimatedRowHeight`. In a `useLayoutEffect`, we then measure the element's `scrollHeight`. This will work if the actual height is larger than the estimated height, however, the `scrollHeight` will never be _smaller_ than the css `height` property. That means if you set the estimated height property larger than the minimum item size, it will not shrink. See here for details: https://github.com/adobe/react-spectrum/blob/main/packages/@react-aria/virtualizer/src/useVirtualizerItem.ts#L26.

In order to fix this, we'd need to remove the css `height` property prior to measuring and restore it after, which would also trigger a reflow. Not sure how performance would be but we could try it. Feel free to experiment if you like.

In the meantime, I'd set `estimatedRowHeight` to the minimum height of your list items, which is what we currently do in Picker.

**Comment by karlpetersson** [comment]
Thanks a lot Devon, that makes sense. I think I messed up when trying out `estimatedRowHeight` values that were smaller than the actual height, where I thought it looked like the resulting height didn't grow past that value. 🤦 Your suggestion for setting it to the minimum height will work for our case.

**Comment by dannify** [comment]
Potential fix in  https://github.com/adobe/react-spectrum/pull/1286/files#diff-4e864d9319d46e26321a2f04afdf2eee017079cbf4f67c4698da1fef97e2d49d

For prosperity in case that pr changes.
```
// Reset height before measuring so we get the intrinsic size
let height = node.style.height;
node.style.height = '';
let size = new Size(node.scrollWidth, node.scrollHeight);
node.style.height = height;
return size;
```

**Comment by LFDanLu** [comment]
#1286 has been merged, closing issue.
