### ISSUE TITLE
Wrong RadioAriaProps interface name for useRadio

### ISSUE THREAD

**Issue by schabluk** [adobe/react-spectrum#1289]
In https://react-spectrum.adobe.com/react-aria/useRadioGroup.html

```
useRadio(
  props: RadioAriaProps,
  state: RadioGroupState,
  ref: RefObject<HTMLElement>
): RadioAria
```

Is: `RadioAriaProps`
Should be: `AriaRadioProps`

**Comment by LFDanLu** [comment]
Thanks for noting this, looks like we just need to rename here: https://github.com/adobe/react-spectrum/blob/main/packages/@react-aria/radio/src/useRadio.ts#L32

**Comment by LFDanLu** [comment]
Ah, actually that type extends from `AriaRadioProps`, this is correct.

**Comment by schabluk** [comment]
@LFDanLu yeah, but it's not exported, so there is no way to use it. IMO the docs are misleading.

**Comment by LFDanLu** [comment]
@schabluk Do you need that type specifically? I'm not entirely sure what you mean by misleading.

**Comment by schabluk** [comment]
@LFDanLu yes, I need it to type component props that are required by `useRadio`. The docs suggest `RadioAriaProps` which is not exported from `@react-types/radio`. How should I know which type to use?

```javascript
import * as React from 'react'
import { useRadio } from '@react-aria/radio'
import type { AriaRadioProps } from '@react-types/radio'

import { RadioContext } from './RadioGroup'

export default function RadioButton(props: AriaRadioProps) {
  const ref = React.useRef<HTMLInputElement>(null)
  const state = React.useContext(RadioContext)
  const { inputProps } = useRadio(props, state, ref)

  return (
    <label>
      <input ref={ref} {...inputProps} />
    </label>
  )
}
```

**Comment by LFDanLu** [comment]
@schabluk Ah I see. So the reasoning for `useRadio` using `RadioAriaProps` instead of `AriaRadioProps` is because it contains a couple extra hook specific options that shouldn't show up in the Radio props, namely `isRequired` and `isReadOnly`. These two props are set on a `RadioGroup` so we can properly set `required`/`readonly` on all radios within the group. Applying `isRequired` or `isReadOnly` on an individual Radio therefore doesn't do anything and thus we don't include it in the `AriaRadioProps`. IMO the same should apply to your `RadioButton` example above, I don't think you would want `isRequired` and `isReadOnly` in the prop definition of your `RadioButton` since those should be controlled by the RadioGroup instead.
