### ISSUE TITLE
V2Dropdown does not work when rendered inside a V3Dialog

### ISSUE THREAD

**Issue by kgen-emerald** [adobe/react-spectrum#1353]
# 🐛 Bug Report 

When adding a V2Dropdown inside a V3Dialog, the dropdown menu is not keyboard focusable. We can't navigate through MenuItems using arrow keys.

## 🤔 Expected Behavior

MenuItems should be accessible using arrow keys.

## 😯 Current Behavior

The temporary solution works, but it does not close the SubMenu when the left arrow key is pressed.
```
<Dropdown>
              <Button variant="cta">Test</Button>
              <V2Provider>
                  <Menu>               
                   <FocusScope autoFocus>
                    <MenuItem role="menuitemradio" value="foo">Foo</MenuItem>
                    <MenuItem role="menuitemradio" value="bar" selected>Bar</MenuItem>
                    <MenuItem role="menuitemradio" value="baz">Baz</MenuItem>
                    <SubMenu label="zaa">
                      <FocusScope autoFocus>
                        <MenuItem value="1">zaa 1</MenuItem>
                        <MenuItem value="2">zaa 2</MenuItem>
                        <MenuItem value="3">zaa 3</MenuItem>
                      </FocusScope>
                    </SubMenu>
                    </FocusScope>
                  </Menu>
              </V2Provider>
            </Dropdown>
```

## 🔦 Context

It's a part of the maintenance flow project which will go live in January next year. 

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | v2+v3|
| Browser          | Chrome |
| Operating System | MacOS Catalina |

## 🧢 Your Company/Team

Adobe/Admin Console

**Comment by LFDanLu** [comment]
Some preliminary investigation done when this came up in slack:
The core issue seems to be due to how v3 Dialog has a [`contain` v3 FocusScope](https://github.com/adobe/react-spectrum/blob/main/packages/@react-spectrum/dialog/src/Dialog.tsx#L82) which will attempt to contain focus within the dialog. V2 Dropdown portals itself outside of the Dialog and doesn't use a v3 FocusScope so its contents aren't added to the [`scopes`](https://github.com/adobe/react-spectrum/blob/main/packages/@react-aria/focus/src/FocusScope.tsx#L79-L93), resulting in the dropdown contents being non-focusable since it thinks focus is leaving the v3Dialog.

As seen above, a workaround was to add FocusScopes wrapping the MenuItems of the Dropdown and the SubMenu, adding those menu items to the `scopes` list previously mentioned. However, another issue arises since V2 SubMenu expects the MenuItems to be the immediate children of the SubMenu, but instead FocusScope is the immediate child in this setup. This results in SubMenu's keydown handler being improperly placed on the FocusScope, hence why the left arrow key no longer works.

A preliminary idea to fix would be to come up with another way to add elements to the FocusScope `scope` so we don't have to insert FocusScope everywhere, maybe in the form of a hook or something.

**Comment by ktabors** [comment]
Adding a `<FocusScope />` around the `MenuItem's` was able to get the focus into the `Menu` and `SubMenu`, but we lose the ability to close the `SubMenu` with the left arrow key. It can still be closed with the escape key. We will continue looking into this.

**Comment by ktabors** [comment]
We are closing this issue because escape key closing the submenu does allow keyboard use of this component. If additional functionality is needed please reopen.
