### ISSUE TITLE
v3 Table - Fractional pixellation 

### ISSUE THREAD

**Issue by bryantabaird** [adobe/react-spectrum#1380]
# 🐛 Bug Report 

The `left` property of a table cell, if it results in a fraction, results in a pixel gap between some cells. For tables where `isQuiet={true}`, this show a noticeable gap depending on the background color, and when hovering over the cell.

For tables with `isQuiet={false}`, this doesn't happen in the table cells themselves, but it does in the header. 

## 🤔 Expected Behavior

This could easily be resolved by changing the background color of the table's parent element, but then the issue is still apparent when hovering over a row, as the color is changed

## 🔦 Context

Best way to reproduce is in the 6 column table sandbox below.

## 💻 Code Sample

https://codesandbox.io/s/morning-waterfall-c62q6

To reproduce, you will likely need to resize the render window where the width of the table is an odd number. See screenshot of the result you're trying to achieve when resizing

Quiet table: Notice the vertical red line in the table
![image](https://user-images.githubusercontent.com/9795404/102274552-50da9c80-3ee1-11eb-9b07-4998f503d75c.png)

Non-quiet tables: the header (and even a few corner cells' border-radius and the right-most header cell) have gaps
![image](https://user-images.githubusercontent.com/9795404/102274641-71a2f200-3ee1-11eb-9d60-c7bab3390b81.png)

## 🌍 Your Environment

@react-spectrum/table: 3.0.0-alpha.9

## 🧢 Your Company/Team

Adobe Analytics

**Comment by snowystinger** [comment]
Yep, I see that as well in your example. In particular, it appears to actually be the fractional width's.
There are two things we should try (I tried the usual zTransform(0) and translate(0, 0) to no avail)
1) use translate instead of absolute positioning (I think perf will be the same)
2) round widths and positions down to a whole number, this may be tricky though because we'll potentially need to round half of them up in response
