### ISSUE TITLE
Scroll bar color inconsistent with OS color mode

### ISSUE THREAD

**Issue by bryantabaird** [adobe/react-spectrum#1520]
# 🐛 Bug Report 

Scroll bars are showing based on the OS theme and not the light/dark theme sent to the provider. This is a regression that happened when upgrading from Chrome 87 to Chrome 88

Light Mode OS vs Dark Mode Theme
![Screen Shot 2021-01-29 at 1 28 21 PM](https://user-images.githubusercontent.com/9795404/106324497-7a078000-6236-11eb-824f-9cf2bcf53b9f.png)

Dark Mode OS vs Light Mode Theme
![Screen Shot 2021-01-29 at 1 27 45 PM](https://user-images.githubusercontent.com/9795404/106324504-7bd14380-6236-11eb-8074-5a70af60eff2.png)

## 🤔 Expected Behavior

Scroll bars should match the theme passed into the Provider.

## 😯 Current Behavior

Scroll bars match the OS theme regardless of theme passed into the Provider.

## 💻 Code Sample

https://react-spectrum.adobe.com/react-spectrum/Picker.html#asynchronous-loading
Open the select menu in the async picker to observe

OR

https://git.corp.adobe.com/pages/taborski/rsp-storybook/?path=/story/v2-v3-components-v3dialog-v2select--v-3-dialog-v-2-select 
Open the dialog and ensure you can scroll within it.

## 🌍 Your Environment

Environment is important for this issue:

Mac
Chrome 88.0.4324.96, macOS 10.15.7
Mac OS -> Display -> General -> Light vs Dark & Always Show Scrollbar

## 🧢 Your Company/Team

Adobe Analytics

**Comment by snowystinger** [comment]
I'm able to see this in our docs, and to reproduce it, I've created a sandbox to simplify https://codesandbox.io/s/determined-noether-htry2?file=/index.html

Chrome 86.0.4238.0 (r799004) appears affected by this too, so I think you were doing a bigger leap than 87 -> 88
Bisecting revealed
```
You are probably looking for a change made after 798993 (known good), but no later than 799004 (first known bad).
CHANGELOG URL:
  https://chromium.googlesource.com/chromium/src/+log/49673ad671f71162a8a81ee992f642be7fedc8f1..38b5919f7e3c17b697cd6424a07b14716b3c6895
```
I've been able to reproduce this in Safari as well.

Safari has an additional bug, which happens when switching between color schemes https://bugs.webkit.org/show_bug.cgi?id=206771

I propose this PR to fix Chrome https://github.com/adobe/react-spectrum/pull/1547
The Safari issue will need to be resolved by Safari.

FF does not support color-scheme yet, so scroll bars will appear in light unless you get a plugin. https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme#browser_compatibility
