### ISSUE TITLE
Broken focus management on controlled Select

### ISSUE THREAD

**Issue by deebov** [adobe/react-spectrum#1580]
# 🐛 Bug Report 

Broken focus management on controlled Select

## 🤔 Expected Behavior

A controlled select component should behave the same as an uncontrolled select component. Pressing up/down/space key should set the focus correctly. And type-to-search functionality works as expected.

## 😯 Current Behavior

Usually up/down arrow opens the listbox and selects the next or previous item. And the space key opens the listbox and sets the focus to the first or selected item. But when the select component is controlled, up/down keys only open and close the listbox. They don't set the focus to the next/previous item as it should. also the same issue with the space key. Pressing the space key does open the listbox but does not set the focus to the listbox.
Also type-to-search functionality does not work.

## 💻 Code Sample

The code snippet is taked from https://react-spectrum.adobe.com/react-aria/useSelect.html

https://codesandbox.io/s/dawn-firefly-dc9l4?file=/src/App.tsx

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.x

**Comment by LFDanLu** [comment]
@deebov I believe the issue you are running into is that the `selectedKey` is initialized to `""` rather than `null` (https://codesandbox.io/s/nameless-cherry-wnmji?file=/src/App.js). [`useSelectableList`](https://github.com/adobe/react-spectrum/blob/main/packages/@react-aria/selection/src/useSelectableCollection.ts#L332-L335) erroneously sets it as the focused key but since that key doesn't exist in the list of options, focus never makes it into the collection. We could definitely improve the logic there though.

As for type to select, the following pull should fix it: https://github.com/adobe/react-spectrum/pull/1374

**Comment by deebov** [comment]
hey @LFDanLu, thanks for the answer. that solved the problem tho.

**Comment by LFDanLu** [comment]
@deebov Nice glad to hear it, I'll close this issue out for now
