### ISSUE TITLE
Dynamic collections do not work if items are strings

### ISSUE THREAD

**Issue by maksimsemenov** [adobe/react-spectrum#1596]
# 🐛 Bug Report 

I'm trying to use a [dynamic collection](https://react-spectrum.adobe.com/react-stately/collections.html#dynamic-collections) pattern in my select component. But, when I pass an array of strings as items, CollectionBuilder throws an error:
```
react-dom.development.js:25108 Uncaught TypeError: Invalid value used as weak map key
    at WeakMap.set
    at CollectionBuilder.getFullNode
    at getFullNode.next
    at CollectionBuilder.iterateCollection
    at iterateCollection.next
    at Object.[Symbol.iterator]
    at Generator.next
    at new ListCollection
    at factory
```

## 🤔 Expected Behavior
It should create a collection of items

## 😯 Current Behavior
It throws an error on line 135 in `CollectionBuilder.ts`:
```js
if (node.value) {
     this.cache.set(node.value, node);
}
```

```
TypeError: Invalid value used as weak map key
```

## 💁 Possible Solution

Not use weak maps for cache? Probably will cause performance issues.
Cast string values to objects?

## 🔦 Context

I'm trying to use react aria for our internal design system. We want to be able to pass items as a list of objects and as a list of string as well

## 💻 Code Sample

```js
const animals = [ 'Aardvark', 'Kangaroo', 'Snake']

<ListBox items={animals}>{(item) => <Item>{item}</Item>}</ListBox>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| @react-stately/collections   | 3.3.0
| Browser          | Chrome 88
| Operating System |macOS Catalina

**Comment by snowystinger** [comment]
I don't know if we want to extend the API in this way, but I'll check with the team.

In the meantime, if it's a list of strings, you could map it in your component
`animals = animals.map(animal => {id: animal})`

**Comment by maksimsemenov** [comment]
Yeah, this is what I ended up doing. But I feel like with this current API react-aria prescribe how we should write our application code, which for me feels not aligned with how generic react-aria is.

Also, I'm not trying to push, so if you think that react-aria does not need this, that's totally fine. But maybe, in this case, you can add a line in the docs about this restriction.

**Comment by maksimsemenov** [comment]
Also, just wanted to add some additional detail. I'm getting this error, even if I specify a `key` property on the `Item`:
```js
const animals = [ 'Aardvark', 'Kangaroo', 'Snake']

<ListBox items={animals}>{(item) => <Item key={item}>{item}</Item>}</ListBox>

// or

<ListBox items={animals}>{(item) => <Item key={getIdForItem(item)}>{item}</Item>}</ListBox>
```

**Comment by snowystinger** [comment]
Talked it over with the team, we do not want to expand the API in this way because we use it to do very specific invalidation through object equality and cleanup with a weakmap.
Even if you do use my suggestion to alter your own API to handle this, you'll need to memo the appropriate things so you don't have extra invalidations or memory leaks.

For example, you'd really need to do something along these lines not to cause every item to re-render every time something is inserted/deleted/modified
```
// cache = {} somewhere outside the scope
animals = animals.map(animal => {
  if (cache[animal]) return cache[animal];
  else {
    cache[animal] = {id: animal};
  }
});
```
but now you have an issue of when to get rid of animals in the cache, so you'll need to handle that too
for small collections, useMemo is probably fine, yes it'll invalidate, but for small collections that's not a big deal

Closing the issue because this isn't the direction we want to take this.

**Comment by maksimsemenov** [comment]
Thanks for laying it down for me.

I have a question about cashing with weak maps.

If I generate the collection of items from some server response like this:
```js
const items = users.map(user => ({ label: user.name, value: user.id }))
```

And then will pass these items to the collection, will the weak map cache it correctly? I mean each item will be a different object every time (reference check will return false) even if `value` and `label` are the same. Will it affect weak map caching?

**Comment by snowystinger** [comment]
If you create your objects like that, then no, they will not be cached correctly, as you stated the reference check will return false. That's why I included my comment about maintaining your own cache in the expanded map example.

If you're dealing with a small`*` number of users, then it doesn't really matter. If you're dealing with many of them, then when your API returns you should map them once and use the objects instead. After all, you should only be fetching each one once, so you shouldn't have new values.
The example was just if you wanted to extend your components API to allow for an array of strings. It's more complicated than it seems which is why we can't generically handle it.

`*` i don't know what the magic small number is

**Comment by maksimsemenov** [comment]
Thanks. That makes sense
