### ISSUE TITLE
ColorWheel does not work inside a Form

### ISSUE THREAD

**Issue by devongovett** [adobe/react-spectrum#1605]
# 🐛 Bug Report 

It gets all stretched out...

<img width="360" alt="image" src="https://user-images.githubusercontent.com/19409/108397777-522c8c00-71e6-11eb-8427-b00e4c9a0e58.png">

## 💻 Code Sample

```tsx
<Form>
  <ColorWheel />
</Form>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.8
| Browser          | all
| Operating System | all
## 🧢 Your Company/Team

RSP

**Comment by marie-ototoi** [comment]
hello! I had a look at this issue, as I would like to start contributing.

It seems the bug is due to the rule
```
> * {
      margin-top: var(--spectrum-fieldlabel-margin);
      width: 100%;
    }
```
line 146 in `packages/@adobe/spectrum-css-temp/components/fieldlabel/index.css`
which overrides the width of ColorWheel - but not its height, so the container is not a square anymore

Wrapping ColorWheel in anything (plain `<div>`, `<Flex>` component) solves the problem. 

I can think of several solutions :
- mention in `ColorWheel` documentation the need to wrap it when using it inside a `<Form>`
  and add a story "in a form" to `ColorWheel` stories, using a wrapper
- or add a `<div>` wrapper in the `ColorWheel` component itself 

None of them is optimal, I am not sure which is better, what do you think?

May I work on this issue?
