### ISSUE TITLE
Crash in useSelectableCollection when ref not attached to dom node in first render

### ISSUE THREAD

**Issue by stefanprobst** [adobe/react-spectrum#1622]
# 🐛 Bug Report 

When the `ref` passed to `useSelectableCollection` is not yet attached to a DOM node in first render - and if `autoFocus` is set to truthy - a crash with `TypeError: element is undefined` happens in [this useEffect](https://github.com/adobe/react-spectrum/blob/dd52b8deffa1850ff4301c98a0db57d7bccebcdf/packages/%40react-aria/selection/src/useSelectableCollection.ts#L342), which triggers `focusSafely` => `focusWithoutScrolling` which then tries to call `focus()` on `null`.

## 🤔 Expected Behavior

No errors.

## 😯 Current Behavior

see above

## 🔦 Context

I ran into this issue when moving `useListBox` up a level in [the `useSelect` docs example](https://react-spectrum.adobe.com/react-aria/useSelect.html#example), i.e. when the listbox ref is only attached when state.isOpen becomes true.

## 💻 Code Sample

CSB was acting up, so i put a repro here: https://github.com/stefanprobst/react-aria-issue/blob/main/components/Select.js

EDIT: here's a codesandbox based on the `useSelect` docs example: https://codesandbox.io/s/react-aria-listbox-ref-r6elr?file=/src/App.js

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | latest
| Browser          | Firefox 85
| Operating System | Ubuntu 20.04

**Comment by snowystinger** [comment]
Yep, I see the issue in your project. Looks like we can just add a check to that if for the `ref.current` https://github.com/adobe/react-spectrum/pull/1629 I've opened a PR for it so we can see if there's anything else needed

**Comment by snowystinger** [comment]
Hey, so I was talking to a coworker, and we noticed that with the fix, even though it doesn't crash, we can't select any items from the picker. Any idea what's going on there? I'll try to check tomorrow as well

**Comment by stefanprobst** [comment]
hmm that's surpsrising - i'll try to dig a bit later today.

**Comment by stefanprobst** [comment]
updated issue description with CSB based on useSelect docs example.

**Comment by stefanprobst** [comment]
would it make sense to use a [callback ref](https://reactjs.org/docs/refs-and-the-dom.html#callback-refs) so ref changes can trigger a render?

**Comment by snowystinger** [comment]
Thanks for the extra information, we'll try it out soon.

**Comment by snowystinger** [comment]
Sorry for the delay, I was pulled away to some other work.

I don't think we can use a callback ref, at least, not as described here https://stackoverflow.com/questions/55838351/how-do-we-know-when-a-react-ref-current-value-has-changed
The ref is passed in and not through, and we can't really require everything using this to move over to a state kept one.

My coworker actually noted a great way to deal with this (thanks @LFDanLu) if you pull the ListBoxPopup out of the Select as we have in our docs, then this will work as expected. Since there isn't a good way for us to know when to try to do the autofocus other than after mounting, I think this is the best way to handle it. useSelectableCollection has no idea about modals and we shouldn't be passing something like "isOpen" to it or "isMounted" (which is what the callback ref amounts to)

I don't think we should continue with the PR I created to try this out. I think by not failing, it'll hide the problem that my coworker pointed out.
I'll leave this open in case you have some other ideas, but feel free to close if not.
