### ISSUE TITLE
Menu inside Overlay closes overlay on menu item hover

### ISSUE THREAD

**Issue by michalkvasnicak** [adobe/react-spectrum#1633]
# 🐛 Bug Report 

If `useInteractionModality()` is used and current pointerType is `pointer` then `MenuItem` automatically receives a focus on hover which closes the Popover.

## 🤔 Expected Behavior

Popover should stay open.

## 😯 Current Behavior

If `useInteractionModality()` is used the menu item automatically receives a focus on hover on which popover and menu closes. If `useInteractionModality()` is not used, then everything works as expected. (`useInteractionModality()` is necessary for Tooltips to work)

https://codesandbox.io/s/hopeful-herschel-0shii?file=/src/App.js

## 💁 Possible Solution

MenuItem should not receive a focus on hover.

## 🔦 Context

We have a menu inside a dialog that is used to choose a value. With this bug we are not able to select anything inside the menu, because it causes the dialog to close (`shouldCloseOnInteractOutside()` is called but there should not be any interaction on hover). This happens only if `useInteractionModality()` is called. But we can't remove `useInteractionModality()` otherwise our tooltips don't work. 

## 💻 Code Sample

https://codesandbox.io/s/hopeful-herschel-0shii?file=/src/App.js

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | see codesandbox |
| Browser          | Safari 14.0.3 |
| Operating System | macOS Big Sur |

**Comment by snowystinger** [comment]
I don't think there's an issue with useInteractionModality, I think you just are missing a couple things in your code.
I've edited your codesandbox to match our documentation a bit more https://codesandbox.io/s/thirsty-snow-oikxf?file=/src/App.js and I don't see the issue anymore.
For reference, this was the example from our documentation that I referenced https://react-spectrum.adobe.com/react-aria/useOverlayTrigger.html#example
Note, there's still more missing because if you try to select a Menu item, it'll blow up. You can find Menu docs here https://react-spectrum.adobe.com/react-aria/useMenu.html

**Comment by michalkvasnicak** [comment]
Yes you are right, I had `shouldCloseOnBlur: true` set on our `Popover` component.
