### ISSUE TITLE
[combobox] listbox opens too late when items become available

### ISSUE THREAD

**Issue by stefanprobst** [adobe/react-spectrum#1673]
# 🐛 Bug Report 

When a combobox's text input changes, and new matching items become available in a `useEffect`, the combobox's listbox does not open correctly (with menutrigger set to default "input").

## 🤔 Expected Behavior

Listbox should open.

## 😯 Current Behavior

Listbox does not open.

## 🔦 Context

I added the following story to the ComboBox storybook:

```js
function Example() {
  const [filterText, setFilterText] = useState("snake");
  const [items, setItems] = useState([]);

  useEffect(() => {
    setItems(
      filterText.length > 4
        ? []
        : [
            { id: "alligator", name: "Alligator" },
            { id: "kangaroo", name: "Kangaroo" },
          ]
    );
  }, [filterText]);

  return (
    <ComboBox
      label="Example"
      items={items}
      inputValue={filterText}
      onInputChange={setFilterText}
    >
      {(item) => <Item key={item.name}>{item.name}</Item>}
    </ComboBox>
  );
}
```

This will render a combobox with the text "snake" as `inputValue`. There are no matching `items`. The cursor is positioned at the end. When pressing <kbd>Backspace</kbd> I would expect the listbox to open, because there are now 2 matches available, and the listbox should be opened because of `menuTrigger: "input"`. However only *another* <kbd>Backspace</kbd> will open the listbox.

I added the following console log [here](https://github.com/adobe/react-spectrum/blob/30377b7558c3e621e8e52d6daf75bd69bc93dbb9/packages/%40react-stately/combobox/src/useComboBoxState.ts#L116):

```js
    console.log({ 
      hasInputChanged: inputValue !== lastValue.current,
      collectionSize: filteredCollection.size,
    });
```

which prints the following after pressing <kbd>Backspace</kbd> the first time:

```
Object { hasInputChanged: true, collectionSize: 0 }
Object { hasInputChanged: false, collectionSize: 2 }
```

So it looks like when the input value has changed, the collection has not yet been updated, but when the collection has been updated, the input value hasn't changed.

## 💻 Code Sample

see above

https://user-images.githubusercontent.com/20753323/110359274-953b8b80-803d-11eb-92a2-35a3f56a4363.mp4

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | latest |
| Browser          | Forefox 85 |
| Operating System | Ubuntu 20.04

**Comment by LFDanLu** [comment]
This is expected behavior. If you control multiple properties of the combobox, it is important to update the others controlled properties at the same time as when one of them changes (see the example [here](https://react-spectrum.adobe.com/react-spectrum/ComboBox.html#fully-controlled-combobox)). In this case you should be updating the `items` along with the `filterText` in an `onInputChange` handler rather than in a `useEffect`, perhaps something like this:

```
function Example() {
  const [fieldState, setFieldState] = useState({
    filterText: "snake",
    items: []
  });

  let onInputChange = (value) => {
    let newItems = value.length > 4
    ? []
    : [
        { id: "alligator", name: "Alligator" },
        { id: "kangaroo", name: "Kangaroo" },
      ];
    setFieldState({
      filterText: value,
      items: newItems
    })
  }

  return (
    <ComboBox
      label="Example"
      items={fieldState.items}
      inputValue={fieldState.filterText}
      onInputChange={onInputChange}
    >
      {(item) => <Item key={item.name}>{item.name}</Item>}
    </ComboBox>
  );
}
```

**Comment by devongovett** [comment]
You could also potentially not keep the filtered items in state at all and instead `useMemo` to compute them in render based on the filtered text.

**Comment by stefanprobst** [comment]
hi!

in my actual usecase, the input value is (debounced and) sent to a server to retrieve matching `items`. so updating `items` and `inputValue` simultaneously would not work.

it looks like the `AsyncLoadingExample` in the combobox storybook works around this issue with `allowsEmptyCollection` (i.e. `loadingState`) which will simply keep the combobox open(?)

**Comment by LFDanLu** [comment]
@stefanprobst I see, so you have an async loading combobox. You are correct, when the combobox is passed a `loadingState` the menu will allow an empty state to be displayed instead of closing/not opening the menu which is why it works there. Perhaps you can do the same for your combobox? My gut feeling regarding controlling `isOpen` and setting it to `true` when `items` change is that you may run into an issue when you select a item -> closes the menu -> changes your inputValue -> causes new `items` to be fetched -> menu is then opened again erroneously.
