### ISSUE TITLE
[React-Aria - Button] - Style broken on Safari

### ISSUE THREAD

**Issue by MistaPidaus** [adobe/react-spectrum#1675]
# 🐛 Bug Report 

Button component from `@react-aria` style broken on Safari when passing `elementType="div"`. 

## 🤔 Expected Behavior

Expecting that the button should be render fine as it is with `@react-aria` package with pre-define styling.

## 😯 Current Behavior

It looks broken on Safari browser. It seems like there's a "grey" background added in the button when passing `elementType="div"`. The styling that are define either by Tailwind classes or `style` prop looks like being ignore.

## 🔦 Context

Upgrading `@react-aria/button` from `@react-aria/button@3.2.2` to `@react-aria/button@^3.3.1` causing the issue. I'm not sure how it happens. Downgrading make it works again - the "greyish" background is gone and the styling applied properly on Safari browser.

## 💻 Code Sample
https://codesandbox.io/s/react-aria-button-styling-issue-dy5pi

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-aria   | 3.3.1
| Browser          | Chrome / Safari
| Operating System | MacOS

**Comment by MistaPidaus** [comment]
@LFDanLu have you tried restart the server? I restarted the server to see the changes and it looks ok on `@react-aria/button@3.2.2` version.

**Comment by snowystinger** [comment]
I believe this has more to do with how Tailwind is applied
`-webkit-appearance: button` is being added due to normalize.css https://flaviocopes.com/css-normalizing/ which Tailwind uses.
I see no difference between 3.2.2 and 3.3.1. Each element has the correct `role` on them as well as `type`. I'd log this with Tailwind or Normalize.
For instance, if you wrote those buttons yourself with that `type` on it, it'd still be styled wrong.

If you are still able to reproduce between the two versions, try to see what the difference in applied CSS is. It might just be the order in which the css ends up in the doc, causing specificity collisions to display differently. Let us know if you find otherwise.

**Comment by MistaPidaus** [comment]
I just noticed that when upgrading to 3.3.1, `type="button"` is added by default if you pass `elementType="div"`. It doesn't occur on 3.2.2 - it doesn't pass the `type="button"` even if you change or pass (or not passing) `elementType=`.

Is it intended? I know the styling webkit has to do with Tailwind/Normalize but just wanna make sure which I part I have to take action.

**Comment by devongovett** [comment]
Looks like a bug. `type="button"` shouldn't be applied on non `<button>` elements.
