### ISSUE TITLE
FocusScope trigger :focus-visible on Firefox

### ISSUE THREAD

**Issue by pascalduez** [adobe/react-spectrum#1688]
# 🐛 Bug Report 

A `<FocusScope contain autoFocus>` seems to trigger `:focus-visible` styles under on Firefox. 

## 🤔 Expected Behavior

`:focus-visible` styles should not be applied.

## 😯 Current Behavior

 `:focus-visible` styles are applied under on Firefox. 
On Chrome this is not happening.

## 🔦 Context

Implementing a Dialog component with a close button inside. The close button shouldn't get the focus styles on programatic or mouse focus, just keyboard navigation.

## 💻 Code Sample

**Repro** https://codesandbox.io/s/sparkling-water-7fjm2  

**Firefox result**
`"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0"`
![Screenshot from 2021-03-11 19-34-00](https://user-images.githubusercontent.com/335467/110837451-86eda980-82a1-11eb-85e6-c4aa0a2928aa.png)

**Chrome result**
`"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"`
![Screenshot from 2021-03-11 19-35-55](https://user-images.githubusercontent.com/335467/110837477-90771180-82a1-11eb-9f48-1c5cce134007.png)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-aria   | 3.2.2
| Operating System | Linux

**Comment by devongovett** [comment]
Hmm I see the same in Chrome and Safari as Firefox. My guess is that this has to do with the heuristic the browser uses to determine whether to show the focus ring or not. FocusScope uses programmatic `.focus()` calls to move focus, and this likely causes the browser to activate `:focus-visible` because the focus didn't come from a user interaction. My suggestion would be to use our [useFocusRing](https://react-spectrum.adobe.com/react-aria/useFocusRing.html) hook to manage this instead, as it is aware of programmatic focus calls and they do not affect the modality of the page. You could also file bugs against the browsers for this, as it's likely going to be a common issue for people.

**Comment by pascalduez** [comment]
Before opening this issue I found https://bugzilla.mozilla.org/show_bug.cgi?id=1618639, but looks like they have changed that behaviour, so a programatic focus shouldn't trigger `:focus-visible`. Also in the repro sandbox there's a bare `.focus()` not nested in a `FocusScope` which doesn't have the problem.

**Comment by devongovett** [comment]
I don't think this is a react-aria issue. Here's a modified reproduction that just uses an explicit `focus()` call on a ref, without any react-aria dependencies: https://codesandbox.io/s/gallant-microservice-kkfuj?file=/src/App.js. For me it shows the red outline across all browsers.

Again, you can use the useFocusRing hook which may provide better cross browser consistency than `:focus-visible`.
