### ISSUE TITLE
@react-spectrum/icon has required peerDependency of @react-spectrum/provider when @adobe/react-spectrum also satisfies

### ISSUE THREAD

**Issue by joelrbrandt** [adobe/react-spectrum#1713]
# 🐛 Bug Report 

I am using the monopackage `@adobe/react-spectrum`. When I add the dependency `@spectrum-icons/workflow`, I get an unmet peer dependency error for the package `@react-spectrum/provider`.

## 🤔 Expected Behavior

If I have `@adobe/react-spectrum` as a dependency, I should be able to add `@spectrum-icons/workflow` as a dependency without getting any peer dependency errors.

## 😯 Current Behavior

I get an error that peer dependency `'@react-spectrum/provider': '^3.0.0-rc.1'` is not met. This peer dependency is required by `@react-spectrum/icon`, which is itself a dependency of `@spectrum-icons/workflow`.

This causes problems when using a package manager that is strict about peer dependencies (e.g. [PNPM](https://pnpm.js.org/))

## 💁 Possible Solution

There are two possible solutions that I can think of:

1. drop this peer dependency entirely, or replace it with a peer dependency of `@adobe/react-spectrum`, as that is the more typical (I think?) way to use RSP.
2. Mark the peer dependency as optional using [`peerDependenciesMeta`](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#peerdependenciesmeta)

If option 2 is chosen, _both_ `@adobe/react-spectrum` and `@react-spectrum/provider` could be listed as optional peer dependencies, both with version numbers. This would help some package managers understand if correct versions were installed.

There is also a workaround (if using PNPM) of adding a read package hook like this:

```javascript
if (packageJson.name === "@react-spectrum/icon") {
  if (
    packageJson.peerDependencies !== undefined &&
    packageJson.peerDependencies["@react-spectrum/provider"] !== undefined
  ) {
    delete packageJson.peerDependencies["@react-spectrum/provider"];
    context.log("@react-spectrum/icon: removed peer dependency '@react-spectrum/provider'");
  }
}
```

## 🔦 Context

I am trying to use RSP with a package manager that is strict about peer dependencies (PNPM)

## 💻 Code Sample

N/A

## 🌍 Your Environment

package manager: PNPM version 5.17.3

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.8.0 |
| Browser          | N/A |
| Operating System | mac |

## 🧢 Your Company/Team

Adobe/Adobe Research

**Comment by devongovett** [comment]
Why do you need `@react-spectrum/icon` rather than using the icon component that's included in `@adobe/react-spectrum` already? I think the peer dependency is correct - peers cannot be satisfied by a transitive dependency (e.g. through `@adobe/react-spectrum`), so if you want an individual package for some reason, you'll also need to declare the versions of the peers it relies on in your app.

**Comment by joelrbrandt** [comment]
@devongovett Thanks for following up. Actually, I experienced this error when adding `@spectrum-icons/workflow` as an explicit dependency to my package (I wasn't adding `@react-spectrum/icon` directly.)

That package has a dependency on `@react-spectrum/icon`. And, when pnpm installed `@react-spectrum/icon`, it complained that I had an unmet peer dependency because `@react-spectrum/provider` was not installed.

Should I be installing some package other than `@spectrum-icons/workflow`?

I agree that peers cannot be satisfied by a transitive dependency. However, it seems less than ideal to be forced to add `@react-spectrum/provider` to my dependency list in addition to `@adobe/react-spectrum` (and to keep their versions in sync in order to not have unnecessarily duplicated packages in my node_modules -- especially given that the monopackage and its dependencies do not use lock-step versioning). 

If I understand correctly (and it's very possible that I don't!), having `@adobe/react-spectrum` as an explicit dependency (and *not* having `@react-spectrum/provider` as an explicit dependency) does actually provide what `@spectrum-icons/workflow` needs.

That's why I proposed listing both potential peer dependencies and marking them as optional.

Do you have another proposed workflow?

**Comment by devongovett** [comment]
Hmm perhaps it would be simpler to just make `@react-spectrum/provider` a real dependency rather than a peer dependency?

**Comment by joelrbrandt** [comment]
@devongovett 

> Hmm perhaps it would be simpler to just make @react-spectrum/provider a real dependency rather than a peer dependency?

I am certainly not an expert in package management, but this sounds fine to me.

The one complication I think it will introduce is that it would be important to keep the semver line for the `@react-spectrum/provider` dependency the same in both `@adobe/react-spectrum` and `@react-spectrum/icon` (or, at least to make sure that the one in `@react-spectrum/icon` is more general than the one in `@adobe/react-spectrum`

Otherwise, two versions of `@react-spectrum/provider` could get installed, and node / webpack / whomever would resolve the dependency differently depending on where the `require` line lives.

**Comment by devongovett** [comment]
Neither of those options are ideal, and both may cause other problems. Provider should not be a real dependency because then you would potentially get duplicates if the ranges do not match. This will break your app because the context that Provider sets won't be the same as the one being consumed by all components. The peer dependency should also not be optional because without provider it won't work. Individual packages may also require a different version of provider than the version provided by the monopackage, and your package manager should tell you when this is not satisfied.

The solutions are either to use the monopackage `@adobe/react-spectrum`, which provides this peer dependency, or when using an individual package, also add `@react-spectrum/provider` as a dependency of your app. The version must match the one provided by the monopackage and be >= to the version required by all of the components.

I'm not really aware of another solution than doing this yourself when using individual packages.

**Comment by snowystinger** [comment]
Closing, my understanding is that this is not something we can support on our end and the expectation is that users will need to manage it if they use individual packages
