### ISSUE TITLE
Table - sluggish filtering performance

### ISSUE THREAD

**Issue by jluyau** [adobe/react-spectrum#1803]
# 🐛 Bug Report 

When filtering rows in a table, the filtering animations cause the application to feel a bit sluggish.

## 🤔 Expected Behavior

Filtering out of rows should feel snappy.

## 😯 Current Behavior

The filtering of the rows happens after a little delay of the trigger event. 

## 💻 Code Sample

https://codesandbox.io/s/blue-dew-z0woi?file=/src/App.js

Use the search field to filter the table row names and observe the filtering animations

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.9.0
| Browser          | Chrome
| Operating System | macOS Catalina 10.15.7

## 🧢 Your Company/Team

Adobe/quarry

**Comment by LFDanLu** [comment]
Did some digging and the performance issues are partially due to table animations (post input change in SearchField) and partially due to https://github.com/adobe/react-spectrum/issues/1516 it seems (entering and typing the first letter in the SearchField causes rerenders in every component on the page w/ a FocusRing).

**Comment by dannify** [comment]
Addressed.
