### ISSUE TITLE
`isHovered` from the `useHover()` hook is not updated when a button is disabled

### ISSUE THREAD

**Issue by AJLemos** [adobe/react-spectrum#1838]
# 🐛 Bug Report 

`useHover()` takes a `isDisabled` prop which blocks hover events when the button is disabled. This works well.

However if a button is disabled _while_ it is being hovered the hover state sticks on the disabled button.

## 🤔 Expected Behavior

Hovering then pressing the button in the Example component below will render:

```
<button disabled>Hover & Press</button>
```

## 😯 Current Behavior

Hovering then pressing the button in the Example component below currently renders:

```
<button data-hover="true" disabled>Hover & Press</button>
```

This leaves the disabled button in a hovered state, but disables buttons can not be hovered when using `useHover({ isDisabled });`.

The `useHover()` hook should not return `true` for `isHovered` when `isDisabled` is set to `true`.

## 🔦 Context

This happening on one of our buttons that becomes disabled after pressing it. The hovered style can be overridden in CSS by adding scope for the disabled & hovered state, but ideally the hovered state would be omitted when the button becomes disabled.

## 💻 Code Sample

Here is a Code Pen demonstrating the bug: https://codepen.io/ajlemos/pen/qBRLgwx

```jsx
import React from 'react';

import { mergeProps } from '@react-aria/utils';
import { useButton } from '@react-aria/button';
import { useHover } from '@react-aria/interactions';

function Button(props) {
  let {
    children,
    isDisabled,
  } = props;

  let buttonRef = useRef();

  let { buttonProps } = useButton(props, buttonRef);
  let { hoverProps, isHovered } = useHover({ isDisabled });

  return (
    <button
      data-hover={isHovered || null}
      type="button"
      {...mergeProps(buttonProps, hoverProps)}
      ref={buttonRef}
    >
      {children}
    </button>
  );
}

export default Button;
```

```jsx
import React, { useState } from 'react';

import Button from './Button';

function Example(props) {
  let [ isDisabled, setIsDisabled ] = useState();

  return (
    <Button
      isDisabled={isDisabled}
      onPress={() => setIsDisabled(true)}
    >
      Hover & Press
    </Button>
 );
}

export default Example;
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-aria/interactions   | 3.3.0
| Browser          | Chrome, Safari, Firefox
| Operating System | MacOS Big Sur

## 🧢 Your Company/Team

SmugMug 😄

**Comment by snowystinger** [comment]
https://codesandbox.io/s/cocky-zhukovsky-eb879?file=/src/App.js
here's a reproduction

**Comment by AJLemos** [comment]
Thanks. I also added a CodePen: https://codepen.io/ajlemos/pen/qBRLgwx

**Comment by snowystinger** [comment]
ah, right you are, i saw all the code and missed the link. Thank you!
looks like we'd need to triggerHoverEnd when isDisabled changes to true https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/interactions/src/useHover.ts#L126
then the event handlers would need to be aware of disabled as well, because we don't want to add that check back into triggerHoverEnd (it used to have that https://github.com/adobe/react-spectrum/commit/03ebcdf7a14af5535c8c030725cf795db1cad0a1#diff-26243ab3d88fb6553f0d6b22913650280616705e1741f2b8a950b63826979bdaL127)
So probably around here would be a more appropriate place for the check https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/interactions/src/useHover.ts#L161

**Comment by AJLemos** [comment]
You didn't miss it. I created the CodePen and added the link after posting 😄 . Thanks for the explanation and links!
