### ISSUE TITLE
Broken on snowpack, bump intl-messageformat

### ISSUE THREAD

**Issue by stephenh** [adobe/react-spectrum#1849]
I'm trying to use react-aria on a project that uses snowpack.

I'm running into this issue, which could potentially be a bug in snowpack's handling of the `intl-messageformat-parser` module:

https://github.com/snowpackjs/snowpack/issues/3155

However, it looks like that package is deprecated anyway:

https://www.npmjs.com/package/intl-messageformat-parser

And when I ask "why does my project have this dep", it comes via `@internationalzed/message`:

```
$ npm ls intl-messageformat-parser
...
└─┬ ...
  └─┬ react-aria@3.5.0
    └─┬ @react-aria/i18n@3.3.0
      └─┬ @internationalized/message@3.0.0-alpha.0
        └─┬ intl-messageformat@2.2.0
          └── intl-messageformat-parser@1.4.0
```

It looks like `intl-messageformat@2.2.0` is a pretty old release, the current one is 9.6.11:

https://github.com/formatjs/formatjs/blob/main/packages/intl-messageformat/CHANGELOG.md

...which actually mentioned the 9.6.9 release specifically fixed ESM issues.

Could react-aria bump the `intl-messageformat` dep to hopefully make building with an ESM tool chain work?

**Comment by snowystinger** [comment]
Seems like something we should update, 2.2.x was 3 years ago. We'll have to look at what the breaking changes were from 2 -> 9 though, haha

**Comment by snowystinger** [comment]
From a quick glance, it looks like updating this all the way to version 9 will require us to update some other things as well. Otherwise we get ` error TS2694: Namespace 'Intl' has no exported member 'RelativeTimeFormat'.`
Unfortunately, updating to node14 and changing TS target to esNext does not solve this. Also, we make use of the package full-icu already, so may need to do something different there as well.

It would appear from your initial message that we need to go to 9, there isn't an earlier version we could move to so we can more gradually introduce/contemplate these changes?

**Comment by stephenh** [comment]
@snowystinger I honestly don't know, I haven't tried any prior versions or even version 9 honestly, I just saw "ESM fixes" go by in their changelog, and working ESM is generally what snowpack wants, so I'm making an assumption there...

**Comment by snowystinger** [comment]
I had a bit of time this evening, so I came up with two branches, one with the minimal changes I believe this will require https://github.com/adobe/react-spectrum/compare/upgrade-intl-messages-minimal?expand=1

and one with an upgrade to TS that would make our lives in the future hopefully easier
https://github.com/adobe/react-spectrum/compare/upgrade-intl-messages?expand=1

I'll present them to the team and see if we think either of these is a good idea. If you have any other thoughts on it, please don't hesitate to chime in.

**Comment by stephenh** [comment]
Awesome, thanks @snowystinger !
