### ISSUE TITLE
inconsistent isPressed state when focus is moved to another element

### ISSUE THREAD

**Issue by deebov** [adobe/react-spectrum#1870]
# 🐛 Bug Report 

We have a Select component that uses react-aria's hooks. When the select popover opens we move the focus to another dom element inside the popover. When we move the focus to another element like this, button's isPressed stays true.

## 🤔 Expected Behavior

isPressed should be false when we change the focus from button to another element

## 😯 Current Behavior

button's isPressed state stays true when focus is moved to another dom element. And since isPressed true button will ignore press/click event triggers.

## 🔦 Context

we have a components library that uses react-aria

## 💻 Code Sample

https://codesandbox.io/s/naughty-blackwell-nnsxu?file=/src/App.tsx

**Comment by LFDanLu** [comment]
@deebov I tried your codesandbox and it seems to toggle the input element appearance on/off just fine. The console.logs seem to indicate that isPressed is being set to false on mouse up as well.

**Comment by deebov** [comment]
> @deebov I tried your codesandbox and it seems to toggle the input element appearance on/off just fine. The console.logs seem to indicate that isPressed is being set to false on mouse up as well.

oh sorry, I forgot to be more specific. 

1. Refresh the page
2. Set the focus to button with Tab
3. Press Space
4. Click the button with mouse and it should ignore the click

**Comment by snowystinger** [comment]
Looks like we have something that's supposed to be dealing with that https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/interactions/src/usePress.ts#L226
but isn't, I'd start debugging here

**Comment by LFDanLu** [comment]
Thanks for the repro steps @deebov, will need to investigate why that line that @snowystinger linked doesn't seem to be handling this situation properly

**Comment by alirezamirian** [comment]
Experiencing the same issue. A similar re-production scenario sandbox: https://codesandbox.io/s/react-spectrum-template-forked-vy3n1m?file=/src/App.js

Did some digging and here is the result:

When the input is focused immediately after keydown, keyup happens on the input. To handle this case, [onKeyUp handler is set on document](https://github.com/adobe/react-spectrum/blob/9498c7d858b08e03b4c36fac491b9e4434453da0/packages/%40react-aria/interactions/src/usePress.ts#L245-L247) (probably what @snowystinger linked too as well). And there is even a test case for that: https://github.com/adobe/react-spectrum/blob/a162e5b235fcdc79087ea6d64c726664dc9d4179/packages/%40react-aria/interactions/test/usePress.test.js#L2071

BUT, in that test case, keyup is triggered on `body`. It's different when it's triggered on an `input`, because `isValidKeyboardEvent` here would return false in that case: 
https://github.com/adobe/react-spectrum/blob/9498c7d858b08e03b4c36fac491b9e4434453da0/packages/%40react-aria/interactions/src/usePress.ts#L292 

And `state.isPressed` would not reset to false.

I adjusted the test case in this branch to cover this case too: https://github.com/adobe/react-spectrum/commit/e5740c3971986932226325b046f9fbb765c812ea

Removing `isValidKeyboardEvent` check in `onKeyUp` would pass the updated test without breaking any other test case, but I don't have a good overview of `usePress` and am not sure if everything in that `if` block should run in this case.

**Comment by alirezamirian** [comment]
I can still open a small PR from https://github.com/adobe/react-spectrum/commit/e5740c3971986932226325b046f9fbb765c812ea to adjust the existing test case to cover this scenario. Let me know if it makes sense.

**Comment by snowystinger** [comment]
We'd love it if you contributed a test. The better and more accurate our tests the less likely we are to regress and that's fantastic

**Comment by devongovett** [comment]
Going to close this since apparently it's fixed.
