### ISSUE TITLE
NumberField positivity/negativity sign should be to the left of the number instead of the right when inputting arabic numerals

### ISSUE THREAD

**Issue by hadihallak** [adobe/react-spectrum#1880]
# 🐛 Bug Report 

NumberField positivity/negativity sign should be to the left of the number instead of the right when inputting Arabic numerals

## 🤔 Expected Behavior
a positive/negative numbers should look like this with the minus/plus sign to the left of the number:
`-٣٢` 
`+٨٨`

## 😯 Current Behavior
the minus/plus sign is to the right of the number:
`٣٢-`
`٨٨+`

**Comment by solimant** [comment]
Hi @hadihallak - the negative sign in Arabic numerals should, in fact, be on the right hand side, not on the left. Otherwise, something like the following equation would be confusing to represent:

![image](https://user-images.githubusercontent.com/11140840/117499262-d3670580-af2f-11eb-8fa5-663b886b0f5d.png)

Which reads:
-2 + (-3) = -5

You would need to be in true RTL mode in order to experience this properly; e.g.
```
<html lang="ar" dir="rtl">
```

There are several online sources regarding how negative numbers are represented on the number line in Arabic. This [one](https://www.nagwa.com/ar/videos/412170865015/) is the briefest one I could fine.

**Comment by hadihallak** [comment]
@solimant when looking at a number in isolation, I was sure the negative sign should be on the left. I even asked other native Arabic speakers and they also agreed that it should be on the left until I mentioned your point about equations which is when we all realized that we all are out of practice when it comes to writing Arabic numerals 😄 

Sorry about that and thanks for the reminder 😬
