### ISSUE TITLE
[@internationalized/number] Which version of "isValidPartialNumber" is correct?

### ISSUE THREAD

**Issue by Westbrook** [adobe/react-spectrum#2039]
In the README.md for `@internationalized/number` you list the following as `true` when tested with the `isValidPartialNumber` method of a parser.
```
let parser = new NumberParser('en-US', {style: 'unit', unit: 'inch'});
parser.isValidPartialNumber('10 i')); // -> true
```
However, in test, you list the same as being `false`:
https://github.com/adobe/react-spectrum/blob/d04e70b27e40d0a04312d8c5e40127eceeefcd22/packages/%40internationalized/number/test/NumberParser.test.js#L246-L247
Which is the expected functionality?

When paired with a Number Field style input, the documented version would allow for a user who chose to start typing the `input` _unit_ to be considered "valid", which seems like a nice user experience, but I can see that a Number Field might be "more correct" when not taking unnecessary non-number input. Clarification on what you mean to ship here would make is easy to support moving in one direction of another with the interfaces we build from this tool.

Thanks!

**Comment by snowystinger** [comment]
The behavior we have is the correct one. If I'm remembering correctly, it proved quite difficult to support typing the partial units/currency symbols. This was due to a situation where the symbol could contain the group or decimal character, such as `150,00 щ.д.` which is `Intl.NumberFormat('bg-BG', {style: 'currency', currency: 'USD'})` and a conflict with trying to be lenient on what is a group symbol and what is a decimal symbol while typing. The biggest issue I think being a combination of not knowing all the combos of numerals systems, currency symbols, unit symbols, and locales. We don't know if there is some case where the symbol might start with either a comma or a decimal, which could lead us to parsing something wrong. someone typing `.1.5` -> `.foo 1.5`, `.foo 0.15`.
One other point of interest, it's tough for a user to know if the expected symbol is long or short or narrow, for instance, do they type ` feet`? or ` ft`? or `ft`? (respectively, in the last one, there is no space), see unitDisplay https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat
and spaces can also be group symbols, just to further confuse things.

This was a while ago, and all of this code has undergone changes since we talked about this issue. We would have liked to have been able to support the partial number AND partial symbol, and it *may* be possible now, but we're not prioritizing it.
All this to say, we should probably update our documentation to reflect how it actually works, and I'll check with the team next week to make sure I didn't remember anything wrong.
