### ISSUE TITLE
On mobile devices, NumberField focus gets stuck when a step button becomes disabled

### ISSUE THREAD

**Issue by Doesntmeananything** [adobe/react-spectrum#2119]
# 🐛 Bug Report 

Hi! These are the steps to reproduce the issue:

1. Be on a mobile device or emulate one via the browser dev tools.
2. Set the number field value one step above the `minValue`.
3. Tap the decrement button.
4. Tap anywhere outside the NumberField.

## 🤔 Expected Behavior

The focus outline should disappear, since we're tapping outside the focused NumberField and triggering the blur event.

## 😯 Current Behavior

The focus outline stays on the NumberField, even when focusing another element.

https://user-images.githubusercontent.com/34657799/126028938-3817cf7f-445e-4b00-bf89-08c222765f91.mp4

## 💁 Possible Solution

I'm not too sure, but as far as I can tell, the underlying cause is that `FocusRing`'s `isFocusWithin` ref doesn't get updated if the stepper gets disabled after tapping on it.

## 🔦 Context

When working with NumberFields, it's common to step down/up to the min/max values, which triggers the focus getting stuck and results in visually confusing behaviour of this component.

## 🌍 Your Environment

Please note that the issue is reproducible in the official docs: https://react-spectrum.adobe.com/react-spectrum/NumberField.html#value

| Software         | Version(s) |
| ---------------- | ---------- |
| @react-aria/focus   | 3.4.0
| @react-aria/numberfield | 3.0.0
| @react-stately/numberfield | 3.0.1
| Browser          | Google Chrome 91.0.4472.164

**Comment by devongovett** [comment]
Appears to be an issue only in Android Chrome. On iOS it works properly...

**Comment by Doesntmeananything** [comment]
After some digging, I've found an upstream React issue that's most likely causing this: https://github.com/facebook/react/issues/9142

And someone has already opened a similar rsp issue concerning disabled buttons: https://github.com/adobe/react-spectrum/issues/1164

As suggested in #1164 by @snowystinger, I was able to fix the issue using `FocusManager`: https://react-spectrum.adobe.com/react-aria/FocusScope.html#usefocusmanager-example. Basically, my hacky workaround checks if we can no longer decrement or increment the NumberFIeld value and if so, it moves focus to another button that's not disabled (which makes clicking outside the component remove the focus correctly).

Since the root cause is in React and various browser inconsistencies, which falls outside of the scope of rsp, I'd be happy to mark the issue as closed. But seeing as the issue appears in the basic usage of the component (so you don't need to anything application-specific to trigger it) and if you guys feel that it's in the spirit of rsp to tackle these browser quirks and provide the best UX possible no matter what, I'd volunteer to work on something that can help mitigate the problem.

**Comment by tomsontom** [comment]
In #1935 i added a possible solution for the upstream bug

**Comment by snowystinger** [comment]
So I don't think this is related to the other issue or that facebook issue. The buttons never actually get focus, instead, focus is on the input element, see https://github.com/adobe/react-spectrum/blob/main/packages/@react-aria/numberfield/src/useNumberField.ts#L262.
However, the input is not getting a blur call when you tap off the NumberInput. https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/interactions/src/useFocusWithin.ts#L62

I'm headed to this line because the entire component retains its focus ring styling, which is driven by this FocusRing instance https://github.com/adobe/react-spectrum/blob/main/packages/%40react-spectrum/numberfield/src/NumberField.tsx#L131

I'm unfortunately not able to debug this right now (combination of old android device + wifi I don't have control over). Keep in mind, this is Android specific, so it's unlikely to be related to a React bug unless the React bug also says Android. Would one of you be willing to look into it more. I'll see if someone else on the team can look as well, but you can help it go faster :)
