### ISSUE TITLE
Checkboxes and buttons can't be navigated with tab in Safari

### ISSUE THREAD

**Issue by moonrise-tk** [adobe/react-spectrum#2128]
# 🐛 Bug Report 

Can't use tab to focus/unfocus buttons or checkboxes in Safari

## 🤔 Expected Behavior

Should be able to use tab/shift+tab to navigate checkboxes and buttons

## 😯 Current Behavior

[Code sandbox here](https://7qf69.csb.app/)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 1.2.1 |
| Browser          | Safari |
| Operating System | MacOS |

**Comment by devongovett** [comment]
This is due to a Safari setting  – it's also true of native input elements, not just React Spectrum. You can find it in the Advanced preferences.

<img width="904" alt="Screen Shot 2021-07-19 at 8 07 47 PM" src="https://user-images.githubusercontent.com/19409/126256075-0acb99ef-d372-4b33-aebd-7ed897781398.png">

Alternatively, there's also a system level setting for this in System Preferences -> Keyboard -> Shortcuts. You can read more about it in our article: https://react-spectrum.adobe.com/blog/building-a-button-part-3.html#ensuring-consistent-focus-behavior

**Comment by moonrise-tk** [comment]
Unbelievable...

Thanks!
