### ISSUE TITLE
Tooltip with disabled button

### ISSUE THREAD

**Issue by natvilla** [adobe/react-spectrum#2230]
# 🐛 Bug Report 
TooltipTrigger not working with a disabled button

## 🤔 Expected Behavior
Tooltip should display on a disabled button as well as active like so
<img width="316" alt="RSP" src="https://user-images.githubusercontent.com/2700336/130109024-d4de73ff-bc7a-44b0-931e-d0986165c6ae.png">

## 😯 Current Behavior
Tooltip does not show up

## 🔦 Context
Was trying to add RBAC related tooltip to a button.
Had to get around issue by wrapping button with a div and handling own state 

## 💻 Code Sample

```
      <TooltipTrigger delay={0}>
        <ActionButton aria-label="Edit Name" isDisabled={true}>
          <Text>My button</Text>
        </ActionButton>
        <Tooltip>Change Name</Tooltip>
      </TooltipTrigger>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |  3.10.0
| Browser          | Chrome
| Operating System | MacOS

## 🧢 Your Company/Team
AEP / Quarry / RBAC

**Comment by dannify** [comment]
This is an accessibility violation. Tooltips need a focusable element to appear on hover and focus. A disabled button does not focus. Adding a wrapping div will also cause an accessibility failure. Instead of this, try using some help text or an additional quiet ActionButton with a ? icon to indicate why.

**Comment by natvilla** [comment]
Thanks for the tip Danni!
