### ISSUE TITLE
Combobox popover's height cannot be adjusted

### ISSUE THREAD

**Issue by eminecula7** [adobe/react-spectrum#2305]
# 🐛 Bug Report 

In certain situations the Combobox popover is rendered behind other elements on the page (e.g. when the Combobox is in an iframe and another element with higher z-index is outside of it).

## 🤔 Expected Behavior

The maxHeight of the popover should be customizable.

## 😯 Current Behavior

The height of the Combobox popover cannot be adjusted/limited manually so sometimes it will be (partially) rendered behind other elements on the same page.

## 💁 Possible Solution

Allow users to set the maxHeight of the popover.

## 💻 Code Sample

https://codesandbox.io/s/ecstatic-mayer-4bbsq

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.8.0 |
| Browser          | Chrome |
| Operating System | MacOS |

## 🧢 Your Company/Team

Adobe Analytics UI Team

**Comment by snowystinger** [comment]
Thanks for submitting this, can you create a codesandbox that reproduces this behavior so we have more information?
I don't know if this is something we'd want to support because then you'd need to measure everything that overlaps the iframe in order to determine what the height should be? it seems like it'd be better to not cover the iframe unless it's a modal situation so that you can't interact with anything in the iframe unless the modal is gone?

**Comment by eminecula7** [comment]
@snowystinger I've added a codesandbox, but it doesn't look ideal. I don't know what's missing, but the important thing is that the issue described above can be observed there.
Note: In our case, there is only one header covering the iframe (and its height and position are fixed), so calculating the maxHeight of the combobox popover is an rather easy task for us. We only need a way to set this value on the popover.

**Comment by LFDanLu** [comment]
We are currently investigating this and are reaching out to the Shell team to see if we can figure out a fix with how the iframe interacts with the Shell.

**Comment by jpgilchrist** [comment]
Any update on this item? I actually don't think you need a sandbox as it's visible in the documentation.

https://react-spectrum.adobe.com/react-spectrum/ComboBox.html#asynchronous-loading

Async Loading in the combbox will infinitely load until the popover finally runs out of room vertically. I'd like to set the popover max height so that the load more doesn't continuously run as the height of it expands.

**Comment by LFDanLu** [comment]
So we won't be supporting this for the React Spectrum ComboBox but the `maxHeight` setting has been made available in `useOverlayPosition` here: https://github.com/adobe/react-spectrum/pull/2673, will be available in the next release.
