### ISSUE TITLE
Consider upgrading to a component-based API

### ISSUE THREAD

**Issue by ianstormtaylor** [adobe/react-spectrum#2331]
This library is awesome for the breath it provides for components and interactions and accessibility. Everything is clearly very well considered. And the goal of it being completely customizable is admirable and why I'd use it.

But as a user, the majority of my time using it is spent in **very** frustrating to debug "glue code" between the many hooks. It may not feel confusing as maintainers because you know the ins and outs of every hook, but let me tell you as a user, this is an **extremely** confusing library.

A big part of this is because of the decision to only provide hooks as the main API. The existing hooks are great for low-level use cases where some hyper-specific customization is required. But 90% of use cases don't need this.

I think this library would greatly benefit from taking an approach similar to [Headless UI](https://headlessui.dev/), which is based around components. With smart use of internal context to connect things together they are able to eliminate all of the tedious glue code, allowing you to focus purely on the components, state, and events. It's wonderfully simple to reason about. (And the existing hooks API could still be available for the 10% of cases that need extreme customization.)

---

For context, take a look at how implementing a Listbox differs between React ARIA's current API, and how HeadlessUI does it...

<details>
<summary>React ARIA</summary>

```tsx
import React from "react";

import {
  useSelect,
  HiddenSelect,
  mergeProps,
  useFocusRing,
  useButton,
  useListBox,
  useOption,
  useOverlay,
  DismissButton,
  FocusScope
} from "react-aria";
import type { AriaListBoxOptions } from "@react-aria/listbox";
import type { AriaSelectProps } from "@react-types/select";
import type { Node } from "@react-types/shared";
import { ListState, Item, useSelectState } from "react-stately";

const animals = [
  { id: "red panda", name: "Red Panda" },
  { id: "cat", name: "Cat" },
  { id: "dog", name: "Dog" },
  { id: "aardvark", name: "Aardvark" },
  { id: "kangaroo", name: "Kangaroo" },
  { id: "snake", name: "Snake" }
];

export function ReactAria() {
  return (
    <Select label="Favorite Animal">
      {animals.map((animal) => (
        <Item key={animal.id}>{animal.name}</Item>
      ))}
    </Select>
  );
}

function Select<T extends object>(props: AriaSelectProps<T>) {
  let state = useSelectState(props);
  let ref = React.useRef(null);
  let { labelProps, triggerProps, valueProps, menuProps } = useSelect(
    props,
    state,
    ref
  );
  let { buttonProps } = useButton(triggerProps, ref);
  let { focusProps, isFocusVisible } = useFocusRing();
  return (
    <div className="inline-flex flex-col relative w-52 mt-4">
      <div
        {...labelProps}
        className="block text-sm font-medium text-gray-700 text-left cursor-default"
      >
        {props.label}
      </div>
      <HiddenSelect
        state={state}
        triggerRef={ref}
        label={props.label}
        name={props.name}
      />
      <button
        {...mergeProps(buttonProps, focusProps)}
        ref={ref}
        className={`p-1 pl-3 py-1 relative inline-flex flex-row items-center justify-between rounded-md overflow-hidden cursor-default shadow-sm border-2 outline-none ${
          isFocusVisible ? "border-pink-500" : "border-gray-300"
        } ${state.isOpen ? "bg-gray-100" : "bg-white"}`}
      >
        <span
          {...valueProps}
          className={`text-md ${
            state.selectedItem ? "text-gray-800" : "text-gray-500"
          }`}
        >
          {state.selectedItem
            ? state.selectedItem.rendered
            : "Select an option"}
        </span>
      </button>
      {state.isOpen && (
        <Popover isOpen={state.isOpen} onClose={state.close}>
          <ListBox {...menuProps} state={state} />
        </Popover>
      )}
    </div>
  );
}

function ListBox(
  props: {
    listBoxRef?: React.RefObject<HTMLUListElement>;
    state: ListState<unknown>;
  } & AriaListBoxOptions<unknown>
) {
  const ref = React.useRef<HTMLUListElement>(null);
  const { listBoxRef = ref, state } = props;
  const { listBoxProps } = useListBox(props, state, listBoxRef);
  return (
    <ul
      {...listBoxProps}
      ref={listBoxRef}
      className="max-h-72 overflow-auto outline-none"
    >
      {[...state.collection].map((item) => (
        <Option key={item.key} item={item} state={state} />
      ))}
    </ul>
  );
}

function Option(props: { item: Node<unknown>; state: ListState<unknown> }) {
  const { item, state } = props;
  const ref = React.useRef<HTMLLIElement>(null);
  const { optionProps, isDisabled, isSelected, isFocused } = useOption(
    { key: item.key },
    state,
    ref
  );

  let text = "text-gray-700";
  if (isFocused || isSelected) {
    text = "text-pink-600";
  } else if (isDisabled) {
    text = "text-gray-200";
  }

  return (
    <li
      {...optionProps}
      ref={ref}
      className={`
        m-1 rounded-md py-2 px-2 text-sm outline-none cursor-default flex items-center justify-between 
        ${text} 
        ${isFocused ? "bg-pink-100" : ""} 
        ${isSelected ? "font-bold" : ""}
      `}
    >
      {item.rendered}
    </li>
  );
}

function Popover(props: {
  popoverRef?: React.RefObject<HTMLDivElement>;
  children: React.ReactNode;
  isOpen?: boolean;
  onClose: () => void;
}) {
  const ref = React.useRef<HTMLDivElement>(null);
  const { popoverRef = ref, isOpen, onClose, children } = props;
  const { overlayProps } = useOverlay(
    {
      isOpen,
      onClose,
      shouldCloseOnBlur: true,
      isDismissable: false
    },
    popoverRef
  );
  return (
    <FocusScope restoreFocus>
      <div
        {...overlayProps}
        ref={popoverRef}
        className="absolute z-10 top-full w-full shadow-lg border border-gray-300 bg-white rounded-md mt-2"
      >
        {children}
        <DismissButton onDismiss={onClose} />
      </div>
    </FocusScope>
  );
}

```
</details>

<details>
<summary>HeadlessUI</summary>

```tsx
import React, { useState } from "react";

import { Listbox } from "@headlessui/react";

const animals = [
  { id: "red panda", name: "Red Panda" },
  { id: "cat", name: "Cat" },
  { id: "dog", name: "Dog" },
  { id: "aardvark", name: "Aardvark" },
  { id: "kangaroo", name: "Kangaroo" },
  { id: "snake", name: "Snake" }
];

export function HeadlessUi() {
  const [selectedAnimal, setSelectedAnimal] = useState<
    typeof animals[number] | null
  >(null);
  return (
    <Listbox value={selectedAnimal} onChange={setSelectedAnimal}>
      <Listbox.Label className="block text-sm font-medium text-gray-700">
        Favorite Animal
      </Listbox.Label>
      <div className="mt-1 relative">
        <Listbox.Button className="bg-white relative w-full border border-gray-300 rounded-md shadow-sm pl-3 pr-10 py-2 text-left cursor-default focus:outline-none focus:ring-1 focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm">
          {selectedAnimal?.name ?? "Choose…"}
        </Listbox.Button>
        <Listbox.Options className="absolute z-10 mt-1 w-full bg-white shadow-lg max-h-60 rounded-md py-1 text-base ring-1 ring-black ring-opacity-5 overflow-auto focus:outline-none sm:text-sm">
          {animals.map((animal) => (
            <Listbox.Option
              key={animal.id}
              value={animal}
              className={({ active }) =>
                `
                  cursor-default select-none relative py-2 pl-3 pr-9
                  ${active ? "text-white bg-indigo-600" : "text-gray-900"}
                `
              }
            >
              {({ selected, active }) => (
                <>
                  <span
                    className={`
                      block truncate
                      ${selected ? "font-semibold" : "font-normal"}
                    `}
                  >
                    {animal.name}
                  </span>
                </>
              )}
            </Listbox.Option>
          ))}
        </Listbox.Options>
      </div>
    </Listbox>
  );
}

```
</details> 

The HeadlessUI code is much easier to reason about because all of the glue code is handled under the covers by the library using context. Whereas the React ARIA code is full of hooks and refs and state that needs to be connected together just right to get things to work.

---

Edit: Unfortunately I wasn't super clear, but I'm advocating for both hooks **and** components APIs. Obviously the hooks are low-level and useful for edge cases. But I think adding components alongside them would be nicer to use for 90% of cases.

**Comment by devongovett** [comment]
Hey, thanks for the feedback! React Aria is certainly low level. Our goal when releasing it was that it could accommodate the widest possible number of use cases. This includes the ability to fully customize the appearance, DOM structure, behavior, etc. We aim to let you have just as much control as if you were building the component from scratch with the raw DOM APIs as you might have before, but also provide a lot of behavior and a11y for you. Our hope was that higher level libraries like Headless UI would be built on top of React Aria. It's only possible to do this one way: the lower level hooks have to come first.

We did look at component and render-props based APIs when designing React Aria. In fact, we started thinking about this problem long before Hooks even existed. However, we never found the right way to do this that offered enough customization potential. Our goal was to build something that we could build React Spectrum (our design system) off of, and I don't think we could have done that without lower level access in some areas.

A few considerations:

* The components are mainly designed to be used as part of a larger design system. Headless UI is definitely simpler to use when you only use one component, but you may find yourself duplicating some things in a larger project. For example, in the React Aria code you showed above, the ListBox and Popover components can be reused for other things, like standalone lists, and menus. This can be hard for us to show on the documentation site for components that compose several pieces together like this, because you need all pieces first before you can put them together. Perhaps there's more we can do to improve this.
* Custom styling often requires extra DOM elements, or access to internal state. For example, a Tabs component with an animating line to indicate the selection requires an extra element and access to the DOM nodes for each tab to measure their sizes. Or perhaps you want to enable virtual scrolling for long lists, but still enable keyboard navigation even when all of the elements aren't rendered. Coupling components to a pre-defined DOM structure and relying on context definitely has limitations.
* Another goal is to share as much as possible across platforms. For example, the [react-native-aria](https://github.com/GeekyAnts/react-native-aria) project is reusing our React Stately hooks to build equivalent versions for React Native. This type of sharing wouldn't have been possible with monolithic components.
* Customizing the behavior sometimes requires overriding properties returned by React Aria. For example, if you wanted to override some keyboard behavior for a specific case, you could override the `onKeyDown` prop returned from a hook and call it conditionally from within your own implementation. Doing this with a component API that renders the DOM elements for you would be tricky.
* There's a tradeoff between functionality and bundle size. Some components might have a lot of functionality that might not be useful across all products. For example, tables could have column resizing/reordering, drag and drop, multi-selection, etc. and not all of this may always be needed. We could include all of that in a single component with props to turn things on or off, but the tradeoff is that you're always paying the bundle size cost for code that's not actually used. Hooks provide a clean way to share small pieces of functionality that can be composed together within a single component, with the downside being, as you said, some glue code.

That being said, I do think there is a lot we can do to improve here without compromising on these goals. We've started at the lowest level layer possible, and are slowing working our way up the stack to provide higher level abstractions. Here are some ideas we have been thinking about:

* Combine some hooks that are very commonly used together. For example, buttons almost always need a focus style. We could combine the call to `useFocusRing` into `useButton` and return an `isFocusVisible` state so you don't need to do that yourself. `useOverlay` could have a focus scope built in for focus trapping. `useSelect` could potentially have `useButton` builtin, etc. The tradeoff is that if you're using the native `:focus-visible`, a different focus trapping library, or something else you get a bit of code you don't use, however, for some things this may be worth it. Figuring out where to draw that line is an interesting challenge.
* Expose more states from the hooks that could be used for styling. We've started doing this already – the `isSelected`/`isFocused`/etc. values returned from `useOption` were recently added. This avoids you needing to compute this yourself. We plan to continue adding more of these across the hooks.
* Reduce the amount of things you need to pass between hooks, e.g. between parents and children. We can often attach multiple things to the `state` object that you pass down rather than needing to pass a bunch of other options to child hooks.
* Create higher level hooks that combine more things together. This is related to the first one, but in some cases, rather than merging everything into one hook and causing larger bundles for everyone, we could keep the lower level hooks and also provide some higher level wrappers for common combinations.

Overall, the goal should be to reduce the number of different hooks you need to call for common cases, while retaining flexibility to drop down to lower level APIs where needed.

We don't currently have plans to offer an official component-based wrapper around our hooks, mainly for lack of time, but we would encourage and assist the community in such an effort. Personally, I would love to see multiple libraries with different takes on such an API built on top of React Aria, e.g. integrating with or optimizing for specific styling methodologies (e.g. tailwind, css-in-js, etc.). If you or anyone else is interested in working on such a library, we'd be happy to assist in any way we can. 😄

**Comment by ianstormtaylor** [comment]
Hey @devongovett, thanks for the thoughtful response!

I totally agree that hooks provide more control for certain edge cases where you need to get really custom (although some of those examples are solvable by components). I think hooks would still be key as the tiny building blocks, but an additional component-based layer would solve 90% of use cases without the current complexity.

It's hard to overstate how much simpler the Headless UI approach is. Even if this library is for UI kits, I'd be willing to bet that a lot of people come to it when first implementing a specific component that isn't well handled by browser defaults. (In my case this was trying to add an autocomplete component to a fairly simple UI kit.)

Totally makes sense if it's a lack of time concern though. Hopefully Headless UI adds more components over time and the mismatch in breadth will be reduced. I could definitely see a useful library that aimed to do what they're doing but with React ARIA under the hood—I'll hold out hope that it's React ARIA itself one day!

**Comment by sandren** [comment]
I think it's difficult to directly compare React Aria and Headless UI because to me it seems that they serve slightly different purposes (I personally use both). I would say that the purpose of React Aria—and @devongovett can correct me if I'm wrong—is to effectively create your own flavor of a Headless UI, either for your own internal design system or for an open source project built on top of it.

The components that you create with React Aria can have any API you want. So instead of building a one-off components with React Aria like in your example, you can create a general purpose one with a reusable API. That means you could technically take your Headless UI example and change the import from `import { Listbox } from "@headlessui/react"` to `import { Listbox } from "./listbox-built-with-react-aria"` and use them the exact same way, render props included if you are so inclined! 😀

So to me it's more about the level of control you have over the abstraction. Headless UI comes out of the box ready to go, but offers less customization. React Aria requires some assembly, but you can build any API you want.

**Comment by DaniGuardiola** [comment]
🙌  I'm glad this was raised, btw hi @ianstormtaylor, I'm currently building a text editor with Slate, great lib!

I've been thinking about this for a long time. In our org, we are using a combination of react-aria and Radix UI, and it's been on my mind to build a bunch of Radix-like primitives on top of react-aria / react-stately. I think that, while nothing beats hooks when it comes to extensibility, they have achieved a really good balance between having a high-level and easy to use abstraction, and making it extensible. I see two interesting patterns for this:

- Their recently simplified component extension API: `asChild` prop for slottable components.
- Optionally controlled state, making it possible to have uncontrolled components that still work correctly.

I bet it wouldn't be too hard to build primitives with a similar approach, on top of react-aria and react-stately.

One point where Radix and react-aria diverge is that Radix is designed around native HTML components like <button>, while react-aria sometimes wraps these elements with custom APIs like the press events API. In fact, this has been a little troublesome for us when combining Radix and react-aria. I guess it'd be a challenge to make something that works well for both react-aria based components and native HTML ones.

Anyway, that's just my two cents. If I had more time I'd definitely try to start a project like this! :)

**Comment by DaniGuardiola** [comment]
PD: this thread by @diegohaz (reakit creator) seems relevant too: https://twitter.com/diegohaz/status/1229499924062048260

Seems like Reakit is the most similar to what a react-aria based component library would look like. It has low-level hooks and high-level components, and you can use whatever you want depending on your needs. It basically bridges the gap between the two worlds, and it's similar to how I'd envision a react-aria based component library.

Relevant Reakit docs: https://reakit.io/docs/composition/#props-hooks

**Comment by ianstormtaylor** [comment]
@sandren thanks for the response. I totally get that, I definitely appreciate the flexibility of the hooks from React ARIA, and I'm very glad this library exists. I know you could theoretically build all of Headless UI on top of React ARIA—I'm definitely not arguing for eliminating them. 

My point is more that I'd bet the majority of users of this library don't require the granularity (and added complexity) that hooks provide. Just look at the difference in imports between the two examples:

```tsx
// Headless UI
import { Listbox } from "@headlessui/react";

// React ARIA
import {
  useSelect,
  HiddenSelect,
  mergeProps,
  useFocusRing,
  useButton,
  useListBox,
  useOption,
  useOverlay,
  DismissButton,
  FocusScope
} from "react-aria";
import type { AriaListBoxOptions } from "@react-aria/listbox";
import type { AriaSelectProps } from "@react-types/select";
import type { Node } from "@react-types/shared";
import { ListState, Item, useSelectState } from "react-stately";
```

With the current state of things... if it's ever possible for me to avoid React ARIA's APIs when adding a new component to my UI kit I will do that. And only when a nicer component-based package doesn't exist will I use React ARIA's hooks. 

So I opened this issue to bring this up, because I think the library would go from useful to amazing if it provided both hooks **and** components. (Imagine a `@react-components` or something to complement the existing packages.)

@DaniGuardiola thank you! That is awesome. Radix UI seems like exactly what I was looking for—similar to Headless UI but with a larger collection of components. The `asChild` pattern is very smart. And looks like it can replace the majority of my uses of React ARIA—the only big one that's missing for my use case is autocomplete/combobox.

**Comment by DaniGuardiola** [comment]
> looks like it can replace the majority of my uses of React ARIA

Yep, we're using Radix everywhere it fits for its simplicity, and Aria in places where we need more customization or for things that Radix hasn't covered yet, like the awesome press interactions. I think it's possible to have the best of both worlds, although it doesn't come without complications when you have to combine the two :laughing:

Hit me up when you try and fail to use a react-aria based button as a Radix trigger, I'll help and save you a world of pain :)

**Comment by devongovett** [comment]
Hey all, thanks for your comments, this is a good discussion. I agree that having both higher level components and lower level hooks would be great. All of the libraries mentioned are good, but I think they are optimized for different use cases. As far as I can tell, all of them could be built on top of React Aria internally if their authors desired.

Here are some tradeoffs with various component-based APIs:

* Headless UI is clearly optimized for usage with Tailwind (makes sense). The `className` prop allows passing a function which receives an object containing various states like `active`, `selected`, etc. This can be used to generate classes on demand based on state, which is required for usage with Tailwind since it doesn't rely on custom CSS selectors. However, using Headless UI with another styling framework might be challenging because it doesn't expose states when you aren't using class names.
* Radix and Reakit (and also Reach UI) are optimized for use with plain CSS or CSS-in-JS. For styling, they expose states as attributes (e.g. `data-state="active"` or `aria-selected="true"`) on their DOM elements, which can be styled using CSS selectors. This makes it difficult to use with something like Tailwind, where you aren't writing CSS selectors, and need to conditionally apply classes instead. Same would be true for some CSS-in-JS libraries that don't use CSS selectors. It's also challenging to use if the component doesn't expose whatever internal state you need as a data attribute.

These also tend to get complicated very quickly as soon as you want to do something even a little custom. Animated tabs is a good example. In order to do this, you need to take ownership of the state so you have access to the selection beyond just DOM attributes. Here's how Reach UI shows to do it: https://reach.tech/tabs/#animation. And here's an example using React Aria: https://codesandbox.io/s/practical-monad-punzo?file=/src/App.js. Because you already own the state, it's trivial to add a useEffect and an extra DOM element to render the selection.

I think it will be hard to design a single component-based API around React Aria that works for a wide number of use cases. That's why I hope the community will begin to explore different APIs for this that are optimized for specific use cases, e.g. `react-aria-tailwind`, `react-aria-styled-components`, etc. We would love to help wherever we can here! 😄

**Comment by devongovett** [comment]
I briefly prototyped an example of what this could look like using the Select component in your example above, but moving all of the styling to be passed in with an API similar to what Headless UI offers: https://codesandbox.io/s/intelligent-wright-7wi39?file=/src/App.js.

It uses functions passed to `className` for styling, which receive various states to apply conditional classes. It also uses render props to customize item elements and trigger contents. State is shared between all of the components via context, along with props returned from React Aria's `useSelect` hook.

This type of API does have a couple limitations though. Rather than passing `<Item>` elements as children, as React Aria currently expects, this type of API needs to allow passing any elements you want. Normally, React Aria uses the Item children to determine what items are in the collection. These are used to implement keyboard navigation, typeahead, etc. When there are arbitrary children, and the items could be at any nesting level, this is more challenging.

Headless UI and other libraries solve this using either a registration system using context, or by querying the DOM tree. Both of these require all of the items to be rendered to the DOM to work. You can't implement virtualized scrolling because keyboard navigation wouldn't be able to access items that are out of view and not rendered. That's why React Aria queries the JSX tree for Item elements instead, but it can't do this at arbitrary nesting.

For this demo, I instead relied on an `items` prop being an array of objects with a specific shape (`id` and `name` properties). This provides React Aria enough information to implement keyboard navigation, and we can pass those objects back to a render prop to render the actual `Option` elements. It's a little less ergonomic of an API than providing `<Item>` children, but it's the only other way to work with React Aria's existing hooks and support virtualized scrolling.

Anyway, hopefully this example shows that it's possible to build an API like Headless UI on top of React Aria, and what the implementation could look like. 🙂

**Comment by ianstormtaylor** [comment]
@devongovett thanks for the follow ups! 

Thing is though, those examples are sort of proving my point. The underlying logic in the `<Select>` example is very convoluted to follow. I can't imagine anyone (but a maintainer of React ARIA themself) writing that code without lots of time spent debugging things they hooked up incorrectly. And if you modified it to include TypeScript typings—like many would need—the confusion would increase another 2-3x.

It just reinforces my belief that React ARIA is great because it can do all these things, but I personally hope to touch it as little as possible, because its current abstractions just don't match what most people need. I'd feel irresponsible recommending people base a new UI Kit on it because of the complexity it would force on them, and instead I'd recommend it as a way to fill the gaps as a last resort.
