### ISSUE TITLE
ComboBox onLoadMore event fires on open

### ISSUE THREAD

**Issue by bhellema** [adobe/react-spectrum#2365]
# 🐛 Bug Report 
When using a ComboBox and useAsyncList together, the onLoadMore event will fire every time the user interacts with the ComboBox by opening it.  The result is that more and more data is fetched went the user has not scrolled to perform a load operation.  

## 🤔 Expected Behavior
No new data should be loaded when opening the ComboBox.

## 😯 Current Behavior
As you interact with the ComboBox the onLoadMore fires calling the useAsyncList's loadMore().

![loading-onloadmore](https://user-images.githubusercontent.com/6395150/134260798-810f7abd-671f-42a8-8805-a28870d9f339.gif)

## 💁 Possible Solution
N/A/

## 🔦 Context
We are trying to load users which can be an expensive operation depending on the number of users in the system.  Preventing additional calls is important.

## 💻 Code Sample
You can reproduce this behavior with the example storybook asynchronous loading https://react-spectrum.adobe.com/react-spectrum/ComboBox.html#asynchronous-loading

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |  3.12.0 |
| Browser          | Chrome |
| Operating System | mac |

## 🧢 Your Company/Team
AEM

**Comment by LFDanLu** [comment]
Some context/debugging on this issue:
Looks to have been introduced via https://github.com/adobe/react-spectrum/blob/11596864232ede67642f304e175a678eafcbb176/packages/%40react-aria/virtualizer/src/Virtualizer.tsx#L86-L92. When a Virtualizer initializes, the `state.contentSize.height` and the `state.virtualizer.visibleRect.height` are both 0 since  the layout calculations haven't happened yet, which satisfies the checks listed above and causes a loadMore to happen -> results in loadMore being called every time the ComboBox is opened (probably isn't limited to ComboBox only either).

Some initial ideas for fixing this would be to check for this exact case of the heights both being 0 (feels iffy unless we check that num items in the collection is > 0?) or to add some logic in the Virtualizer/virtualizer state/layout that checks if initial layout calculation have finished (perhaps a flag that gets set once buildCollection in the layout is ran once) and only call loadMore if initial layout is finished.
