### ISSUE TITLE
Implement TreeView component

### ISSUE THREAD

**Issue by devongovett** [adobe/react-spectrum#2396]
# 🙋 Feature Request

A `TreeView` allows users to navigate a hierarchical tree data structure, with expanding and collapsing items. It also allows multiple or single selection of items, focusable elements inside items, and other interactions.

![](https://spectrum.adobe.com/static/images1x/01_element_desktop@2x_5HI0ZMwireN9Qmw2MaoBvW_1616705293395.png)

## ARIA pattern

Since `TreeView` allows focusable elements inside items, it will implement the [`treegrid`](https://www.w3.org/TR/wai-aria-practices-1.2/#treegrid) ARIA pattern rather than the `tree` pattern. The `TreeView` Spectrum component supports only a single column, however, the React Aria hooks will not have this limitation.

Since `grid` and `treegrid` are so similar, the existing React Aria grid hooks should be extended with treegrid support. See the above pattern and [this example](https://www.w3.org/TR/wai-aria-practices-1.2/examples/treegrid/treegrid-1.html) for details.

- Update `useGridState` to handle expanding and collapsing
- Add a prop to `useGrid` that controls whether it is a treegrid. Basically changes the role. Cannot be changed after initial render (we should throw).
- In `useGridRow`, we need to add `aria-expanded` for parent rows, `aria-level`, `aria-setsize`, and `aria-posinset`.
- Add keyboard handling for left and right arrow keys to expand and collapse a row

## Spectrum

React Spectrum’s `TreeView` component should follow the existing collections API, which allows nested items in the dynamic case. Static collections with nested children will not be supported for the initial version.

The `Virtualizer` should be used to implement `TreeView` as with other collection components, and a new `TreeLayout` will be needed to handle the layout. It should produce a flattened list of items with indentation since the `treegrid` pattern does not use DOM hierarchy.

`TreeView` should use the `useGrid` and associated hooks, and use the option that specifies that it is a treegrid. It should use `useTreeState` and `TreeCollection` to store the state, which should be converted within the component to use `useGridState` similar to `ListView` and `CardView`.

### Example

```tsx
import {TreeView, Item} from '@react-spectrum/tree';

<TreeView items={items}>
  {item => 
    <Item childItems={item.children}>
      <FolderIcon />
      <Text>{item.name}</Text>
    </Item>
  }
</TreeView>
```

## API

```ts
interface TreeViewProps<T> extends CollectionBase<T>, MultipleSelection, Expandable {}
interface SpectrumTreeViewProps<T> extends TreeViewProps<T>, StyleProps, DOMProps {}
```

## Not for initial implementation
- No static API
- No Sections
- No drill-down (Spectrum design)
- No thumbnails (Spectrum design)
- No t-shirt sizes
- No drag and drop
- No tooltips or truncating (to come)
- No infinite scroll (different ticket)
- No async loading (different ticket)
- No additional keyboard shortcuts (Spectrum design)

**Comment by GrantRussell** [comment]
I'm not totally familiar with the proposed aria-pattern proposed above, but a nice-to-have feature would be to rescue focus from a tree node that has document focus but is then removed from the DOM.

Currently in React Spectrum v2 TreeView, the focus is lost when the focused element is removed.

**Comment by curran** [comment]
I'm interested in potentially working on this.

Here is the Spectrum design doc for tree view https://spectrum.adobe.com/page/tree-view/

**Comment by LFDanLu** [comment]
@curran Thank you for your interest! The team is currently revisiting this to make sure all the information is still pertinent and up to date, we hope to get back to you in a week or so. If you'd like, you could explore implementing Tree using React Aria Components (RAC) and its collections pattern in the meantime. We plan on converting our React Spectrum components to use this new collection pattern so we figure it would be easier to create TreeView for RAC rather than implementing it in React Spectrum first and converting it later. Since it is a RAC implementation, you don't need to match the visuals of the Spectrum Design doc. Instead, the `treegrid` ARIA [pattern](https://www.w3.org/WAI/ARIA/apg/patterns/treeview/) should be your guide for the DOM structure and navigation patterns. 

Keep in mind that due to ongoing team priorities we won't have much time to actively support a contribution of this scale, but we'd appreciate any findings and progress you make here!

**Comment by curran** [comment]
Awesome, thanks for the note! Indeed, an implementation in `react-aria` should come first, and honestly that's probably where my contribution would end, as I plan to develop custom UI components at that level and not adopt `react-spectrum` itself.

I'm was considering attempting a recursive form of the existing [useListBox](https://react-spectrum.adobe.com/react-aria/useListBox.html) pattern. I see there are some 2-level examples with a `Section` concept, but no 3-level examples. Will post here if I have any progress to show.

**Comment by donaldpipowitch** [comment]
Was looking for a react-aria based treeview solution as well. Found [this great very recent tutorial](https://www.joshuawootonn.com/react-treeview-component-part-3) (not related to react-aria) in case someone needs a custom solution in the meantime.

**Comment by rostero1** [comment]
I assume this ticket applies to RAC as well, right?

**Comment by curran** [comment]
I've been working on a tree component for navigating files.

![image](https://github.com/adobe/react-spectrum/assets/68416/5b5ed530-c769-4630-b662-3bbf441e6617)

One thing I would like to do is make it more accessible using `react-aria`, or ideally use an off-the-shelf tree component from RAC (`react-aria-components`) if it exists. In the mean time, I've got some good direction here for making it more accessible: [VZCode issue #176: Keyboard Navigation & Accessibility](https://github.com/vizhub-core/vzcode/issues/176). Looking forward to making it work!

**Comment by edoelas** [comment]
Is there any reason for not to use React Stately?

**Comment by curran** [comment]
>Is there any reason for not to use React Stately?

For what in particular? What would that look like? It may be a good fit, but I'm not very familiar with it. I'm open to using React Stately if the benefits are clear. What would be the benefits of using it?

**Comment by reidbarber** [comment]
@edoelas This page may be helpful: https://react-spectrum.adobe.com/architecture.html

**Comment by GermanJablo** [comment]
In case some research on treeView components helps, here's what I found:

![image](https://github.com/adobe/react-spectrum/assets/43938777/ccf018be-d67c-4ba5-b9c4-354401630d43)

The best options I found are [react-arborist](https://github.com/brimdata/react-arborist) and [react-complex-tree](https://github.com/lukasbach/react-complex-tree). As a third honorable mention, the latter's creator is working on his "spiritual successor", [headless-tree](https://github.com/lukasbach/headless-tree) (still in alpha, and the author doesn't seem to be able to spend much time on it). The website is not mentioned in the GitHub repository, so [here it is](https://headless-tree.lukasbach.com/).

The arborist API seems better to me at first glance, although `react-component-tree` and `headless-tree` have a much smaller bundle size.

The following libraries have open issues regarding the implementation of a TreeView component:
- [react-aria](https://github.com/adobe/react-spectrum/issues/2396)
- [Radix-UI](https://github.com/radix-ui/primitives/issues/1456)
- [AriaKit](https://github.com/ariakit/ariakit/issues/767)

**Comment by GermanJablo** [comment]
To discuss / receive feedback

# 1. Nested or flat DOM?

> It should produce a flattened list of items with indentation since the treegrid pattern does not use DOM hierarchy.

I have read [Aria's documentation on the treegrid pattern](https://www.w3.org/WAI/ARIA/apg/patterns/treegrid/), and I understand that it is possible to implement with a nested or flat DOM (they mention aria-owns), am I understanding correctly?

If so, I would like to receive feedback on some observations:

## 1.1 Drop-target.
While a `gridlist` can have a dropTarget only in "before" or "after" which is usually displayed with a thin line before or after, a `treegrid` can have a third state which is "inside". Although I have seen applications that display the "inside" state by only putting the drop target item in a different color, what offers a better UX is to color all the descendants of the item on which it is about to be dropped, just as programs like Notion or VS Code do.

![treegrid](https://github.com/adobe/react-spectrum/assets/43938777/463b9e64-30a2-4571-9e13-1ff4bf099f49)

This is possible to do with both a flat and a nested DOM. However, nesting may require accessing all descendants and adding some indicator to them in the markup.

## 1.2 Virtualization
If I'm not mistaken, it should be possible to virtualize both models, although it would surely be much easier with a flat model.

The creator of react-complex-tree is making the new headless-tree library as I mentioned in my comment above, precisely because [he found complications virtualizing a nested DOM](https://github.com/lukasbach/react-complex-tree/issues/263#issuecomment-1550477203).

# 2. Drop "inside"

[The useDragAndDrop event exposes `dropPosition`](https://react-spectrum.adobe.com/react-aria/GridList.html#dropping-between-items) which can be "before" or "after" as I mentioned above.
What would be better?
1. Add the third state "inside" that differs from "before" and "after" according to the number of pixels located on the edge of the element. Users could not change that number of pixels.
2. Do not expose "inside", "before" or "after", and let each user calculate it however they want.
I tried doing something like this with `useDrop` and it wasn't very difficult

```ts
  const [dropPosition, setDropPosition] = useState<
    "before" | "after" | "inside" | null
  >(null);
  const { dropProps, isDropTarget } = useDrop({
    ref: dropRef,
    onDropMove(ev) {
      if (!dropRef.current) return;
      const itemHeight = dropRef.current.offsetHeight;
      if (ev.y < 7) setDropPosition("before");
      else if (ev.y > itemHeight - 7) setDropPosition("after");
      else setDropPosition("inside");
    },
  });
```
3. Add the third state as in point 1 and also expose a property that allows defining the distance from which inside enters.

# 3. Expanding and collapsing API

Using item selection as a reference, an analogous API could be:
```ts
type CollectionProps = {
   defaultCollapsedKeys: 'all' | Iterable<Key>, // initial state
   collapsedKeys: 'all' | Iterable<Key>, // current state
   onCollapsedChange: (keys: Collapsed) => any, // setter
}
```
However, for the same reasons [I explained here](https://github.com/adobe/react-spectrum/discussions/5058#discussioncomment-8053130) I **strongly suggest** that the API be determined solely by a setter and a getter:
```ts
type CollectionProps = {
   getCollapsed: (item: object) => boolean, // getter
   setCollapsed: (item: object) => void, // setter
}
```

**Comment by 6thpath** [comment]
Hi, I have a question on node selection for this component, as `react-aria-components@1.2.0` released, i think when the parent node is selected then all children nodes should be selected too, is that right?
<img width="223" alt="Screenshot 2024-05-12 at 12 39 36" src="https://github.com/adobe/react-spectrum/assets/22215743/ac1bb99c-6307-46f3-b27e-0e02309cad1f">

**Comment by LFDanLu** [comment]
@6thpath At the moment that is intended behavior, similar to how macOS's file system allows you to select a parent folder individually from its children. I imagine we could consider adding support for customizing this behavior though.

**Comment by snowystinger** [comment]
Initial component is done
https://react-spectrum.adobe.com/react-aria/Tree.html#tree
https://react-spectrum.adobe.com/react-spectrum/TreeView.html#treeview

We'll track other work in other issues such as https://github.com/adobe/react-spectrum/issues/6589

**Comment by GermanJablo** [comment]
That's great @snowystinger!

I was going to open 4 threads with the observations or questions from my previous comment and gave up after making the [first one](https://github.com/adobe/react-spectrum/discussions/7266).

I just hope you take them into account. Thanks for the amazing work you do!
