### ISSUE TITLE
Would like Aria Hooks to utilize the useObjectRef Hook to avoid the extra friction of having to call it

### ISSUE THREAD

**Issue by solimant** [adobe/react-spectrum#2503]
# 🙋 Feature Request
This is a follow-up enhancement based on https://github.com/adobe/react-spectrum/pull/2293#issuecomment-944797775:
> ... ideally the next step would be to call this util from most of our hooks that accept refs, and add function refs to their type signatures. It should be safe because it's an additive change - object refs are already supported and we are adding function ref support. While people can use this util in their components themselves, it's a bit of extra friction we can hopefully avoid.

## 🤔 Expected Behavior
Aria Hooks work OOTB without necessarily having to make the additional imperative call to `useObjectRef` for forwarded `ref`s.

## 😯 Current Behavior
Using `useObjectRef` is necessary for forwarded `ref` to work with Aria Hooks.

## 💁 Possible Solution
N/A

## 🔦 Context
TypeScript custom components that support `ref` forwarding and that utilize [React Aria](https://react-spectrum.adobe.com/react-aria/index.html) Hooks. 

## 💻 Examples
The following should work without having to use `useObjectRef`:
```tsx
const TextField = React.forwardRef<HTMLInputElement, TextFieldProps>((props, forwardedRef) => {
  const {label} = props;
  const {labelProps, inputProps, ref} = useTextField(props, forwardedRef);

  return (
    <div style={{display: 'flex', flexDirection: 'column', width: 200}}>
      <label {...labelProps}>{label}</label>
      <input {...inputProps} ref={ref} />
    </div>
  );
});
```

## 🧢 Your Company/Team
Adobe/RSP

## 🎁 Tracking Ticket (optional)
N/A

**Comment by gmwill934** [comment]
Has this been released?

**Comment by LFDanLu** [comment]
No, this hasn't been picked up by the team yet. If you need this sooner rather than later, we'd be happy to accept contributions!

**Comment by gmwill934** [comment]
happy to, can you point the way?

**Comment by snowystinger** [comment]
Hey, so sorry for some confusion. We had meant to close this. There were some concerns with calling this in our hooks for several reasons.

How do we decide which hooks to call it in? The most obvious choice is every hook. However, our hooks frequently compose other hooks in our library, meaning we'd call this many times just for a single component.

It's better to call the hook only once. And the only way to do that is to call it at the component level. We're actually handling it in our new React Aria Components this way. https://react-spectrum.adobe.com/react-aria/react-aria-components.html 
https://github.com/adobe/react-spectrum/blob/main/packages/react-aria-components/src/utils.tsx#L134

This helper is also timing sensitive, it has to be before any layout effect that tries to use the ref, otherwise it may not have been updated in time. This is something that can only be done at the component level.

I think the best thing to do is document the hook `useObjectRef` to explain this.

I'm going to close this issue to avoid further confusion.
