### ISSUE TITLE
input props overrides props from ...register() in react-hook-forms

### ISSUE THREAD

**Issue by lveillard** [adobe/react-spectrum#2603]
Not sure if it's an issue because i don't know if there is a reason for useTextField's "inputs props" to override the value prop . But I spent hours trying to figure this out, so i think it may help others.

In case you're using both react-hook-forms and react aria , remember to use react aria first and then spread the register so it overrides whatever react aria is doing to the values:

```
const { inputProps, labelProps, errorMessageProps, descriptionProps } =
    useTextField({ label, ...props }, ref);

   <input
          type={type}
          {...inputProps} // must be used before ..register so register can override some stuff
          {...register("yourvar")}
          aria-invalid={error ? 'true' : 'false'}
/>
```

hope it elps somebody or there is way to avoid react aria overiding value props

Thanks!

**Comment by snowystinger** [comment]
This setup will likely break some accessibility.
Instead, you can use our `mergeProps` function if it's just event listeners like `onChange`, but there's a bit more to it than that, because there's also a ref and a name, and our hooks should be aware of those things too. see the return type for register here https://react-hook-form.com/api/useform/register and our hooks options as well as return types here https://react-spectrum.adobe.com/react-aria/useTextField.html#api
A better approach could be to create the input as a component with the aria hook. This would then be reusable across your site. When you use the component in your form, you'd then register using https://react-hook-form.com/api/usecontroller which is how React Hook Forms recommends integrating with other UI libraries or Design Systems
See https://github.com/adobe/react-spectrum/issues/1860#issuecomment-840125913 for more information on this kind of integration as well.

**Comment by LFDanLu** [comment]
Closing for now, feel free to reopen if there are any further issues.

**Comment by lveillard** [comment]
Thanks! Will definitively take a look at it!
