### ISSUE TITLE
`locale` is used in code but not imported

### ISSUE THREAD

**Issue by deadcoder0904** [adobe/react-spectrum#2780]
# 🙋 Documentation Request

On the [SSR page](https://react-spectrum.adobe.com/react-spectrum/ssr.html), `locale` is used in a code-block but isn't imported:

```ts
import {SSRProvider, Provider, defaultTheme} from '@adobe/react-spectrum';

<SSRProvider>
  <Provider theme={defaultTheme} locale={locale}>
    <App />
  </Provider>
</SSRProvider>
```

I tried importing `locale` from `@adobe/spectrum` but it doesn't exist so would love to know where to import it from otherwise removing it might be better as it throws an error in VSCode when used with TS.

**Comment by reidbarber** [comment]
You can specify a string as the locale here i.e. `"en-US"` for English (US) locale. I think the intent here was to show that you need so explicitly provide one if you're using SSR, since we can't automatically detect it from the browser if it's being rendered on the server.

We should definitely update this example to be more clear though, thanks for spotting this!
