### ISSUE TITLE
Tabs: tabindex not updated in DOM on state.setSelectedKey()

### ISSUE THREAD

**Issue by jpdevries** [adobe/react-spectrum#2807]
# 🐛 Bug Report 
_This is our first bug report._

When calling `state.setSelectedKey()` along with `useTabListState()` we've noticed that the `tabindex` properties of the related tab items are not updated as expected. It's as if those only get updated on the literal mouse or keyboard events.

## 🤔 Expected Behavior

Unless we are mistaken, `tabindex` props should update when the state is updated as a 'controlled component'.

## 😯 Current Behavior

`tabindex` props are not updated when the state is updated via `state.setSelectedKey()` of `useTabListState()`. 

## 💁 Possible Solution

In the interim, in 'userland' we've done something kind of hacky, trigger a `.click()` on the corresponding DOM element:

```js
  useNonInitialEffect(() => {
    if (state.selectedKey !== activeTab_)
      // state.setSelectedKey(activeTab_); // what we'd like to do
      
      // hm, why doesn't setSelectedKey update tabindex of tab items?
      tabListRef?.current.querySelector(`[data-key="${activeTab_}"]`).click();   }, [activeTab_]);
```

Presumably the cleanest fix 'under the hood' would be for the `useTab()` Hook to return the expected `tabindex` properties based on `state.selectedKey`.

## 🔦 Context

We're building a top `react-aria` in the form of a `useTabs()` hook and would like the component to be "controlled-friendly" meaning the active tab can be set via a prop.

## 💻 Code Sample

Please see this example:
https://codesandbox.io/s/tabs-with-changing-label-forked-nzcyj?file=/src/App.js

Use the dropdown to change tabs. Note that when you do, the tabindex props are not updated in the DOM.
![image](https://user-images.githubusercontent.com/592335/152607175-ba053eab-f1d5-477e-89cd-835805a1dbbf.png)

## 🌍 Your Environment

See codesandbox. 

## 🧢 Your Company/Team

Nike/Digital Accessibility Team.

**Comment by snowystinger** [comment]
Yep, I see that we're tracking the last focused, not necessarily the currently active. Tabs may not always follow "the selected one should be the focused one". For instance, https://react-spectrum.adobe.com/react-spectrum/Tabs.html#keyboard-activation

However, maybe we should make more of a distinction there. Maybe when not using keyboard-activation, the selected one should update the tabIndex.

**Comment by jpdevries** [comment]
Interesting. Thanks for the hyper-fast response @snowystinger! Is there another method we should, or should also, be calling? If not, is our `.click()` hacky our best bet for now? 
We'd be happy to help contribute a fix if needed. It's understandably tricky, with the controlled-but-not stuff.

**Comment by snowystinger** [comment]
Hey! No worries, we're actually in the middle of a team meeting right now, so your issue came in at a very opportune time. We talked about it a bit more. I think we'd like to go with, tabIndex should be set to the selected item when the collection doesn't have focus and the selected key prop changes.

This will affect all of our components that have selection, so we'll need to test it after the change pretty thoroughly, but I think it makes sense.

We currently determine the tabIndex here: https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/selection/src/useSelectableItem.ts#L128
But we'll likely need to make a change in https://github.com/adobe/react-spectrum/blob/main/packages/%40react-stately/selection/src/useMultipleSelectionState.ts#L43
This tracks if focus is in the selection as well, so maybe in a useEffect (so we can track the previous prop), if `isFocusedRef.current` is false, we `setFocusedKey` to the first `selectedKey`.

**Comment by jpdevries** [comment]
Sounds like a plan. Thanks for the update @snowystinger! We'll stay tuned, and can test nightlies.

**Comment by devongovett** [comment]
FYI, the fix was released in today's release: https://react-spectrum.adobe.com/releases/2022-03-07.html
