### ISSUE TITLE
useFocusRing - isFocusVisible is true on [ESC] key

### ISSUE THREAD

**Issue by kremda** [adobe/react-spectrum#2821]
# 🐛 Bug Report 

Elements using useFocusRing get focused on the [ESC] key.

## 🤔 Expected Behavior

Elements should be focused only on the [Tab] key.

## 😯 Current Behavior

The bug can be seen here:
https://react-spectrum.adobe.com/react-aria/useFocusRing.html
1) Click on the example's "Test" button
2) Press the [ESC] key
3) The button gets the focus ring

**Comment by snowystinger** [comment]
Hey! Thanks for the issue, I had the same thought the first I saw this as well. This is intentional though, and it's how native elements work too. I've included a fiddle that demonstrates this, click the button, then press ESC. You'll see the focus ring appear around the native button element.
https://jsfiddle.net/fkveL9n4/
