### ISSUE TITLE
Reseting state externally of RadioButton group removes keyboard control.

### ISSUE THREAD

**Issue by pontageorge** [adobe/react-spectrum#2886]
# 🐛 Bug Report 

https://codesandbox.io/s/aged-surf-235df0?file=/src/Main.jsx

The CodesandBox above has an implementation of the `RadioGroup` with an external `Reset` button that resets the value to a default value. This is a scenario when editing existing documents or cloning and want to reset the document to its default state.

The scenario is that you select a value other than the default value then hit the `Reset` button. You can't `TAB` back into the `RadioGroup` anymore. Which from what I can tell is caused by the fact that the `selectedValue` is not  equal to the `lastSelectedValue` as that one is not reset to the same value as the default value. And the `value` prop doesn't update the `lastSelectedValue`.

## 🤔 Expected Behavior

After I reset the form to the default value. I still should be able to TAB back into the RadioGroup and control the value with the arrow keys

## 😯 Current Behavior

RadioGroup is skipped from TAB control. Not being able to select a new value with keys.

## 💁 Possible Solution

I have done this

```
    useEffect(() => {
        state.setLastFocusedValue(selected);
    }, [selected]);

    state.setLastFocusedValue = () => {};
```
Which sets the lastFocusedValue manually. It is already added and commented out in the `RadioGroup.jsx` file.

## 💻 Code Sample

https://codesandbox.io/s/aged-surf-235df0?file=/src/Main.jsx

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by LFDanLu** [comment]
Had an initial solution [here](https://github.com/adobe/react-spectrum/blob/a9cb1e8a44c4ec42ec16b6dd3f4c4b26f55414de/packages/%40react-aria/radio/src/useRadio.ts#L65) but upon digging some more the fix may be a bit more complicated that than. With that fix applied, it is possible to have 2 different radios with `tabIndex=0`, one due to `lastFocusedValue` and the other due to being the `selectedValue`. Testing in the browser shows that tabbing into the radio group in a scenario like the above will result in focus landing on the selected radio which feel correct, but I'm still concerned about the break in the roving tab index pattern. 
Additional questions/musings:
- if there is a radio selected, should it always override the lastFocusedValue? Or is focus and selection not supposed to be tightly coupled?
- maybe we could do something similar to tabs where if focus isn't within the radio group and selection changes, we should update the lastFocusedValue to the new selected value? What if the value doesn't exist?

**Comment by snowystinger** [comment]
> What if the value doesn't exist?

I think there'd be bigger issues if they set the selected value to a non-existent value. I think this has some merit in an approach. But let's look at native radiogroups.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio
https://jsfiddle.net/eh5vj4p8/3/

test instructions for fiddle
hit the run button to start it over
within 5 seconds, get keyboard focus on the radio group, it should go automatically to the 2nd option if you tab into it
wait for the timeout, the value of the radio group will change to the 3rd option
press tab to go to the submit button
press shift+tab to go back to the radio group, it'll take you to option 3

so I think the selected radio should always override lastFocusedValue

**Comment by snowystinger** [comment]
I've updated my codesandbox with the latest release. This appears to be fixed https://codesandbox.io/p/sandbox/floral-tdd-u22mdb
