### ISSUE TITLE
DialogTriggers do not work with TooltipTriggers

### ISSUE THREAD

**Issue by dmskinner** [adobe/react-spectrum#3009]
# 🐛 Bug Report 

When trying to use a `DialogTrigger` and `TooltipTrigger`, the dialog does not open.

## 🤔 Expected Behavior

If I wrap an `ActionButton` with a `TooltipTrigger` and use it in a `DialogTrigger`, both the tooltip and dialog should work. This behavior worked before React Spectrum v3.9

## 😯 Current Behavior

Right now, only the tooltip shows. The dialog cannot be triggered. 

This [codesandbox](https://codesandbox.io/s/modern-fast-gsouxb?file=/src/App.js) shows how the behavior worked using v3.8 and if the react-spectrum version is adjusted to v3.9+, you can see the functionality breaks.

## 🔦 Context

Our UI is mostly buttons triggering dialogs. Most of our buttons are icon-only. As such, they require tooltips per [Spectrum guidelines](https://spectrum.adobe.com/page/action-button/#Use-tooltips). Since using a `DialogTrigger` with a `TooltipTrigger` does not work, we've had to hack around it by using `DialogContainers`.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.15
| Browser          | 
| Operating System |

## 🧢 Your Company/Team

Adobe Edge Certificate Service

**Comment by ktabors** [comment]
I updated the codesanbox https://codesandbox.io/s/sad-architecture-n1981y?file=/src/App.js to include the DialogContainer workaround. I found via nightly builds that this worked on 3.0.0-nightly.948 and broke with 3.0.0-nightly.953. Looking at the commits, it broke with the following commit, https://github.com/adobe/react-spectrum/commit/6e4d003efd536df25fd653ff366c94ef81ded88a.

**Comment by cedeber** [comment]
I have something similar, but I am building my own component with react-aria. So, when you have a popover (which use `useOverlayWithPosition` and then a tooltip which also use `useOverlayWithPosition` in order to place both components close to the same trigger (usually a button), if you don't set `isDismissable` to `false` for the `useOverlayWithPosition` of the tooltip, you will never be able to open the dialog in the same time that a tooltip is active.

First it will close the tooltip https://github.com/adobe/react-spectrum/blob/c38d48149ff355c0aaa8f4db5b0be7a8774b26e7/packages/%40react-aria/tooltip/src/useTooltipTrigger.ts#L106 but somehow stop the propagation of the event, and only then you can click again to open the popover.

I have the feeling that as the overlay - or the trigger state manager - tries to be smart and close only one element (dialog, popovers...) after another (which make sense), the tooltip is more or less considered as if it was another popover instead of just a tooltip.

Not sure it was very clear, but maybe that the issue in Spectrum is just about that? Again I don't use Spectrum, just sharing my findings if other people have the same issue ;-)

**Comment by marshallpete** [comment]
Any idea how close the PR posted by @jluyau is to being merged? Dealing with some work arounds and wondering if I should just hold off till this one gets merged.

**Comment by snowystinger** [comment]
It won't be in this release. The next one is roughly a month+ out.
