### ISSUE TITLE
Provider theme prop is shown as optional, but TypeError raised if omitted

### ISSUE THREAD

**Issue by apoco** [adobe/react-spectrum#3021]
# 🐛 Bug Report 

In my next.js where I'm adding in React Spectrum, I placed the `<Provider/>` in my `/pages/_app.tsx`:

```jsx
<SSRProvider>
  <Provider>
    {/* ... */}
  </Provider>
</SSRProvider>
```

## 🤔 Expected Behavior

Users should be prompted on what is 

## 😯 Current Behavior

When loading my app, I got this error.

```
TypeError: Cannot read properties of null (reading 'dark')
    at $a6e2b5f4621e4690$export$6343629ee1b29116 (webpack-internal:///./node_modules/@react-spectrum/provider/dist/main.js:67:15)
    at Object.$96cabdf5b0aed55b$var$Provider [as render] (webpack-internal:///./node_modules/@react-spectrum/provider/dist/main.js:98:27)
    at ReactDOMServerRenderer.render (<redacted>/node_modules/react-dom/cjs/react-dom-server.node.development.js:3872:44)
    at ReactDOMServerRenderer.read (<redacted>/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at Object.renderToString (<redacted>/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at Object.renderPage (<redacted>/node_modules/next/server/render.tsx:1226:37)
    at Object.defaultGetInitialProps (<redacted>/node_modules/next/server/render.tsx:711:43)
    at Function.getInitialProps (webpack-internal:///./node_modules/next/dist/pages/_document.js:142:20)
    at Object.loadGetInitialProps (<redacted>/node_modules/next/shared/lib/utils.ts:387:27)
    at renderDocument (<redacted>/node_modules/next/server/render.tsx:48:29)
```

It appears that supplying a theme is _required_, but the types for `<Provider/>` indicate `theme` is optional.

## 💁 Possible Solution

Perhaps `theme` is required only in the case of SSR? Might I suggest a single provider that combines `<SSRProvider/>` and `<Provider/>`? If a customer used this, then you'd know it was for SSR, and then you could make the `theme` prop _required_. Alternately, maybe the `theme` prop could be omitted as the types suggest and it automatically uses `defaultTheme`. 

## 🔦 Context

I'm able to work around by explicitly passing the default theme; I'm just suggesting the improvement so new users that might not figure out the problem don't hit this snag.

## 💻 Code Sample

```typescript
// /pages/_app.tsx

import {
  Provider as SpectrumProvider,
  SSRProvider
} from "@adobe/react-spectrum";
import { type AppProps } from "next/app";

export default function MyApp({ Component, pageProps }: AppProps) {
  return (
    <SSRProvider>
      <SpectrumProvider>
        <div>My content</div>
      </SpectrumProvider>
    </SSRProvider>
  );
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.16.5
| Browser          | N/A
| Operating System | Linux

## 🧢 Your Company/Team

https://ifareahumanitariancenter.org/

**Comment by LFDanLu** [comment]
Thanks for filing this issue. From what I can tell `theme` is _supposed_ to be a required prop for Provider in general, I don't think this is SSR specific.

**Comment by LFDanLu** [comment]
@snowystinger reminded me of the nested Provider case where `theme` for the nested Provider should indeed be optional since it will fallback to the parent Provider's theme if none is provided. 

We should probably throw an error ourselves if [this](https://github.com/adobe/react-spectrum/blob/ad9fc6c065d86de63517874c08d3ddf96f9cfed3/packages/%40react-spectrum/provider/src/Provider.tsx#L43) `theme` is found to be undefined. Additionally, we should update the [type description](https://github.com/adobe/react-spectrum/blob/ad9fc6c065d86de63517874c08d3ddf96f9cfed3/packages/%40react-types/provider/src/index.d.ts#L62-L65) of `theme` to indicate that the parent provider **must** have a theme provided

**Comment by pkerschbaum** [comment]
Am I right that there is nothing left to do here?

#3322 is already merged, it added a runtime validation that `theme` must be set. And in the `ProviderProps` type, `theme` should remain optional because of the "nested Provider" case @LFDanLu mentioned above.

(would like to contribute, that's why I am asking)

**Comment by devongovett** [comment]
I believe so.
