### ISSUE TITLE
add prop pass through option to react-aria hooks (don't strip non HTML props)

### ISSUE THREAD

**Issue by hainessss** [adobe/react-spectrum#3037]
# 🙋 Feature Request

Stripping props passed to react-aria hooks breaks compositional components.

## 😯 Current Behavior

For example, 

```
import {useButton} from '@react-aria/button'

const CustomButton = styled('button', {
  ...someStylesHere
})

export function Button({ ...props }) {
  const ref = useRef()
  let buttonProps = useButton(props, ref);

  return (
    <CustomButton
      ref={ref}
      {...buttonProps}
    >
      {props.children}
    </CustomButton>
  );
}

export function App = () => {
  return (
     <CustomButton
        css={{ ...contextSpecificStylesHere }}
      >
        My Button
    </CustomButton>
  );
}
```

In this example the css and any other custom props are lost.

## 🤔 Expected Behavior

There should be an option to allow the props through.

For example,

```
useButton(props, ref, {
  filterDOMprops: false
});
```

**Comment by devongovett** [comment]
It's not so much that we filter them, it's just that we don't do anything at all with props that aren't defined by us. We return DOM props based on the props in our API. It's your job to add any additional props you want passed through. You could use the `mergeProps` utility for that.

```js
import {mergeProps} from '@react-aria/utils';

export function Button({ ...props }) {
  const ref = useRef()
  let buttonProps = useButton(props, ref);
  let domProps = {
    className: props.className,
    style: props.style,
    // ...
  };

  return (
    <CustomButton
      ref={ref}
      {...mergeProps(buttonProps, domProps)}
    >
      {props.children}
    </CustomButton>
  );
}
```

Or you could write a small utility to filter DOM props (or use a library from npm that does that), and merge them with the returned buttonProps.

```js
import {mergeProps} from '@react-aria/utils';
import filterInvalidDOMProps from "filter-invalid-dom-props";

export function Button({ ...props }) {
  const ref = useRef()
  let buttonProps = useButton(props, ref);

  return (
    <CustomButton
      ref={ref}
      {...mergeProps(buttonProps, filterInvalidDOMProps(props))}
    >
      {props.children}
    </CustomButton>
  );
}
```

**Comment by cornedor** [comment]
Props like `enterKeyHint` are also filtered out. Can I make pull-requests where they are added? Or should those be passed trough manually as well?

**Comment by hainessss** [comment]
> 

Thanks @devongovett. I can try that. It just seems like you might as well do the prop merge in useButton itself?  Otherwise a.) if you have a lot of props, this can quickly become untenable. For example, components that use a style prop pattern (one prop for each css property).  and b.) you need to know exactly what props useButton is returning so you don't accidentally overwrite them.

**Comment by devongovett** [comment]
The reason we don't is because different component libraries may choose to pass through different DOM props. For example, in React Spectrum, we don't allow passing through className because we want to enforce UI consistency. So I think it's better if other component libraries have control over what props are allowed on their components. I think it's fairly simple to write a small utility function in your library to do that.

>  if you have a lot of props, this can quickly become untenable. For example, components that use a style prop pattern (one prop for each css property)

I think my second example covers this. Rather than list them all explicitly, use a util function.

> you need to know exactly what props useButton is returning so you don't accidentally overwrite them.

`mergeProps` merges, rather than overrides in most cases. For example, event handlers are chained so both functions apply, class names are combined, etc. Otherwise, they are ordered, so if you put React Aria's props last they will win.

**Comment by devongovett** [comment]
> Props like enterKeyHint are also filtered out.

We do add some props on a per-component basis. In this case, `enterKeyHint` applies specifically to text inputs, so it should be supported there and not on every single component. That could be added [here]https://github.com/adobe/react-spectrum/blob/main/packages/%40react-types/shared/src/dom.d.ts#L122) and [here](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/textfield/src/useTextField.ts#L131-L166). Please feel free to submit a PR.

What we don't want to add is every possible HTML attribute for every possible element, since there are a lot, and we might not want to allow overriding certain ones depending on the component.

**Comment by hainessss** [comment]
ah I see, mergeProps has more functionality than I thought. thanks @devongovett

**Comment by hainessss** [comment]
okay, I don't think I am understanding.

This button:
```
export function Button({ as, ...props }: any) {
  const ref = React.useRef();

  let { buttonProps } = useButton({
    ...props,
    elementType: as
  }, ref);

  return (
    <StyledButton
      ref={ref}
      as={as}
      {...mergeProps(buttonProps, props)}
    >
      {props.children}
    </StyledButton>
  );
}
```

when used like this:
```
<Button as='span' onClick={() => { alert('hey') } > Click Me</Button>
```

When clicked, the alert is called twice.  
And when focused, the spacebar doesn't elicit a click.

Would expect, alert to be called once on click and onClick to be called when the spacebar is clicked despite it being a span right?

What am I doing wrong? And using filterInvalidDOMProps on my props doesn't make sense because then I lose all the custom props I want to pass-through.

**Comment by snowystinger** [comment]
if i had to guess, you're also getting a deprecation warning for onClick

use onPress instead https://react-spectrum.adobe.com/react-aria/useButton.html

see https://react-spectrum.adobe.com/react-aria/usePress.html for more information, as well as https://react-spectrum.adobe.com/blog/building-a-button-part-1.html

**Comment by hainessss** [comment]
Okay thanks @snowystinger 

```
export function Button({ as, onClick, ...props }: any) {
  const ref = React.useRef();

  let { buttonProps } = useButton({
    onPress: onClick,
    ...props,
    elementType: as
  }, ref);

  return (
    <StyledButton
      ref={ref}
      as={as}
      {...mergeProps(buttonProps, props)}
    >
      {props.children}
    </StyledButton>
  );
}
```

this works as expected.

I still think merging props and doing the conversion from onClick to onPress inside useButton would be a better developer experience. You could also create the ref inside useButton and fork it with the one passed in from props so you wouldn't need that second argument.

**Comment by devongovett** [comment]
`onClick` and `onPress` are different things, and I don't think we should override `onClick`'s default browser behavior. If you want to use `onClick`, you can pass it to the element itself. Otherwise, we recommend using `onPress` which provides a bunch of cross browser/device normalization. See the blog post linked previously for details.

As mentioned previously, we won't be passing through all DOM props because different component libraries have different requirements about which props are allowed so we'd rather leave that to them. Going to close this. Let us know if you have any more questions.
