### ISSUE TITLE
useNumberFieldState with formatOptions may cause crash with infinite-loop error

### ISSUE THREAD

**Issue by MrKou47** [adobe/react-spectrum#3200]
# 🐛 Bug Report 

I'm trying to build a NumberInput Component with `useNumberFieldState` and `useNumberFieldProps`. As default I want to disable grouping number so I add `formatOptions: { useGroupping: false }` as argument for those two hooks. And then it cause crash with infinite-loop error.

## 🤔 Expected Behavior

It should work without crash.

## 😯 Current Behavior

It make app crash with infinite-loop.

![image](https://user-images.githubusercontent.com/13513747/172542428-719e6eb0-e8e7-4b5b-b82d-e3f1a557119c.png)

## 💻 Code Sample

Reproduce: https://codesandbox.io/s/react-aria-numberfield-crash-0bhll4

As you can see if you remove `formatOptions` it will works as usual.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-aria   | latest
| react-stately   | latest
| Browser          | Chrome latest
| Operating System | Mac 12.4

**Comment by snowystinger** [comment]
It appears to happen with any formatOptions you provide at the hook level because it's creating a new object each time, if you memo the formatOptions or pass it in on props, you don't have this problem.
https://codesandbox.io/s/react-aria-numberfield-crash-forked-ty3iv1?file=/src/NumberField.tsx:610-638

Btw, you'll want the group element with its props if you want the scroll wheel to work, though maybe we should be attaching those focus events to the input. I'll have a think on that.

**Comment by MrKou47** [comment]
Thanks!
