### ISSUE TITLE
FocusScope feature request: focus the next row, skipping over tabbable columns

### ISSUE THREAD

**Issue by raymondwang** [adobe/react-spectrum#3226]
# 🙋 Feature Request

Given a grid of elements, I'd like to be able to configure up and down arrow keypress event handlers that skip between rows. For example:

```
[element a] | element b | element c
 element d  | element e | element f
```

If `element a` is currently focused, pressing the down arrow key should focus `element d`, skipping elements `b` and `c`. 

## 🤔 Expected Behavior

An option in the `FocusManager` API that lets us configure this somehow.

## 😯 Current Behavior

As far as I can tell, no such functionality exists — a workaround for the above table currently looks like:

```ts
const numColumns = new Array(3).fill(0);
numColumns.forEach(() => focusManager.focusNext());
```

## 💁 Possible Solution

I _think_ the easiest solution would be to add support for a new numeric `skip` option directly in the `focusNext` and `focusPrevious` API. I can contribute the change if this isn't too controversial.

There might be something clever that can be done with `NodeFilter` and indices, but not that I'm aware of right now.

## 🔦 Context / 💻 Examples

This has come up in a few places, but here's an example of a grid I'm working with, where I'd like to configure sensible arrow keybindings:

https://user-images.githubusercontent.com/4248263/173683815-dbe92593-c299-49bc-aa03-e3c3a6046c36.mov

Ideally, right and left arrow keys would navigate to the next column over (i.e. the default behavior for `focusNext` / `focusPrevious`), while I'd like for down and up arrow keys to jump to the next row. The aforementioned workaround would work here, but a native solution would be even better!

## 🧢 Your Company/Team

Atlassian/Trello

**Comment by snowystinger** [comment]
What determines this grid's layout? if I expand the area, then the down arrow would need to point to a different element. Would you expect to put in a resize observer that checks how many columns are there and changes that skip number?

If it's modelled after any of our work, we actually put together specific logic for navigating views like this by tracking keys instead of querying the dom. https://github.com/adobe/react-spectrum/blob/main/packages/%40react-spectrum/card/src/BaseLayout.tsx#L143

Otherwise, I think the workaround you have is fine for now. I seem to remember someone else doing it a while back, though I've been unable to find the conversation. I think we could consider adding something like this. I do wonder if a skip count is the best way to accomplish it though given that the items may reflow.

I think a better way to do it would be to make use of the `accept` option we pass to createFocusManager's functions. You could do something like this:
https://codesandbox.io/s/practical-banach-mhov26?file=/src/App.js

https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/focus/src/FocusScope.tsx#L148 should match
https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/focus/src/FocusScope.tsx#L513

**Comment by devongovett** [comment]
I was writing a reply but Rob beat me to it. You could use `accept` to implement this perhaps. I think you could probably just count the number of times it is called though.

```tsx
let i = 0;
focusManager.focusNext({
  accept: element => ++i === 3
});
```

Thoughts?

**Comment by raymondwang** [comment]
Thanks for the feedback @snowystinger & @devongovett! The `accept` workaround seems sensible and I probably prefer it to my hack (as it results in only one focus invocation). The thing that immediately jumps to mind in terms of functionality difference is reconciliation for non-wrapping edges: when pressing down on the first element of the last row, my hack would focus the last element in the row, while the `accept` implementation would no-op. That said, I don't actually have a gut-level preference for which behavior feels more "correct" — not sure if there are any established a11y guidelines for this kind of thing — and it should be pretty easy to configure that behavior with a check that called `focusLast`, anyway.

Reflow is an excellent callout. I don't have a great solution for it — I actually kind of love the `getBoundingClientRect` hack, but it obviously has some risk factors itself. I'm working with hardcoded grid constraints at the moment, so I haven't had to think about it too much. I'd be interested in exploring whether there's a way to rig together a `skip`-type parameter that can take reflow into account, i.e. doesn't require an explicit number of columns to be passed in.

I'll change my implementation to leverage `accept` for now, but I'm still open to kicking around ideas on a built-in solution if there's appetite.

**Comment by raymondwang** [comment]
Hey @snowystinger & @devongovett, I've been kicking around the solutions discussed here on a nightly build, but have found something interesting: `focusNext` with Devon's count implementation works perfectly, but it doesn't work as expected with `focusPrevious`. Here's a sandbox: https://codesandbox.io/s/billowing-cookies-hp5knh

You can see that pressing the down arrow key correctly goes to the next row, but pressing the up arrow key skips one fewer element. Adding a console.log there for the element being evaluated shows that we run `accept` on each node twice, for some reason, instead of once.

**Comment by snowystinger** [comment]
I looked into it today, it actually appears to be a bit of a problem/quirk with the browser implementation, previousNode will call filter twice when the node in question has child nodes
You can see in this example https://codesandbox.io/s/elegant-vaughan-wqw2pb?file=/src/App.js that is not React Spectrum/Aria, all the elements that have a string in them have accept called twice. While the empty ones only call accept once.

This is present in every browser and in jest dom.
jest-dom https://github.com/jsdom/jsdom/blob/master/lib/jsdom/living/traversal/TreeWalker-impl.js#L74
chromium https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/dom/tree_walker.cc;l=196

I'll check with the team tomorrow to see if this is a behavior we'd like to change. My personal stance is that it is the same everywhere, we shouldn't change it, but we'll see how others feel.

**Comment by snowystinger** [comment]
I chatted with the team. The behavior is not something we want to change because it's been like this in browsers for a long time, and it'd be tricky to change. I suggest not relying on the number of times 'accept' is called and instead using the solution I originally proposed using the bounding box; this will be more resilient to implementation changes and screen size differences.
