### ISSUE TITLE
Improve return types in FocusManager methods `focusNext()`/`focusPrevious()`

### ISSUE THREAD

**Issue by kirill-galimov-plutotv** [adobe/react-spectrum#3324]
# 🙋 Feature Request
Currently FocusManager methods `focusNext()`/`focusPrevious()` have `HTMLElement` return type. Since they use [TreeWalker.nextNode()](https://developer.mozilla.org/en-US/docs/Web/API/TreeWalker/nextNode) which may return `null`, it would be great to reflect the return type of these methods more accurately.

## 🤔 Expected Behavior
```typescript
// nextElement: HTMLElement | null
const nextElement = focusManager.focusNext();
```
## 😯 Current Behavior
```typescript
// nextElement: HTMLElement
const nextElement = focusManager.focusNext();
```

**Comment by blordpluto** [comment]
@snowystinger Thanks but AFAICT "strict" has nothing to do with the assertions at issue here. Strict is just a group of what they call ["strict mode family options"](https://www.typescriptlang.org/tsconfig#strict). None of the those options relate to the use of assertions. In other words, you can be strict and dubious assertions are still allowed.

I'm talking about assertions like like:
https://github.com/adobe/react-spectrum/blob/263db83002000d6deed33b6eb1341e76f6609f42/packages/%40react-aria/focus/src/FocusScope.tsx#L155

This feels like a good example of assertion creating some confusion where just letting the inference do its thing would be both simpler and more accurate.

Would you be open to a PR on this?

**Comment by devongovett** [comment]
The types for TreeWalker return `Node | null`, so I don't think there's a way to avoid the `as` here, short of an `instanceof` check every time. In this case, we know it is an element based on the filters we passed to `createTreeWalker`, so asserting so is safe. If anything, it would be the types of TreeWalker in TypeScript that could potentially be improved.

**Comment by blordpluto** [comment]
> In this case, we know it is an element based on the filters we passed to `createTreeWalker`, so asserting so is safe.

The third argument filter there doesn't guarantee that there's going to be a be a nextNode. It just imposes conditions on what an acceptable `nextNode` can be. It can still return `null`.

If `nextNode()` always returned an Element, then a `while` loop like the example here at https://developer.mozilla.org/en-US/docs/Web/API/Document/createNodeIterator#examples
would never break. It would be an infinite loop:

```javascript
const nodeIterator = document.createNodeIterator(
    document.body,
    NodeFilter.SHOW_ELEMENT,
    {
      acceptNode(node) {
        return node.nodeName.toLowerCase() === 'p' ? NodeFilter.FILTER_ACCEPT : NodeFilter.FILTER_REJECT;
      }
    }
);
const pars = [];
let currentNode;

while (currentNode = nodeIterator.nextNode()) {
  pars.push(currentNode);
}
```

And in the existing code, it makes no logical sense to assert that `nextNode` is an Element and then immediately check for it:

https://github.com/adobe/react-spectrum/blob/263db83002000d6deed33b6eb1341e76f6609f42/packages/%40react-aria/focus/src/FocusScope.tsx#L536-L543

If the assertion on line 536 is true, then the condition on line 541 is redundant and has no point. The "code" works but the assertion creates problems here for TS that is consuming the return value.

> If anything, it would be the types of TreeWalker in TypeScript that could potentially be improved.

Well, no, the TS typings are exactly correct per the [spec](https://www.w3.org/2003/01/dom2-javadoc/org/w3c/dom/traversal/TreeWalker.html#nextNode__).

**Comment by snowystinger** [comment]
Yes we'd be open a PR, we can debate more on that PR as well.

Sorry for the confusion with ts strict, I saw an `| null` and that's been the majority of our reported ts strict bugs. Thank you for clarifying.

**Comment by devongovett** [comment]
> The third argument filter there doesn't guarantee that there's going to be a be a nextNode. It just imposes conditions on what an acceptable nextNode can be. It can still return null.

You were arguing that this had nothing to do with strict null checks, but now you are saying the opposite. So Rob's initial assessment was correct. This is because we do not currently use strict mode, and therefore the `| null` is implicit in the type. The assertion to Element vs Node is still necessary.

> Well, no, the TS typings are exactly correct per the [spec](https://www.w3.org/2003/01/dom2-javadoc/org/w3c/dom/traversal/TreeWalker.html#nextNode__).

Yes but you were saying that the assertion could be removed and we could rely on inference, but that is incorrect. We have to assert that it's an element and not just a node, because Node doesn't have a `focus()` method. If you remove the assertion you can see the error.

Again, all of this is because we do not currently use strict mode in our typescript configuration, and therefore every type includes an implicit `| null`. Writing it explicitly is not necessary. Once we move to strict mode, it will be, but not today.

**Comment by blordpluto** [comment]
Got it, thanks. I've actually never worked on a project that didn't have "strict" enabled. 😄 Since so many DOM APIs return `null`, it seems like this is something pretty crucial for a DOM-oriented library. As it is, we're going to have to assert on the return of these functions in every usage 😦 .

One more thing while I'm here: I'm not convinced that `FocusableElement` would even be the right assertion here. For example if there is a tabindex on an SVG element, then it's focusable, but it's not an HTMLElement, etc.

Thanks again.

**Comment by devongovett** [comment]
I think it's right - SVG elements are also focusable, so they should work with a focus scope just fine. I don't think there's a reason it would need to be an HTMLElement specifically?
