### ISSUE TITLE
Unusual spacing in DateRangePicker

### ISSUE THREAD

**Issue by minaseem** [adobe/react-spectrum#3355]
# 🐛 Bug Report 
There is unusual space in DateRangePicker field

![image](https://user-images.githubusercontent.com/5484032/181482436-c136299c-1b5d-4b2d-b658-5ef4bb8c9cad.png)

Space between points A and B, C and D is not proper. It seems that it is more than it should be which makes it looks little off.

## 🤔 Expected Behavior
Space between points A and B, C and D should be lesser.

## 😯 Current Behavior
Space between points A and B, C and D is more than it should ideally be.

## 🔦 Context

We have received this as feedback multiple times. People have raised concerns regarding the above-specified spacing.

## 💻 Code Sample

The issue can be reproduced within RS doc. [Link](https://react-spectrum.adobe.com/react-spectrum/DateRangePicker.html)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3
| Browser          |
| Operating System |

## 🧢 Your Company/Team
Adobe / AJO

**Comment by LFDanLu** [comment]
The spacing is there to accommodate for the wider placeholder text that appears if you delete those values:
<img width="320" alt="image" src="https://user-images.githubusercontent.com/9661127/181600096-6bb7b18b-887f-41f5-af85-7a12f218f3f2.png">
This was the best compromise we could come up with that allowed the placeholders to be readable/convey the proper date format, allowed for large enough date segment hit targets for mobile, and prevented layout shifting as the user inputs a value (aka if we had dynamic spacing instead of the static date segment widths)

**Comment by LFDanLu** [comment]
Note: the prefixed 0 is automatically included for some regions/locales (e.g. fr-FR), so this seems to be a regional preference. As such, we prefer that the prefixed "0" formatting is automatically handled (aka the current behavior)

**Comment by vladdoletskiy** [comment]
![Screenshot_39](https://user-images.githubusercontent.com/62791013/183506215-7ad90df1-0bff-42e0-95f3-95488f98dac5.png)
how about this space?

**Comment by devongovett** [comment]
As shown above, it's to accommodate the placeholder and avoid a layout shift when a value is entered or deleted.

<img width="245" alt="image" src="https://user-images.githubusercontent.com/19409/183507623-cef0bda4-a25c-4745-90b4-376db3942590.png">

**Comment by LFDanLu** [comment]
@vladdoletskiy just to make sure, which specific associated locale are you seeing this? For French (Canada), that spacing is required due to the amount of room the placeholder text takes:
<img width="239" alt="image" src="https://user-images.githubusercontent.com/9661127/183507594-8b44f709-434b-4429-989a-5171411b9911.png">
vs
<img width="235" alt="image" src="https://user-images.githubusercontent.com/9661127/183507631-5ef68f94-0253-4b8c-be62-63c7cafb32a0.png">

**Comment by vladdoletskiy** [comment]
it's ugly. My designers don't want to use it because of this. Although DatePicker good. Tell me if it's possible to use only "/" instead of '-'

**Comment by devongovett** [comment]
The formatting depends on the locale. If the country/region/language uses `/` then that will be used, otherwise a different separator might be used.

This is a case where there is no perfect design. Previously, we had a numeric placeholder (example date), but people complained that they couldn't tell it was a placeholder and not filled in. So, we replaced with a text-based placeholder. But that means that the placeholder is a different width from a value. We thought it was weird to have things shifting around while entering a value (in fact, the whole component changes width), so reserved space for the placeholder at all times to avoid it.

Here's an example:

https://user-images.githubusercontent.com/19409/183513294-91ea8730-2298-4ac2-a7f6-6d23838c5413.mov
