### ISSUE TITLE
FocusScope Contain scroll focus element into view.

### ISSUE THREAD

**Issue by Viraj-10** [adobe/react-spectrum#3371]
# 🐛 Bug Report 

1. go to codesandBox [link](https://codesandbox.io/s/focusscope-contain-issue-with-scroll-x0gtfi?file=/src/App.js)
2. Click on the open `button`.
3. click on a first or second input.
4. scroll down and select a text or click anywhere in the container.
5. it gets to scroll up to the first input.

## 🤔 Expected Behavior
There should be some way to stop this.

**Comment by LFDanLu** [comment]
You can fix the above by providing `tabIndex={-1}` to the FocusScope's child div: https://codesandbox.io/s/focusscope-contain-issue-with-scroll-forked-lres2q. The reason it scrolls up to the first input is because a `contain` FocusScope attempts to enforce that a focusable element within the scope is always focused

**Comment by Viraj-10** [comment]
Hi @LFDanLu, Thanks. making it `tabIndex={-1}` solved my problem.
