### ISSUE TITLE
Unexpected useFocusRing behavior

### ISSUE THREAD

**Issue by tanishqkancharla** [adobe/react-spectrum#3410]
# 🐛 Bug Report 

`useFocusRing` seems to say a focus ring is required even if it isn’t in some cases.

## 🤔 Expected Behavior

I expect 

1. when hovering over the listbox initially, that useFocusRing returns false
2. If I start using the keyboard, that useFocusRing returns true,
3. If I go back to using the mouse, that useFocusRing return false

## 😯 Current Behavior

`useFocusRing` returns true in all 3 instances.

https://codesandbox.io/s/youthful-sanderson-f5wjkh?file=/src/Listbox.tsx

Notice that once the sandbox loads, and you initially hover over the listbox, the selection option has a focus ring. If you click outside the listbox, and hover back, the options no longer have the focus ring. Once you start using the keyboard, the focus ring appears again. However, if you go back to using the mouse, the ring remains visible (but it shouldn’t, because I’m not longer using the keyboard to navigate).

## 🔦 Context

I’m just trying to emulate Linear’s behavior, which is under the expected behavior

## 💻 Code Sample

https://codesandbox.io/s/youthful-sanderson-f5wjkh?file=/src/Listbox.tsx

## 🌍 Your Environment

Codesandbox, safari and chrome.

| Software         | Version(s) |
| ---------------- | ————— |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by snowystinger** [comment]
Hey, could you verify this against https://react-spectrum.adobe.com/react-aria/useListBox.html#example ? I think it's working how you expect.

**Comment by tanishqkancharla** [comment]
Sorry I should have specified; as in the codesandbox, I set `shouldFocusOnHover` on `useListBox`

**Comment by snowystinger** [comment]
Ah, then this is behaving as expected. When you first load the page, we don't know what interaction mode you're in, so we assume keyboard. As you hover each item, it gets focused. Because we think you're in keyboard mode, it returns true. Then you use the keyboard, so it stays in keyboard mode, but now we have an interaction mode we know about. Finally, you start moving the mouse again. This doesn't count as an interaction mode change. Only clicking or taking an action with the mouse will change the interaction mode.

You can see what I mean by loading your example, click somewhere on the page, then hover the items. It shouldn't return true anymore.

We did want to move a use to mouse interaction just because they move the mouse since it's easy to bump a mouse and the focus ring shouldn't disappear because of that.

**Comment by tanishqkancharla** [comment]
Ah, I see, that makes sense! Do you know of any way to achieve what I’m trying to do? We don’t have to change the interaction mode immediately on move; only once the mouse enters the boundary of a different item, you can switch the interaction mode to mouse, and have the focus ring disappear. Can I manually change the interaction mode on focus of a different section?

**Comment by snowystinger** [comment]
You'd be looking for https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/interactions/src/index.ts#L19
It's definitely a use at your own risk situation though. We don't document it and it could change. It also causes a re-render in almost every one of our hooks (something we're working on). I don't think it hurts to be a little overly obvious with focus indicators. Most people using a mouse will click on something pretty quickly.
