### ISSUE TITLE
Focusing on input elements inside a table does not work

### ISSUE THREAD

**Issue by djangbahevans** [adobe/react-spectrum#3598]
# 🐛 Bug Report 
An TextField component inside a table row within a table component does receive focus.

## 🤔 Expected Behavior
Clicking on an TextField component inside a table should send focus to the TextField component.

## 😯 Current Behavior
Clicking on a TextField component sends the focus to the body element instead of the actual element that was clicked.

## 💁 Possible Solution
The problem is caused by the onMouseDown function in the gridProps object returned by the useTable hook. Not passing the onMouseDown function to the table fixes the problem. If this can not be immediately fixed, maybe a warning in the documentation about this problem will suffice.

## 🔦 Context
I was trying to create a table not just to display data, but to actively accept information from a user. However this problem prevented users from being able to click and type information into the input fields within the table. 

## 💻 Code Sample
https://codesandbox.io/s/usetable-focuswithin-issues-h4jf0s

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | latest
| Browser          | chrome, firefox, - all latest
| Operating System | windows 11

**Comment by devongovett** [comment]
The problems go beyond just that. Once you are in a textfield, the arrow keys should move your cursor rather than moving between cells. This requires an edit mode to be implemented and the user must explicitly enter and exit this mode to use a textfield within a table. See #2328

**Comment by devongovett** [comment]
Going to close as a duplicate. Edit mode is on our roadmap for Q1 2023.

**Comment by LFDanLu** [comment]
No updates on edit mode yet, we added a partial implementation for interactions with the column resizers but will still need some work. I don't think there are any good work arounds since the column headers use `useGridCell` which has a [capturing level listener handling keyboard events](https://github.com/adobe/react-spectrum/blob/da38fa0da7da175032209fccb4556c0d580d0274/packages/%40react-aria/grid/src/useGridCell.ts#L107).

That being said, could you move your SearchField outside of the Table entirely? Is there a reason you need it within the TableHeader itself?

**Comment by jrmyio** [comment]
For the project I am working on its a requirement for every column to have some kind of filter or searchfield underneath it's column label, mainly because by the clients this is perceived as the most quick and user friendly way. So moving them outside of the table would cause big issues to line them up with columns widths and label heights.
