### ISSUE TITLE
Labels for buttons not triggering click events with `onPress` on Firefox

### ISSUE THREAD

**Issue by wahidshafique** [adobe/react-spectrum#3613]
# 🐛 Bug Report 

On firefox, there seems to be a problem when a label is associated with a sibling `button` that uses `onPress`. According to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label#try_it) we should expect that, 
> When a user clicks or touches/taps a label, the browser passes the focus to its associated input (the resulting event is also raised for the input). That increased hit area for focusing the input provides an advantage to anyone trying to activate it — including those using a touch-screen device.

## 🤔 Expected Behavior

The behaviour should be the same as when I use `onClick`, for the click on the label to be sent to the button and initiate an alert (see codesandbox)

## 😯 Current Behavior

on Firefox, clicking the label simply triggers the hover state of the button but does not click.

## 💁 Possible Solution

This is purely an issue with `onPress` not catching the event that the browser is passing, `onClick` works as intended on all browsers. My rough solution was to simply honor an associated labels click event seen here 
https://github.com/adobe/react-spectrum/pull/3614

## 🔦 Context

I expect that the solution should work the same across browsers. Currently this presents a trade-off for me. So either

A. I use `onClick` instead of `onPress`, and sacrifice all the benefits of `onPress` such as keyboard navigation etc
or
B. I use `onPress` and accept that firefox users clicking labels will have a sub-optimal experience.

## 💻 Code Sample

https://codesandbox.io/s/react-aria-firefox-label-issue-8hj39z?file=/src/App.js

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-aria   | 3.2.0
| Browser          | Firefox
| Operating System | Mac OS Monterey 12.0.1

**Comment by dannify** [comment]
Can we have some more information on what the use case is for this functionality? I have never seen a label for a button before. Is there a bug for this in Firefox?

**Comment by wahidshafique** [comment]
@dannify I think one issue is parity; that fact is that now, the behaviour of `onPress` is oh so slightly different from `onClick`. In the recreations I linked, `onClick` always behaves as intended, which is to pass along the labels click event to the associated buttons handler.

A use-case for this is when it comes to Likert scale options. The supplementary labels not only act as guiding markers, but ideally those labels being clicked should also trigger the associated Likert button's hander.
<img width="784" alt="image" src="https://user-images.githubusercontent.com/9141395/196774590-c3a9c78c-4da9-4acd-b998-3666ecbd37da.png">

**Comment by snowystinger** [comment]
Hey, I chatted with the team more and we dove into the root cause of this. The issue is a difference in Firefox vs the other browsers. I've filed a bug with them here https://bugzilla.mozilla.org/show_bug.cgi?id=1796300

I think given the complexity of usePress, this isn't something we want to take on right now, and would prefer to let the browser make a fix.

In the meantime, there are several workarounds available. The one I'd recommend is to represent this scale as a radiogroup. Since you can only select one option, this makes more sense accessibility-wise in addition to the label working as a click target. https://codesandbox.io/s/dank-wave-p8dqis?file=/src/App.js

Another option is to place the label inside the button with the graphic.
