### ISSUE TITLE
onKeyDown event on the SearchAutocomplete component is getting fired twice.

### ISSUE THREAD

**Issue by manasayedire** [adobe/react-spectrum#3684]
# 🐛 Bug Report 

onKeyDown event on the SearchAutocomplete component is getting fired twice.

## 🤔 Expected Behavior

onKeyDown event on the SearchAutocomplete component should get fired once.

## 😯 Current Behavior

onKeyDown event on the SearchAutocomplete component is getting fired twice.

## 💻 Code Sample

https://reactspectrum.blob.core.windows.net/reactspectrum/1b4d3af728d7eed74834601cc796ffb4ecd89966/docs/react-spectrum/SearchAutocomplete.html
https://codesandbox.io/s/jolly-moon-8ljsvy?file=/src/App.js

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

## 🧢 Your Company/Team

 Adobe/Adobe Sign

**Comment by snowystinger** [comment]
This is likely happening because useSearchAutocomplete merges the input props of two hooks which both independently call `onKeyDown` on the props they are passed. We should be able to just pass `props.onKeyDown` to one of them
This is the line where they are merged:
https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/autocomplete/src/useSearchAutocomplete.ts#L94

I think we can just pass an `onKeyDown: null` here:
https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/autocomplete/src/useSearchAutocomplete.ts#L82
in order to overwrite the one on the props object we are spreading.

This is likely affecting some other prop events as well. onKeyUp definitely. Not sure about others such as focus/change/or any of the useTextfield events ie onCompositionEnd/onSelect/etc
