### ISSUE TITLE
popover will auto dismiss when focus out from a input inside it

### ISSUE THREAD

**Issue by minzojian** [adobe/react-spectrum#3788]
# 🐛 Bug Report 

first of all,i am not using spectrum, but work on aira and stately together

i copied the offical sample code, and create a popover and checkbox, then placed checkbox inside of popover, however, when i double click the checkbox, the popover will auto dismiss.
it seems that when  some input component's focus lost, the dialog would auto dismissed

## 🤔 Expected Behavior

keep the popover shown no matter i click anywhere inside it 

## 😯 Current Behavior

 dialog would auto dismiss when i first click checkbox then click the plain text 

## 💁 Possible Solution

no idea :(

## 🔦 Context

i was going to create a form inside a popover, that contains many input components, if the popover auto dismiss, i can't finished fill the form. 

## 💻 Code Sample

here is the codesandbox link
https://codesandbox.io/s/gifted-keller-w5yvoe?file=/src/App.tsx

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-aira  |  3.21.0
| react-stately | 3.19.0
| Browser          | Chrome latest
| Operating System | Mac OS latest

## 🧢 Your Company/Team

Indie Developer

**Comment by LFDanLu** [comment]
@minzojian Is there a particular reason you aren't using `useDialog` with your Popover [like so](https://codesandbox.io/s/hopeful-panka-1oqioj?file=/src/Dialog.tsx)? See https://react-spectrum.adobe.com/react-aria/usePopover.html#features for mention of why you'd want to use `useDialog` (accessibility). If I had to guess, the auto dismissing is probably due to a blur event triggering [this](https://github.com/adobe/react-spectrum/blob/810579b671791f1593108f62cdc1893de3a220e3/packages/%40react-aria/overlays/src/useOverlay.ts#L127-L136) since your popover itself isn't focusable and thus focus is being lost to the body or something

**Comment by snowystinger** [comment]
I think this is more of a documentation bug, another user has provided a confusing paragraph from our documentation https://github.com/adobe/react-spectrum/issues/4961#issuecomment-1689318807

**Comment by snowystinger** [comment]
I'm going to close this one as people seem to be figuring it out now. If it's still an issue, we accept contributions and we can reopen this.
