### ISSUE TITLE
React-aria versions of react-spectrum Tray

### ISSUE THREAD

**Issue by mitchellwarr** [adobe/react-spectrum#3816]
# 🙋 Feature Request

The react-spectrum package has a feature not available if you are solely building on top of react-aria and react-stately; the mobile tray versions of the Picker and ComboBox. 

## 🔦 Context

The trays used by these are very useful and have special logic and code inside the react-spectrum implementation. It is certainly possible to recreate a mobile tray, and copy implementation details from react-spectrum, but that is not an ideal solution.

We are currently building a component library on top of react-aria and react-stately, since our design team wants a lot of flexibility but we also care about a11y. The mobile trays have so far been complicated to implement, and we would rather not copy implementation examples from react-spectrum since it can easily get out of sync with bug fixes in the futrue.

There is a lot of code in the ComboBoxTray that basically looks like its own useMobileComboBox hook.

**Comment by LFDanLu** [comment]
Definitely something we can consider doing, my only hesitation would be the divergences our MobileComboBox has from the    [WAI-ARIA ComboBox pattern](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/) in general and where we would draw the line when deciding which of those divergences are Spectrum design specific.

**Comment by jakubriedl** [comment]
Another very useful use-case for Tray from react-spectrum is Menu. The current version in RAC doesn't do that on mobile and so creates a usability issue.

react spectrum docs even call it out:
> [Trays](https://react-spectrum.adobe.com/react-spectrum/Menu.html#trays)
On mobile, Menus automatically display in a tray instead of a popover to improve usability.

**Comment by snowystinger** [comment]
We hope to bring `Trays` to RAC in the near future.

**Comment by devongovett** [comment]
I don't think we need to do anything for them. You can already build a Tray with the Modal component and some custom styles. This example opens to the side but you could just as easily build a bottom tray. https://react-spectrum.adobe.com/react-aria/Modal.html#custom-overlay

**Comment by jakubriedl** [comment]
Good to know, thanks for the links. In the Menu use-case there's however the complexity of sliding left and right with submenus. Is there some way how to achieve that with existing components/hooks?

**Comment by snowystinger** [comment]
I think you have a couple options. You could make a Popover which just renders into place, sibling to root Menu.

If it needs to be more complex. All the hooks and state for Popovers should be available via the context. You can reference our implementation. I also made a stripped down example the other day for another discussion.
https://github.com/adobe/react-spectrum/discussions/6258#discussioncomment-10027318

@devongovett am I missing an easier way to do this? Otherwise I imagine we'll add something (even just an example) in the near future.

**Comment by snowystinger** [comment]
Closing as this should be doable.

**Comment by monolithed** [comment]
> I don't think we need to do anything for them. You can already build a Tray with the Modal component and some custom styles. This example opens to the side but you could just as easily build a bottom tray. https://react-spectrum.adobe.com/react-aria/Modal.html#custom-overlay
> 
> And for a more fancy example here's one that you can swipe to close https://react-spectrum.adobe.com/react-aria/examples/framer-modal-sheet.html

@devongovett, it's really hard to find a modern website these days where the mobile menu doesn't slide out in a tray – it's kind of a standard. But you're suggesting adding a library and then writing custom CSS on top of it, which might not even work bug-free?  
I've criticized Ant Design plenty of times for its performance, but every time I look for alternatives to Tabs, Drawer, Collapse, or Dropdown, I end up going back to it. Why? Because I don’t have to reinvent the wheel with custom components – most of the features I need are already built-in.

**Comment by devongovett** [comment]
All of react aria components is style free so I'm not sure how this component is any different than our others?
