### ISSUE TITLE
Auto-scroll does not work with virtualized GridList when navigating using keyboard

### ISSUE THREAD

**Issue by grzegorz-zadora** [adobe/react-spectrum#3822]
# 🐛 Bug Report 

Auto-scroll does not work with virtualized GridList when navigating using keyboard

## 🤔 Expected Behavior

Auto-scroll should work the same way when GridList is virtualized and when it's not virtualized.

## 😯 Current Behavior

I've created a GridList using example from the docs: https://react-spectrum.adobe.com/react-aria/useGridList.html

When `isVirtualized` prop is not set (or has `false` value), and I navigate through the list using keyboard, the auto-scroll works like a charm.

However, when I set `isVirtualized` prop to `true` the auto-scroll **stops working with keyboard navigation**.

By saying keyboard navigation, I mean going through the list using up/down arrow or page up/down keys.

## 💁 Possible Solution

Sadly, I have no idea :crying_cat_face: 

## 🔦 Context

I'd like to have a virtualized list that supports keyboard navigation.

## 💻 Code Sample

Here's an example:

https://codesandbox.io/s/musing-nobel-wvifq9?file=/src/App.tsx

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-aria   |  3.21.0
| react-stately | 3.19.0
| Browser          | Chrome Version 108.0.5359.94 (Official Build) (64-bit).
| Operating System | Ubuntu 22.04

Thank you very much for your work on `react-aria`.

I'm looking forward for the answer :crossed_fingers:

**Comment by LFDanLu** [comment]
When `isVirtualizer` is set, we assume the virtualized list/virtualizer will handle scrolling focused items into view. In the React Spectrum ListView component, we have our own [Virtualizer](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/virtualizer/src/Virtualizer.tsx) component. In your codesandbox however, you aren't using a virtualized list and thus every item is rendered to the DOM. In that case you should set `isVirtualized` false so that the item can be scrolled into view via [useSelectableCollection](https://github.com/adobe/react-spectrum/blob/582ac7cd9736925ee842f28a1cf4d37ff2188173/packages/%40react-aria/selection/src/useSelectableCollection.ts#L357-L365).

**Comment by grzegorz-zadora** [comment]
I see, I was under the impression that the `useGridList` hook already has a virtual scroll working. 

Thank you for clarifying @LFDanLu :bow:
