### ISSUE TITLE
TableView: hideHeader columns show clipped focus rings on ActionButtons

### ISSUE THREAD

**Issue by carolframpton** [adobe/react-spectrum#3825]
# 🐛 Bug Report 

TableView hideHeader default width column with ActionButton shows clipped focus ring
## 🤔 Expected Behavior

Focus ring should not be clipped.

## 😯 Current Behavior
https://reactspectrum.blob.core.windows.net/reactspectrum/82d74597a0176141733a4c2366392f39ebe7811d/storybook-17/index.html?path=/story/tableview--hideheader&providerSwitcher-express=false&providerSwitcher-toastPosition=bottom

Keyboard to one of  `Add Info` or `Delete Item` cells. Note the focus ring is clipped.

![image](https://user-images.githubusercontent.com/71789937/206544242-63c17a86-94d7-4085-9fd4-101d0315da77.png)

Rob made this code sandbox which shows a compact table: https://codesandbox.io/s/fancy-sun-ye8dgm?file=/src/App.js

![image](https://user-images.githubusercontent.com/71789937/206548791-c2bccd33-08e4-4edd-bc04-64bd7bba323b.png)

## 💁 Possible Solution

Issue is https://github.com/adobe/react-spectrum/blob/main/packages/%40react-spectrum/table/src/TableView.tsx#L119

## 🔦 Context

We have many tables which have Action columns.

We have many usages of ActionButtons, in tables and not, that are impacted by the focus ring change. It seems that we need to add a small margin around each ActionButton to ensure the focus ring is not clipped.

## 💻 Code Sample

Spectrum TableView hideHeader storybook demonstrates this problem.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.23.0
| Browser          | Chrome
| Operating System |

## 🧢 Your Company/Team

Adobe Admin Console

**Comment by snowystinger** [comment]
Spectrum moved everything to a halo focus in order to improve contrast. They are ok with some clipping due to this. Native controls are affected by this as well. Until Chrome and other browsers can resolve the paint order for focus rings, like this issue https://bugs.chromium.org/p/chromium/issues/detail?id=462609, this is considered acceptable. So every focusable element does not need a safety margin around it.

That said, we should still fix this for the obvious case of TableView, and we decide on other instances on a case-by-case basis.

**Comment by LFDanLu** [comment]
For posterity: https://github.com/adobe/react-spectrum/blob/703ab7b4559ecd4fc611e7f2c0e758867990fe01/packages/%40react-spectrum/table/src/TableView.tsx#L125-L127 is a good place to look to patch this in TableView
