### ISSUE TITLE
TableView - allowsResizing is breaking style for columns with align=end

### ISSUE THREAD

**Issue by minaseem** [adobe/react-spectrum#3880]
Table header alignment is not proper when `allowsResizing` is `true` on columns with `align: end`

### Expected Behaviour
On columns with `align: end`, their headers should be aligned to the end.
### Actual Behaviour
Table header alignment is not proper when `allowsResizing` is `true` on columns with `align: end`
On columns with `align: end` and `allowsResizing: true`, their headers are aligned to `start`.
#### Steps to Reproduce
1. Use `TableView`
2. On any column, add below props
   - align: end
   - allowResizing: true
3. Observe the alignment of header of the column mentioned in previous step. Expectation is that header should be aligned to the `end`, however it is getting aligned to `start`. Refer screenshot below

<img width="547" alt="image" src="https://user-images.githubusercontent.com/5484032/210488213-1cb775a0-ac48-432f-802e-25827fe1fe84.png">

#### Platform and Version
v3.24.1

#### Sample Code that illustrates the problem
```tsx
<TableView
  aria-label="TableView with resizable columns"
  maxWidth={320}
  height={200} >
  <TableHeader>
    <Column key="file" maxWidth={500}>File Name</Column>
    <Column key="size" width={80} allowsResizing={true} align="end">Size</Column>
    <Column key="date" allowsResizing minWidth={100} allowsResizing={true} align="end">Date Modified</Column>
  </TableHeader>
  <TableBody>
    <Row>
      <Cell>2022-Roadmap-Proposal-Revision-012822-Copy(2)</Cell>
      <Cell>214 KB</Cell>
      <Cell>November 27, 2022 at 4:56PM</Cell>
    </Row>
    <Row>
      <Cell>62259692_p0_master1200</Cell>
      <Cell>120 KB</Cell>
      <Cell>January 27, 2021 at 1:56AM</Cell>
    </Row>
  </TableBody>
</TableView>
```

**Comment by snowystinger** [comment]
Thanks for the issue. I have started talking with the team and it's unclear how we should handle this, so we're looking for feedback from users.

We have a menu chevron that appears to the right of the header text when a column is resizable. It's hidden by default, and appears during hover or focus of the header cell. When left aligned, this is not an issue, it just appears on the right.
When right aligned however, it does cause a problem, it causes the entire header text to shift over in order to make room.

We have a few options, none of which are ideal:
- Treat this shift as acceptable
  - hover of headers happens pretty frequently for mouse users and layout shifts are not good for people who prefer reduced motion
- Always reserve space for the chevron, but still only show it on focus/hover
  - the header text wouldn't appear to align with the rest of the column text
- Always show the chevron
  - there could be many chevrons on a table, so it might clutter the layout
- something else?

**Comment by snowystinger** [comment]
Talked with our design team, decision is to align the headers with the rest of the cells in the column and to always show the menu chevron. While this is slightly noisier, we've decided that it will also be helpful to touch users who have no concept of focus or hover and thus wouldn't know there is a menu without the chevron.
