### ISSUE TITLE
Clicking the label of an input that is a child of a draggable item activates drag and drop mode, freezes focus

### ISSUE THREAD

**Issue by chuckdries** [adobe/react-spectrum#3901]
# 🐛 Bug Report 

1. spread dragProps from useDraggableItem into a div, and put a TextField or some other input in that div. Make sure to specify `hasDragButton: false` in the useDraggableItem configuration.
2. click the label of the input
3. focus is now stuck inside that input. Nothing else on the page can be interacted with

## 🤔 Expected Behavior

Input should be focused, but in a way that allows it to lose focus

## 😯 Current Behavior

Input is focused, but is stuck in that input. Can become un-stuck by pressing escape.

## 🔦 Context

We're seeing this behavior inside a Dialog whose DialogTrigger is rendered in the draggable item.

## 💻 Code Sample

https://codesandbox.io/s/spectrum-focus-freeze-t6ko8q?file=/src/App.tsx

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.24.1 |
| Browser          | chrome, safari |
| Operating System | macOS |

## 🧢 Your Company/Team

Adobe Marketo

**Comment by reidbarber** [comment]
Looks like clicking the label qualifies as a virtual click here:

https://github.com/adobe/react-spectrum/blob/73d8be4dd7ff1713084cfe3f602f11aef1cecb07/packages/%40react-aria/dnd/src/useDrag.ts#L318-L325

**Comment by LFDanLu** [comment]
TODO: investigation on what nativeEvent info is returned here so that we can try to distinguish between the screenreader click and label click. We'll also want to make sure the drag hooks warn if a draggable element isn't focusable nor has a role and doesn't support a separate drag affordance.

@chuckdries Just want to make sure: is the sandbox you provided a rough reflection of an in app use case? If so, just want to emphasize that you'll want a separate drag affordance for that draggable div OR the div needs to be keyboard focusable and have a role applied on it for screenreaders/keyboard users to be able access and drag said div.

**Comment by chuckdries** [comment]
yep!

**Comment by LFDanLu** [comment]
@chuckdries Apologies, I must've missed your reply in my inbox. Did adding a separate drag affordance or making the wrapping div keyboard focusable resolve your issue? Just wanna be sure we have the proper experience drag and drop experience in your app.

**Comment by chuckdries** [comment]
Sorry, I could've been more clear: yes, the sandbox is a rough approximation of our app. Yes, we have made sure the div is keyboard focusable and announced by screen readers. We also have a visual drag handle inside the card. The issue is present with these features implemented. I omitted all that from the sandbox because it doesn't affect the bug.

I'm pretty sure the issue would go away if we made only the visual drag handle draggable, but our designs called for the whole thing to be draggable.

**Comment by LFDanLu** [comment]
I see. Since you already have a separate drag affordance in your card, is there a particular reason you need `hasDragButton: false`? Providing `hasDragButton: true` just makes it so the various handlers to start our accessible drag and drop (aka handlers like entering drag when Enter/screen reader click happen on the element) are provided to the drag handle via `dragButtonProps` instead of the entire drag element as a whole. The whole drag element is still draggable in that case.

**Comment by chuckdries** [comment]
Oh, I see. I'll poke at it and get back to you.

**Comment by chuckdries** [comment]
`hasDragButton: true` appears to solve the issue!

The reason we were using `false` was that our drag handle was inside an `item.rendered`, so it wasn't immediately clear how to pass the `dragButtonProps` through to it. Turns out a react `context` worked fine. 

Apologies for the late response 😅

**Comment by LFDanLu** [comment]
No worries and glad it worked for you! I'll close this for now, feel free to reopen if other issue occur with `hasDragButton: true`
