### ISSUE TITLE
`usePreventScroll` refers to `useDialog` documentation, but isn't mentioned there

### ISSUE THREAD

**Issue by Vinnl** [adobe/react-spectrum#3909]
# 🙋 Documentation Request

The [docs on `usePreventScroll`](https://react-spectrum.adobe.com/react-aria/usePreventScroll.html) say:

> See [useDialog](https://react-spectrum.adobe.com/react-aria/useDialog.html#example) for an example of using usePreventScroll to prevent scrolling on the document body on dialog mount.

However, <kbd>Ctrl</kbd>+<kbd>F</kbd> `scroll` doesn't turn up anything (interestingly, `usePreventScroll` isn't mentioned in the sidebar anymore either, even though it is listed on e.g. [this page](https://react-spectrum.adobe.com/react-aria/useOverlayTrigger.html)).

**Comment by devongovett** [comment]
A bunch of those lower level APIs were removed from the index in favor of higher level APIs that are now available. I think those links are still working because they were previously deployed and not overwritten, so they may be outdated.

If you're using the old low level API (`useModal`), then it would still be necessary to use `usePreventScroll` yourself. But if you switch to the newer API `useModalOverlay` and `<Overlay>`, then it is included for you automatically. See the docs for [useModalOverlay](https://react-spectrum.adobe.com/react-aria/useModalOverlay.html) for an example of the new API.
