### ISSUE TITLE
useDateRangePicker commits selection when updating popover placement

### ISSUE THREAD

**Issue by nathanforce** [adobe/react-spectrum#4007]
# 🐛 Bug Report 

A bit of background...I'm attempting to create a DateRangePickerField that appears as two conjoined fields rather than a single field with two values inside.  When selecting a date range via the picker we want the calendar popover to shift its alignment to the edge of the field being selected.  So when selecting the startDate (`!state.anchorDate`) we align `bottom start` and when selecting the endDate `(state.anchorDate !== null)` we align `bottom end`.

Video of desired behavior:

https://user-images.githubusercontent.com/6694194/216640373-88344f3e-48a8-4483-bc2f-e93b1c5f6644.mov

This technically works, meaning the `placement` is indeed updated when `state.anchorDate` changes.  However, this results in the popover moving during `pointerDown` and thus the pointer is over a different element on `pointerUp` so it seems the hook is treating this as if the user did a drag selection on the range.  The popover is immediately closed and the field is populated with a range despite the user only pressing on a startDate.

I've managed to work around it by waiting to update `placement` after a 150ms timeout but that feels like a magic number and fragile.

## 🤔 Expected Behavior

I'd expect to be able to update `placement` without it being treated as a drag.

## 😯 Current Behavior

Updating `placement` is treated as a drag.

## 💁 Possible Solution

Not sure!

## 🔦 Context

See video

## 💻 Code Sample

I've updated the Tailwind example to reproduce the issue.

https://codesandbox.io/s/loving-cohen-sb0iyf?file=/src/RangeCalendar.js

**Comment by snowystinger** [comment]
You could treat both inputs as one single one so that the popover doesn't jump positions. Sounds like you've already considered this to some extent from your opening sentence. I think this would probably be recommended anyways though for users who prefer reduced motion anyways. People with low sight or tunnel vision may have a difficult time tracking where the popover has gone.

Your demo is a little misleading though in the video and would appear to contradict your opening sentence. There is a drop down button only on the second date's field. This leads to it feeling more like a single input. To make it two, you'd need a drop down on each, which could also solve your problem, because then the first one could select one date and close, then they can choose to open the second one or not if you allow open ended ranges.

You could also make the calendar a two month view to make selecting a range easier and reduce the need to move it.

**Comment by nathanforce** [comment]
Hey thanks for the response! I understand there are some design decisions we can make to work this out (and we probably will) but just wanted to confirm that you feel this is expected behavior? Regardless of whether the design is appropriate for the use case I did find the behavior unexpected.

**Comment by snowystinger** [comment]
I'm not sure what else we would do. For a range we allow press and drag to select. This means that we need to set the start anchor on press down, and the end date would be on press up. Following that, I think our behavior is expected. I think it's more unexpected that the calendar shifted out from under the user. Open to other thoughts if you have ideas on how to differentiate between the cases.

**Comment by ktabors** [comment]
Closing and if it's still a problem or you have additional information we can reopen.

**Comment by ktabors** [comment]
Closing and if it's still a problem or you provide additional information we can reopen.
