### ISSUE TITLE
how to useGridRowGroup

### ISSUE THREAD

**Issue by xajhqffl** [adobe/react-spectrum#4021]
I don't see any documentation around how to use this hook `useGridRowGroup`. I'm trying to follow the example from here https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/grid/stories/example.tsx. However, `useListState` only takes `Item` as the children nodes. I'm not able to use any other component created from `useGridRowGroup`

### Expected Behaviour

```jsx
export const GridRowGroup = (props) => {
  let { children } = props;
  let { rowGroupProps } = useGridRowGroup();
  return <div {...rowGroupProps}>{children}</div>;
};
```

```jsx
<Grid>
    <Item></Item>
    <GridRowGroup>
        <Item />
    </GridRowGroup>
</Grid>
```
### Reproduce Scenario (including but not limited to)

Please take a look at this code snippet.

https://codesandbox.io/s/muddy-silence-di06sh

**Comment by snowystinger** [comment]
Have you taken a look at how we use it in our components? Here's our TableView https://github.com/adobe/react-spectrum/blob/main/packages/%40react-spectrum/table/src/TableView.tsx#L581

And here it is in our docs as well https://react-spectrum.adobe.com/react-aria/useTable.html#example

We haven't done documentation for the lower level grid hooks yet because they may still change.

**Comment by xajhqffl** [comment]
Thank you!
