### ISSUE TITLE
Doc Issue: useFocusRing differs between Listbox Option in useComboBox and useListbox docs

### ISSUE THREAD

**Issue by ashleyryan** [adobe/react-spectrum#4163]
# 🙋 Documentation Request

I first built a listbox component using useListBox and now I'm building a combobox on top of that following the useComboBox documentation. For the longest time I couldn't figure out why no options were showing as focused using keyboard navigation. As it turns out, the `useListBox` documentation shows the `Option` component using `useFocusRing` to determine `isFocusVisible`, which has different behavior than getting `isFocused` from `useOption` which is used in the useComboBox documentation.

- [ListBox documentation](https://react-spectrum.adobe.com/react-aria/useListBox.html#example)
- [ComboBox documentation - listbox code sample](https://react-spectrum.adobe.com/react-aria/useComboBox.html#listbox)

`isFocusVisible` doesn't appear to work with combobox, I'm assuming because focus remains on the input. Is it safe to not use `useFocusRing()` with a listbox?

This might be a bug, not a documentation issue, but I'd love to see the code examples on the two pages match.

**Comment by LFDanLu** [comment]
You're hunch about combobox and `useFocusRing`'s `isFocusVisible` is correct. A listbox option's visual focus state is a bit more complicated than portrayed in the `useListBox` docs and the `useComboBox` docs for that reason, really it should be a combination of the two implementations if the same ListBox is going to be used for both combobox and non-combobox components. In our Spectrum implementation of [ListBoxOption](https://github.com/adobe/react-spectrum/blob/05be974f59eece54dd2f47f1866e1c30031c0999/packages/%40react-spectrum/listbox/src/ListBoxOption.tsx#L72-L84) we use `useOption`'s `isFocused` and a keyboard modality check to display the focused state for the combobox's "virtual" focus case and otherwise rely on `FocusRing` to apply the visual focus style in the standard ListBox use case.

For the sake of simplicity, we didn't go into that level of implementation detail for the aria docs but we can try to refine the docs to make that clearer. [Aria Components](https://github.com/adobe/react-spectrum/pull/4058) will also help alleviate this issue as well for users who just want to use an stylable aria ListBox without needing to implement these hard to find details themselves

**Comment by ashleyryan** [comment]
Ok, that all makes sense - thanks for the link to the Spectrum implementation. I've been wading into all of the source code for react-stately and react-aria, but not the actual spectrum components. 

I will stick with `isFocused` from `useOption` for now as our org hasn't made the switch to `:focus-visible` yet, but this is a helpful reference for when we do.

**Comment by devongovett** [comment]
We could probably add an `isFocusVisible` property to the return value of `useOption` using that same logic. I needed it in React Aria Components as well so probably good to centralize it.
