### ISSUE TITLE
Combo box popover stays even if user click outside 

### ISSUE THREAD

**Issue by nawazmobusss** [adobe/react-spectrum#4233]
# 🐛 Bug Report 

This is related to combo box component https://react-spectrum.adobe.com/react-spectrum/ComboBox.html#trigger-options.
User clicks on the text field and then dropdown shows up. But when user removes the focus from the text field, the drop down list keeps showing up, blocking the user to proceed. 

## 🤔 Expected Behavior

Upon clicking outside of the text box, the drop down should get closed.

## 😯 Current Behavior

User clicks on the text field and then dropdown shows up. But when user removes the focus from the text field, the drop down list keeps showing up, blocking the user to proceed.  This behavior is replicated in the documentation playground too https://react-spectrum.adobe.com/react-spectrum/ComboBox.html#trigger-options

## 🔦 Context

This is affecting all the combo boxes in our app. We have around 5 combo boxes and all these flows are impacted.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

## 🧢 Your Company/Team

Adobe Express - Content Production Engineering Team

**Comment by nawazmobusss** [comment]
Thanks @LFDanLu , for taking a quick look at this! We are planning to onboard 100s of designers to our application in couple of weeks. Could we expect some quick fix on this?

**Comment by LFDanLu** [comment]
Did some investigation, the issue seems to be that with the changes in https://github.com/adobe/react-spectrum/commit/168ca5a5cd53589bae6620fba1602e18240efc46, the ComboBox's popover [overlay](https://github.com/adobe/react-spectrum/blob/23a33ceb3e36706a3aceb0f55cdb4645223efb57/packages/%40react-aria/overlays/src/Overlay.tsx#L47) now always has a FocusScope with `restoreFocus`, which on close refocuses the ComboBox, resulting in the popover reopening when the ComboBox has `menuTrigger='focus'`. I think ideally our `restoreFocus` logic shouldn't try to restore focus if focus never entered that scope in the first place, theoretically we should be checking if there is an active scope [here](https://github.com/adobe/react-spectrum/blob/23a33ceb3e36706a3aceb0f55cdb4645223efb57/packages/%40react-aria/focus/src/FocusScope.tsx#L624-L635) perhaps and skip the restore focus logic if the scope being unmounted wasn't the active scope or didn't contain the active scope. However, we also seem to be setting the active scope [here](https://github.com/adobe/react-spectrum/blob/23a33ceb3e36706a3aceb0f55cdb4645223efb57/packages/%40react-aria/focus/src/FocusScope.tsx#L537-L539) if no active scope exists and a FocusScope with `restoreFocus` mounts, even though the `focusin` event that triggers that logic is from focusing the combobox input which is outside the FocusScope. We should probably add logic there to check that the focused element is actually in the current active scope instead.

@nawazmobusss The team currently has its hands pretty full at the moment prepping for an upcoming release so a immediate fix is unlikely. If you need this fix sooner rather than later, we'd welcome a contribution. I've outlined the areas above that I imagine would need to be changed for this fix.

**Comment by boutahlilsoufiane** [comment]
Hello @LFDanLu  I would love to work on this!

**Comment by LFDanLu** [comment]
@boutahlilsoufiane Sounds good, lemme know if you have any questions about what I've outlined about!
