### ISSUE TITLE
Documentation needs improvements

### ISSUE THREAD

**Issue by eran-or** [adobe/react-spectrum#4320]
# 🙋 Documentation Request
I'm using this library 3 days. Honestly, what I tried to achieve  should take have an hour. 
I only tried to add a button that located in an horizontal menu and open a dropdown menu.
This is my conclusions:
1. It would be very helpful to have a button - "Open in codesendbox" next to the demo (element to try). because if I copy paste the example to my project from your website and it doesn't work for me then obviously there is a difference between the example and the demo.   
2. The Getting started should have a big improvement in the flow. There's a lot of important details that should be in the examples:
First The getting started have to many next steps. It's confusing, I don't know what to do next and it is missed the point of giving the user a quick start. It would be very helpful to have a full blown basic app demo with Buttons, Modal etc. that every website have and every next click will show me the next step among the important features that the library offer. 
3. This page: https://react-spectrum.adobe.com/react-aria/useOverlayTrigger.html is not in the documentation of that page: 
https://react-spectrum.adobe.com/react-aria/
Probably something you forgot to remove from google search. or I don't know...
4. A little search in site input will be amazing 
5. There's a flow problem:
 In order to do a dropdown menu with a button trigger I needed to learn the usePopover, useMenu, useOverlayTrigger, useOverlay and so on.First part of the hooks resides in two different locations that I pointed on 3. which is the right version? I still not sure that I understand the difference between the overlay and the dialog but let put aside because it is a smaller problem. Third, the big problem was the lack of two flows with good examples one for SSR and one for CSR.  The use Providers that affect on the whole app should be in the getting started first page, second, the need to use SSRProvider and that it cause a problem when using OverlayContainer and Overlay which render in this situation in a portal outside of corse the DOM app tree and position it self somewhere in the space (of the page). It took me a lot of time and effort to find the solution which was to add portalContainer attribute. Why you didn't write it on the basic example? or better to ask Shouldn't it better to do portalContainer={document.body} as default so it will work out of the box for most cases? (but I guess it's a different discussion). 
6. I think you should improve and extend the examples to show more then now. Developers mostly don't read the whole documentation at the first day and it will increase the usage if it will have more of code than explanation or info text.
It's only when a user got friendly with the library when he start to want more from the lib. 

This is only what I found in 3 days on this lib, imagine what I'll fined it a week. I put a lot of time and effort to write this because I can say it is a good library with a great team. I hope someone will put the effort to make it better in the months to come.

**Comment by snowystinger** [comment]
Thanks for the feedback! These are all great ideas.

1. We're working on getting this going. https://github.com/adobe/react-spectrum/pull/2978 it's been a bit on pause due to competing priorities. We do have some "styled examples" such as https://react-spectrum.adobe.com/react-aria/useDatePicker.html#styled-examples and we're working on adding more

2/5/6. Here's a peak at an alpha that will be in our next release hopefully making all of this easier https://reactspectrum.blob.core.windows.net/reactspectrum/7fa0a88e8925f432fa50516044907c58aa7ec952/docs/react-aria/react-aria-components.html and the RFC for it here https://github.com/adobe/react-spectrum/blob/main/rfcs/2023-react-aria-components.md

3. Yes, it's gotten stuck in google results for now. That hook is covered by usePopover now to hopefully reduce the number of hooks you'd need to use.

5. This should be coming very soon after our next release, https://github.com/adobe/react-spectrum/pull/3383

We accept PRs as well if there are specific things you'd like to see.

**Comment by eran-or** [comment]
Thank you for answering and for the great resources. I think if there was a
document version number on the top of the page that would help people to
understand which document is the new one and which is just there on the web
for some reason.
I'm new to this library so with time I'm sure I'll get involved more. It's
a great library with a great team and I'm sure it will be very popular.

‫בתאריך שבת, 1 באפר׳ 2023 ב-21:22 מאת ‪Robert Snow‬‏ <‪
***@***.***‬‏>:‬

**Comment by LFDanLu** [comment]
Closing this since we have work in progress for these
