### ISSUE TITLE
[React Aria Components] Missing Components Request

### ISSUE THREAD

**Issue by yangmingshan** [adobe/react-spectrum#4363]
# 🙋 Feature Request

Accordion Component
Toast Component
Pagination Component

## 🤔 Expected Behavior

React Aria Components including these components.

## 😯 Current Behavior

Not included.

## 💁 Possible Solution

https://github.com/adobe/react-spectrum/issues/848
https://react-spectrum.adobe.com/react-aria/useToast.html
https://github.com/adobe/react-spectrum/issues/1748

## 🔦 Context

I like React Aria Components, I want try it on my project, but these missing components blocked me. I mainly use [Radix](https://www.radix-ui.com/) now and some independent components like [React Headless Pagination](https://github.com/thijssmudde/react-headless-pagination).

## 💻 Examples

https://www.radix-ui.com/docs/primitives/components/accordion
https://www.radix-ui.com/docs/primitives/components/toast
https://github.com/thijssmudde/react-headless-pagination

## 🧢 Your Company/Team

Individual

**Comment by reidbarber** [comment]
Thanks for the request! The plan is to release any React Aira Components along with the release of the corresponding hooks. Because of this, we'll probably dedupe any requests for components in favor of existing requests for hooks. You can find the roadmap for components here: https://github.com/orgs/adobe/projects/19/views/18.

**Comment by yangmingshan** [comment]
@reidbarber Thanks for the response, feel free to close this issue.
