### ISSUE TITLE
Theming Configuration for Custom Color Palettes

### ISSUE THREAD

**Issue by MJ-One** [adobe/react-spectrum#4375]
Hey there, 
               I've been using react spectrum for a while now. when it comes to theme-Ing, I like to create a custom theme. But I can't see any guide regarding this action. please Help me out or provide some sources on how to build custom themes with react spectrum. Thank You.

**Comment by reidbarber** [comment]
Unfortunately, it isn't really possible at the moment. You can read more about why in this issue here: https://github.com/adobe/react-spectrum/issues/3370

That being said, you could consider using [React Aria Components](https://react-spectrum.adobe.com/react-aria/react-aria-components.html), where theming will be much easier.
