### ISSUE TITLE
Combobox menu popover appears empty, list items won't show up

### ISSUE THREAD

**Issue by Agile-fox** [adobe/react-spectrum#4525]
# 🐛 Bug Report 

After using combobox with example usage from spectrum docs the menu is empty. List of item component just don't appear at all. But you can still select them with keyboard. Console don't show any errors
![image](https://github.com/adobe/react-spectrum/assets/54645009/2d4e8d9b-c13a-4888-8225-6c7b7b6bac55)

## 🤔 Expected Behavior

Combobox is showing menu items when clicked on arrow key.

## 😯 Current Behavior
when clicking on combobox the menu popover appears empty when items are set. Work same for controlled and uncontrolled state.

## 💻 Code Sample

[Codesandbox](https://codesandbox.io/s/nostalgic-tereshkova-mlb6f9?file=/src/App.tsx)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |  3.26.0 
| Browser          | Firefox
| Operating System | Windows

**Comment by reidbarber** [comment]
Looks like this is due to React Strict Mode. You can fix it by removing `React.StrictMode` in `index.tsx`: https://codesandbox.io/s/jolly-framework-8lios9?file=/src/index.tsx

Issues with React Strict Mode are actively being worked on. We have an umbrella issue for those here: https://github.com/adobe/react-spectrum/issues/779

**Comment by devongovett** [comment]
Closing in favor of umbrella.
