### ISSUE TITLE
Link inside a menu

### ISSUE THREAD

**Issue by subhero24** [adobe/react-spectrum#4571]
A menuitem rendering a `<a href="...">` link prevents the link from working. Only when setting `closeOnSelect: false` in the useMenuItem hook, does the link work.

```javascript
function MenuItem(props) {
    let { item, state } = props

    let ref = useRef();
    let { menuItemProps } = useMenuItem({ key: item.key }, state, ref);

    return (
        <li ref={ref} {...menuItemProps}>
	    <a  href="/some/url">link</a>
        </li>
    );
}
```

**Comment by LFDanLu** [comment]
I believe this kind of menu item use case is more inline with the pattern covered [here](https://www.w3.org/WAI/ARIA/apg/patterns/menubar/examples/menubar-navigation/). Notice how the `a` receives the `menuitem` role instead rather than the wrapping `li`. I'm not sure our hooks are compatible with this kind of structure though, we typically rely on `onAction` for navigation instead. Also note the callout in w3 site that it is recommended to follow the [disclosure pattern](https://www.w3.org/WAI/ARIA/apg/patterns/disclosure/) instead

**Comment by LFDanLu** [comment]
https://github.com/adobe/react-spectrum/issues/1244 has some prior discussion and some workarounds to get this behavior, closing in favor of that issue.
