### ISSUE TITLE
Date picker unusable with screen reader (NVDA)

### ISSUE THREAD

**Issue by binaryartifex** [adobe/react-spectrum#4637]
# 🐛 Bug Report 

From the initial focus of the date picker field there is a large amount of repeated reading from the screen reader that its easy to get lost in the 'noise'. When i go to focus and open the calendar, the reader then proceeds to read out every single day in the calendar. 

## 🤔 Expected Behavior

When navigating the date picker with a screen reader and keyboard, the information conveyed shouldn't get lost in the constant repeating of previous labels or headings and when the calendar is in focus, the reader doesn't begin to read out each and every from the initial focused day.

## 🔦 Context

Ive been using the screen reader software NVDA while ive been developing my design system with react aria to ensure maximum WAI ARIA compliancy. However in this instance, navigating the date picker is problematic.

## 💻 Code Sample

The codesandbox link provided by the docs also has this issue. Download NVDA, then begin to tab through the datepicker and open the calendar. [docs link here](https://codesandbox.io/s/white-breeze-rer8g2?file=/src/Calendar.js)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-aria   | ^3.25.0
| @react-aria/calendar | ^3.3.0
| @react-aria/datepicker | ^3.4.1
| @internationalized/date | ^3.2.0
| Browser          | Chrome 114.0.5735.90
| Operating System | Windows 11

**Comment by majornista** [comment]
I think the issue is that NVDA shifts out forms mode when focus lands on the button within a cell within the calendar table, and as such, after announcing the focused element, starts to read the content of the dialog from that point forward. I think the easiest solution for this would be to use `role="application"` instead of `group` for the container `calendarProps` returned by the `useCalendarBase` hook here:  https://github.com/adobe/react-spectrum/blob/7f63e933e61f20891b4cf3f447ab817f918cb263/packages/%40react-aria/calendar/src/useCalendarBase.ts#L94-L97.

The [WAI-ARIA Authoring Practices Guide Date Picker Dialog example ](https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/examples/datepicker-dialog/) uses the `grid` pattern that focuses the cells within the grid, rather than a `button` within the cells, which triggers forms mode with NVDA, however I don't think we can remove the button, because support for selection with the WAI-ARIA grid pattern is insufficient on mobile screen readers like VoiceOver on iOS.

**Comment by binaryartifex** [comment]
@majornista cheers for the timely reply and work towards a fix mate. I hate to be 'that' guy, but it seems that when the NVDA application is open, there is no longer any visual confirmation of date or date range selection within the calendar. the screen reader reads the dates as the arrow keys are pressed however no styling or any visual confirmation is applied. is this intentional? Kinda feels like we 'robbed peter to pay paul' in this instance if it is....
