### ISSUE TITLE
[react-aria] Document and type `preventFocusOnPress` prop for `useButton`

### ISSUE THREAD

**Issue by maslennikov** [adobe/react-spectrum#4741]
# 🙋 Documentation Request

Quite a while ago a very useful prop `preventFocusOnPress` (alongside with `allowFocusWhenDisabled`) was introduced for `useButton` hook:
- https://github.com/interlay/interbtc-ui/pull/786
- https://github.com/adobe/react-spectrum/issues/918
- https://github.com/adobe/react-spectrum/issues/1247

Since then it stays undocumented and not included in types. Are there any reasons against making it public?

Relevant code: https://github.com/adobe/react-spectrum/blob/60e30029e5627ac514a354219a6f790f5fee45f7/packages/%40react-aria/button/src/useButton.ts#L58

**Comment by LFDanLu** [comment]
From what I can remember, we were mainly worried that people would misuse that prop and thus hesitant to document it. It isn't very often that you'd want focus NOT to move to the element the user is pressing/interacting with. We mainly added it for components where there are buttons that should behave as if they are a part of the whole component rather than a separate element, most commonly seen in composite fields.

A similar reason exists for `allowFocusWhenDisabled`, aka it has very specific use cases and didn't want expose it in case it was misused (you mention this prop in the issue, but maybe you meant `preventFocusOnPress`?)

**Comment by maslennikov** [comment]
@LFDanLu you are right, I meant `preventFocusOnPress` but while looking in code confused it with another prop name.

My reasoning is that this functionality is a part of react-aria, which is supposed to be unopinionated about styling. Therefore I may control the look and feel of my components whatever I like, and for that I'd prefer standard means of css, if there are any. And for that specific reason (`:focus`, `:focus-within`) there is a reasonable browser support and ui frameworks adoption already. CSS UI frameworks' opinions differ on that topic, and some of them leave focus ring visible after mouse click, some of them not. By using one or another I expect consistent results regardless of javascript runtime technology behind.

With its default focus trapping behavior react-aria adds some unintuitive inconsistency to behavior of my styles. And by hiding `preventFocusOnPress` from types and docs the whole matter starts feeling kind of developer unfriendly.

**Comment by LFDanLu** [comment]
Is the above more about the overall useButton behavior as described in [this issue](https://github.com/adobe/react-spectrum/issues/1247) you linked? Or is it that some of the other hooks (useNumberField, etc) use `preventFocusOnPress` under the hood for their button props which makes styling inconsistent? I'm not entirely sure what issue you are running into here that `preventFocusOnPress` would help with.

**Comment by maslennikov** [comment]
The issue I'm running into is that using `useButton` on an html element with applied valid css styles for styling focus behavior (`:focus`, `:focus-within`) breaks this styling by adding JavaScript-controlled focus trap on press forcing `:focus` styles to be applied. 

It takes using undocumented prop `preventFocusOnPress` to revert this focus trapping and reach default browser look and feel.

I find this design decision confusing and suggest at least to document it and provide proper types for the hidden props.

**Comment by LFDanLu** [comment]
Apologies, I don't think I still quite understand the exact issue that `preventFocusOnPress` is resolving here. If you apply `preventFocusOnPress` it will stop focus from being moved to the button on mouse click/touch/etc which is different from how native buttons behave. As you can see in this [sandbox](https://codesandbox.io/s/happy-phoebe-7wtgxk?file=/src/App.js), the focus style doesn't get applied at all on the button with `preventFocusOnPress` applied on it, unlike the native button and the button without `preventFocusOnPress` applied. Is this the desired behavior you are mentioning? Could you provide a codesandbox showing the exact issue `useButton` is causing here?

If this is more of an issue with trying to get a focus ring not to appear on press instead, `useFocusRing` is probably the way to go due to inconsistent browser handling as mentioned in [this issue's thread](https://github.com/adobe/react-spectrum/issues/1247#issuecomment-725484609).

**Comment by maslennikov** [comment]
@LFDanLu [I've made a sandbox](https://codesandbox.io/s/dank-field-ly2mv5), and now I feel funny because on all recent versions of chrome, firefox, and safari (all on mac) with vanilla example from `useButton` page I see exactly the behavior I was trying to achieve earlier by applying `preventFocusOnPress`. Now I'm not sure what caused it earlier (inconsistent browser support of `focus-visible` or something's changed in `useButton`) but it seems that my primary use-case for this prop is now not necessary and I was just dragging it over and over again from project to project.

**Comment by hejtmii** [comment]
Hi, we just came by this (undocumented) property via reverse engineering the code after using `useButton` and I wanted to share our scenario with you. Just for the record and maybe so someone reconsiders it being publicly documented (maybe with a warning not to overuse it)...

Our case is **rich text editor toolbar**. The editor is based on `contenteditable`, and while it needs to keep the focus (caret or selection) within the text, there is a toolbar with buttons that you can use to apply or insert various things.

![image](https://github.com/user-attachments/assets/571d666d-c6b8-4108-9a6b-564cf0037658)

Upon click to the toolbar button, we need to trigger the action while **keeping the DOM selection and focus in its original place**.

We have a library of components, one of which is this type of button, and we applied `useButton` to it to achieve proper accessibility in the rest of the app. But it stopped working in the RTE toolbar because it effectively steals focus from the `contenteditable` which subsequently hides the toolbar.

Setting `preventFocusOnPress: true` makes it act normally (as we need it).

We are still exploring how to handle accesibility in these RTE toolbars or whether they should display via keyboard navigation at all. For now we are happy with not having accesibility (focus ring and other stuff) in RTE toolbars so `useButton` with this extra options seems working fine for us.

I am just a bit concerned if we can rely on using undocumented feature in regards to long-term maintenance of our app. Can we? If it gets removed later, would it be considered a breaking change (major version and listed in changes)?

**Comment by snowystinger** [comment]
We'd like to officially support it, see https://github.com/adobe/react-spectrum/issues/6533
You are fine to use it for a case like this.
