### ISSUE TITLE
ButtonGroup checkForOverflow causes component flickering 

### ISSUE THREAD

**Issue by kzhangg** [adobe/react-spectrum#4769]
# 🐛 Bug Report 

When using AlertDialog + ButtonGroup component, buttons within ButtonGroup are flickering (altering between horizontal and vertical orientation) when getting limited on space.

## 🤔 Expected Behavior

Buttons within ButtonGroup should be in either horizontal or vertical orientation -- when limited on space it switches to vertical orientation.

## 😯 Current Behavior

There is some window of browser dimension that it temporarily stops, but then resumes:

## 💁 Possible Solution

Investigate resize observer / overflow check in ButtonGroup: https://github.com/adobe/react-spectrum/blob/8c9d3bdc279568e76e406adc924607c04d796009/packages/%40react-spectrum/buttongroup/src/ButtonGroup.tsx#L43C1-L84

## 🔦 Context
Component is currently being used in unified checkout when a user chooses to switch countries when entering credit card payment information

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |  
| Browser          |
| Operating System |

## 🧢 Your Company/Team

Adobe Commerce

**Comment by reidbarber** [comment]
I noticed this happens in React 16 and 17, but not 18, so that may be indicative of something (i.e. automatic batching). Looks similar to some issues we had with a TagGroup container resizing. Maybe introducing `flushSync` could be a potential fix, but I forget if there were side effects with that.

https://github.com/adobe/react-spectrum/blob/8c9d3bdc279568e76e406adc924607c04d796009/packages/%40react-spectrum/buttongroup/src/ButtonGroup.tsx#L43-L84

**Comment by kzhangg** [comment]
I tried reproducing in sandbox, but was unable to recreate it -- which seems expected since the sandbox is in React 18

**Comment by rkantor7** [comment]
This issue can be replicated on the RSP docs website https://react-spectrum.adobe.com/react-spectrum/ButtonGroup.html. Use 150% zoom and resize the page until it occurs.

https://github.com/adobe/react-spectrum/assets/142634044/72b5fb22-591e-4245-8081-5874025cc95a
