### ISSUE TITLE
RAC Select RenderProps prevents Popover from rendering

### ISSUE THREAD

**Issue by binaryartifex** [adobe/react-spectrum#4888]
### Provide a general summary of the issue here

when using the Select renderprops "isOpen" variable to manually control the appearance of the popover (use case -> framer motions AnimatePresence requires this to effectively handle its child components animation lifecycle, the popover in this instance), the popover looses all functionality. 

### 🤔 Expected Behavior?

The popover should work with or without the option of using the Select fields renderprops to conditionally control the state of its children. 

### 😯 Current Behavior

At first i thought it was the AnimatePresence blocking the rendering, however it appears that attempting to conditionally control the render state of the popover prevents it from being rendered at all.

### 💁 Possible Solution

Without looking at the underlying code i suspect a ref or id is attempting to be passed to a popover wrapper component on initial render, and with a predicate in the form of Selects isOpen prop preventing it from being passed, it can never be controlled.

### 🖥️ Steps to Reproduce

codesandbox available [here](https://codesandbox.io/s/patient-surf-c6t4h6?file=/src/App.js)

This sandbox has popover wrapped in an animate presence as it was going to be my initial bug submission, however if you remove any semblance of framer motion and your just left with the isOpen predicate, you can see that

a. the popover doesn't appear and
b. the predicate state being rendered in the button stays false. 

### Version

3.25.1

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

Windows 11

**Comment by binaryartifex** [comment]
so it helps if you scroll down to the 'controlled open state' part of the docs. onOpenChange and isOpen has to be set with whatever top level controlling state you have, ie. `const [isOpen, onOpenChange] = useState(false);`. which has to be passed to both Select and Popover, then everything seems to work and AnimatePresence works again. although with the animate render props on damn near everything im starting to reconsider a third party animation library...

**Comment by binaryartifex** [comment]
For some reason this doesnt work anymore either. if someones actually got a working popover using framer motion id love to see it.

https://codesandbox.io/s/confident-sanne-y5tm8j?file=/src/App.js

**Comment by devongovett** [comment]
I think this is because `AnimatePresence` prevents the popover/listbox from rendering at all, and therefore the `Select` has no items. That causes it to never open. https://github.com/adobe/react-spectrum/blob/403ec27bf8f5af6e19529b78782526f680c171ca/packages/%40react-stately/select/src/useSelectState.ts#L61-L64

Not sure what to do about this TBH. We rely on the listbox rendering even when the popover is not open to collect the items. That way the user can use the left/right arrow keys, or type ahead to select an item even when the popover is not open as well.

ListBox is aware that it is hidden via a context and does not render anything to the DOM, but the render function still needs to run so that the child items get registered with the Select. https://github.com/adobe/react-spectrum/blob/403ec27bf8f5af6e19529b78782526f680c171ca/packages/react-aria-components/src/ListBox.tsx#L96

Somehow we'd need Framer Motion to do the same thing.

**Comment by devongovett** [comment]
In #5358 I added some new props that should make this possible in a different way, without needing AnimatePresence. See the updated [example in the docs](https://react-spectrum.adobe.com/react-aria/styling.html#framer-motion).
