### ISSUE TITLE
Using `autoFocus` in a Dialog causes the page to scroll to the bottom

### ISSUE THREAD

**Issue by polc** [adobe/react-spectrum#4898]
### Provide a general summary of the issue here

Example : 

```jsx
<DialogTrigger>
  <Button>Click me!</Button>

  <Popover>
    <Dialog className="p-4 bg-blue-400">
      <input autoFocus={true} />
    </Dialog>
  </Popover>
</DialogTrigger>
```

### 🤔 Expected Behavior?

The input is automatically focused when opening the dialog.

### 😯 Current Behavior

The dialog is hidden by a scroll to the bottom of the page.

### 🖥️ Steps to Reproduce

https://codesandbox.io/s/practical-aryabhata-4r2q28?file=/src/App.tsx

### Version

`react-aria`: 3.27
`react-aria-components`: 1.0,0-alpha.6

### What browsers are you seeing the problem on?

Chrome

**Comment by devongovett** [comment]
Native `autoFocus` runs really early, before even React `useLayoutEffect` fires. Therefore the popover will not have positioned itself yet, and will be at the end of the document due to the portal. Not sure there is a good way around that other than not using `autoFocus` and instead calling `focus()` manually with a ref.

**Comment by polc** [comment]
That works for me, thanks @devongovett !
