### ISSUE TITLE
Popover crashes whole page if a DOM node already removed

### ISSUE THREAD

**Issue by edzis** [adobe/react-spectrum#4899]
### Provide a general summary of the issue here

The whole page crashes with:
NotFoundError
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### 🤔 Expected Behavior?

Popover closes without errors even if some nodes have been removed by some other code.

### 😯 Current Behavior

When I close the Popover after a single dom none is missing the page crashes.

### 💁 Possible Solution

Check if node is still a child of the expected parent.

### 🔦 Context

I am using Popover in an app that has a need to remove DOM nodes added by some leaky 3rd party components. Now I have taught it to ignore the nodes created by these Popovers, but would like more resilience and an easier way to detect what not to clean up.

Currently leaving these nodes untouched:
```
        node.dataset?.[SKIP_CLEANUP] === ADDED_BY_PORTAL ||
        node.dataset?.focusScopeStart === 'true' ||
        node.dataset?.focusScopeEnd === 'true' ||
        (node.style?.position === 'fixed' && node.style?.inset === '0px')
```

### 🖥️ Steps to Reproduce

https://codesandbox.io/s/elated-sinoussi-7kh2jh?file=/src/App.js:297-378

### Version

 "react-aria-components": "^1.0.0-alpha.6"

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

MacOS

**Comment by LFDanLu** [comment]
I don't believe this is something we can handle on our end, it seems to be a known issue in React that can arise when you mutate the DOM directly as discussed in this [issue](https://github.com/facebook/react/issues/11538#issuecomment-417504600). We aren't the ones calling `removeChild` here, I believe this is simply triggering because the Popover itself is unmounting and React is performing cleanup.

**Comment by edzis** [comment]
@LFDanLu Thanks for the update!
But could you still consider marking the DOM nodes you are adding to `body` with some attributes that would allow for more explicit selection than what I had to use (as described in the "Context" section)?

**Comment by LFDanLu** [comment]
Could you expand a little bit on what nodes exactly you are looking to remove? I see you mention that they come from 3rd party libraries, is it hard/impossible to target those introduces node directly? I'm just concerned that it feels you are creating a whitelist of nodes that shouldn't be removed which feels hard to maintain on both of our ends (we'd have to always to remember to add the custom attributes to any nodes we add to the body + you'd have to ask other 3rd party libraries to do the same)

**Comment by edzis** [comment]
To give more context - I manage a shell where other micro-applications are launched and closed. Even though they are running inside specific nested elements and we have a shutdown process, some of their implementation leaks as new nodes in head and body. I need to clean up if they haven't done that during shutdown.

I can not expect those applications to be updated to communicate ownership of their nodes. Tracking what I create sounds much more manageable.

From my perspective the perfect solution would allow me to add custom attributes to these nodes created by Popover:
<img width="456" alt="Screenshot 2023-08-18 at 14 00 49" src="https://github.com/adobe/react-spectrum/assets/163636/af896632-b7c2-455d-9099-61ee10066948">
See how I am already adding `data-skip-cleanup="added-by-portal"`.

**Comment by snowystinger** [comment]
I still don't quite follow why asking us to change is any different than asking these other 3rd parties which are "leaking nodes" (aka, have bugs). I'm not saying they should communicate ownership, I'm saying they should finish their cleanup.

Could you load these 3rd party micro applications into an iframe instead so they don't pollute your main app?

I'm ok considering adding some sort of attribute to the portal root. Would it be ok to add an attribute to them ourselves, and not require a new prop to customize it?
Another tack you could take is keeping nodes that aren't aria-hidden. When we have a popover open, we aria-hide everything else.

I also noticed that you are putting a class on the portal, `unifi-portal-un0eju`, I'm assuming you have access to that before CSS modules, so you know the transformation. You could target that instead of the data-attribute.

**Comment by edzis** [comment]
- changing functionality of the legacy versions of these micro applications is close to impossible
- I have `unifi-portal-*****` and data-skip-cleanup="******" on the only node that I can control - I would like to gain the ability to add attributes or classnames to the other nodes you are creating for the popovers
- skipping `aria-hidden="true" would be too generic - if I can't get custom attributes I'd rather stick to my current selectors

**Comment by LFDanLu** [comment]
The team talked about this today and we'll want to eventually support https://github.com/adobe/react-spectrum/issues/4404 which should allow you to have more fine grain control over what nodes to exclude from your cleanup (aka: you could make your own div in which the Popover would render and attach a data attribute to that).
