### ISSUE TITLE
RAC FileTrigger should accept the same file twice

### ISSUE THREAD

**Issue by MarekBodingerBA** [adobe/react-spectrum#4925]
### Provide a general summary of the issue here

FileTrigger in React Aria Components uses the native input which is hidden by the user. If the native input contains the value of some file, it is not possible to upload the same file again.

### 🤔 Expected Behavior?

It should be possible to upload the same file twice in a row.

### 😯 Current Behavior

After uploading a file, it is not possible to upload the same fail again right after.

### 💁 Possible Solution

As a temporary fix, we clear the `value` of the input after each change.
https://github.com/bratislava/konto.bratislava.sk/blob/7206955eb4f809bcac4b4b6758070dcfc7309821/next/components/forms/widget-components/Upload/UploadButton.tsx#L70

It might be also possible to clear if before [triggering click event](https://github.com/adobe/react-spectrum/blob/09a258f098147f7e67a0430b593b08168220ec4a/packages/react-aria-components/src/FileTrigger.tsx#L50C38-L50C38) on the input.

I am not sure if it is possible to do that on library scale, but as the input is hidden, and the only time the file reference is accessed is `onChange`, it may be safe to do so. Maybe as an optional prop.

### 🖥️ Steps to Reproduce

https://codesandbox.io/s/proud-moon-mvq7qz

1. Upload "file1.txt".
2. See console.
3. Upload "file1.txt".
4. See that console only contains one log.

### Version

react-aria-components@1.0.0-alpha.6

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

Windows

**Comment by snowystinger** [comment]
Hey, thanks for the issue. I took a look and it works the same way with a native input https://codesandbox.io/s/adoring-rui-gzp2gc

I think setting the value to null when you're done processing it is fine, though I'd give the user some indication that you've successfully done something with the file, otherwise it might look like it just disappeared.

It might be helpful to display the name of the chosen file.

Finally, this is only an input, so you can select a file. I'd consider separating the upload to a separate button, something along the lines of "Upload chosen file" vs the input's button "Choose file".

**Comment by LFDanLu** [comment]
We'll want to get rid of onChange and instead offer onSelect that will fire everytime your select a file via FileTrigger.

**Comment by MarekBodingerBA** [comment]
Thank you.
