### ISSUE TITLE
RAC: improving import structure for dx

### ISSUE THREAD

**Issue by eckoln** [adobe/react-spectrum#4944]
Current import structure makes it hard to understand code and build custom component. I suggest to support uses like `Tabs.TabList`, like [Headless UI](https://headlessui.com/) does.

The current import structure is unnecessarily long and complicated. For example:
```js
// your-tabs.jsx
import {
  Tabs as TabsPrimitive,
  TabList as TabListPrimitive,
  Tab as TabPrimitive,
  TabPanel as TabPanelPrimitive,
} from "react-aria-components";

<TabsPrimitive>
  <TabListPrimitive>
    <TabPrimitive />
  </TabListPrimitive>
  <TabPanelPrimitive />
</TabsPrimitive>
```

I suggest to make the import structure simpler and more readable:
```js
// your-tabs.jsx
import { Tabs as TabsPrimitive } from "react-aria-components";

<TabsPrimitive.Tabs>
  <TabsPrimitive.Tablist>
    <TabsPrimitive.Tab />
  </TabsPrimitive.Tablist>
  <TabsPrimitive.TabPanel />
</TabsPrimitive.Tabs>
```

**Comment by devongovett** [comment]
Why rename all the imports with as? Why not

```js
import {Tabs, TabList, Tab, TabPanel} from "react-aria-components";

<Tabs>
  <TabList>
    <Tab />
  </TabList>
  <TabPanel />
</Tabs>
```

Or if you want a namespace for some reason

```js
import * as RAC from "react-aria-components";

<RAC.Tabs>
  <RAC.TabList>
    <RAC.Tab />
  </RAC.TabList>
  <RAC.TabPanel />
</RAC.Tabs>
```

**Comment by eckoln** [comment]
When i create my reusable components, i using the same names in same file. For example, you can't use it like this:

```js
import { Tabs, TabList, ... } from "react-aria-components";

const Tabs = ({ ...props }) => {
    return <Tabs className="..." {...props} />
}

const TabList = ({ ...props }) => {
    return <TabList className="..." {...props} />
}

export { Tabs, Tabslist, ... }
```

So, if i import like this (`import * as RAC from "react-aria-components"`), won't it affect the bundle size?

**Comment by eckoln** [comment]
> 

When i create my reusable components, i using the same names in same file. For example, you can't use it like this:

```js
import { Tabs, TabList, ... } from "react-aria-components";

const Tabs = ({ ...props }) => {
    return <Tabs className="..." {...props} />
}

const TabList = ({ ...props }) => {
    return <TabList className="..." {...props} />
}

export { Tabs, Tabslist, ... }
```

So, if i import like this (`import * as RAC from "react-aria-components"`), won't it affect the bundle size?

**Comment by devongovett** [comment]
No it should not affect bundle size. All bundlers I know of are able to tree shake namespace imports like that just as they can for named imports.

One reason we don't attach all the sub components to a Tabs namespace like that is actually so the individual components can be tree shaken. Perhaps not for Tabs, but in other components some of the children are optional and if they were all attached as properties to the root component they wouldn't be able to be tree shaken. You can also replace any component with your own implementation using hooks if you need to do something super custom, so that's another case where the default implementation should be tree shaken.

Additionally, in React Aria Components, many of the "child" elements are reusable independently. For example ListBox and Popover are used within both ComboBox and Select, and can also be used on their own. It wouldn't make sense to tie them to a specific parent component.

Personally I don't think it's a huge burden to either rename the components when you import them if there is a conflict (you can do something shorter than `TabPrimitive` too, eg `RATab`), or use a namespace import like I showed above. Then we preserve tree shakeability and make it clear that most components can be used independently.
