### ISSUE TITLE
Ability to properly clear value in useDateRangePickerState

### ISSUE THREAD

**Issue by Refrase** [adobe/react-spectrum#4986]
### Provide a general summary of the feature here

We're implementing a custom `DateRangePicker` with all related hooks incl. `useDateRangePickerState`.

It seems to be hard to clear the state in a good way.

What we have done for our `DatePicker` is already a little hacky, as we repeatedly call `fieldState.clearSegment` for each segment.

It's not possible to do it like this when having to call `clearSegment` for both `startFieldState` and `endFieldState` though, as the `value`, used when `clearSegment` via `setDateTime` sets the `useDateRangePickerState` `value`, is stale.

Meaning that when running `endFieldState.clearSegment` it will set the `{ start: ... }` part back to the last selected value, because `endFieldState.clearSegment` is not aware that it has just been reset by `startFieldState.clearSegment`.

We could of course just do `dateRangePickerState.setValue({ start: null!, end: null! })` (though null is not accepted by TS).
But `clearSegment` is doing other useful stuff like saving last selected `value` to be used for a re-selection.

What we've found would work is if the `value` was saved as a `ref` (which [you've done before](https://github.com/adobe/react-spectrum/pull/2510/commits/ca696af45e1f4548e1ace06e5de6d4f297f46eeb?diff=split&w=0#diff-eb983dc43959711e7dea6f33bcbbe97aa0bab850f24441753cdbd885125f3b71R50-R51)) for the latest state to be used in `endFieldState.clearSegment` call:
```typescript
  // useDateRangePickerState.ts

  let value = controlledValue || placeholderValue;
  let valueRef = useRef(value);
  valueRef.current = value;

  let setValue = (value: DateRange) => {
    valueRef.current = value;
    ...
  }

  setDateTime(part, dateTime) {
    setValue({ ...valueRef.current, [part]: dateTime });
  },
```

But even better if a new method like `clearAllSegments` would be made available to avoid the repeated calls as well.

Are we overlooking something? Is there another way to achieve this clearing properly?
 

### 🤔 Expected Behavior?

Calling `startFieldState.clearSegment` then `endFieldState.clearSegment` should fully clear value of `useDateRangePickerState`.

### 😯 Current Behavior

Calling `startFieldState.clearSegment` then `endFieldState.clearSegment` sets start-part of `value` of `useDateRangePickerState` back to last selected value.

### 💁 Possible Solution

```typescript 
  // useDateRangePickerState.ts

  let value = controlledValue || placeholderValue;
  let valueRef = useRef(value);
  valueRef.current = value;

  let setValue = (value: DateRange) => {
    valueRef.current = value;
    ...
  }

  setDateTime(part, dateTime) {
    setValue({ ...valueRef.current, [part]: dateTime });
  },
```

Even better if a new method like `clearAllSegments` would be made available to avoid the repeated calls as well.

### 🔦 Context

This is how we work around it to both make clearSegment do the extra stuff it does (even though only taking effect for the end field) and also end up with a fully cleared state value:
```typescript
  const clearFields = () => {
    segmentTypes.forEach((segmentType) => {
      startFieldState.clearSegment(segmentType)
      endFieldState.clearSegment(segmentType)
    });
    
    dateRangePickerState.setValue({ start: null!, end: null! });
  };
```

**Comment by LFDanLu** [comment]
Mind providing a codesandbox or a codesnippet showing your DateRangePicker? My understanding is that calling `clearSegment` of either of the fieldStates should only affect the value tracked for that fieldState since the value passed to each `useDateFieldState` is the start or end field's respectively. I could be wrong here, haven't looked at the date hooks in depth for a while.

Calling `dateRangePickerState.setValue({ start: null!, end: null! });` should be fine and in general is our usual approach for clearing the value for many of our fields, the TS issue you are running into there is because we haven't fully converted to [support TS strict](https://github.com/adobe/react-spectrum/issues/3183) yet, but I am surprised that it wasn't covered as part of https://github.com/adobe/react-spectrum/pull/4225. What version of the datepicker package are you on?

**Comment by Refrase** [comment]
We're using datepicker version 3.5.0. 
[#4225](https://github.com/adobe/react-spectrum/pull/4225) seems to be released with 3.4.0 if I'm not mistaken.

Here's a sandbox that resembles our setup (but with Spectrum components). 
See the comment in code under `clearFields` function:
[![Edit busy-lederberg-kkczgc](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/busy-lederberg-kkczgc?fontsize=14&hidenavigation=1&theme=dark)

**Comment by devongovett** [comment]
I think my PR #5052 should fix this. You'll be able to call `state.setValue(null)`.

**Comment by LFDanLu** [comment]
@devongovett what do you think about expanding `props.placeholderValue` so that it supports a separate `start` and `end` value? I believe @Refrase wants to also save the last set date value as the new placeholder but at the moment `props.placeholderValue` only supports a DateValue so they would only be able to use either the `start` or `end` as the new placeholder value upon clearing the field.
