### ISSUE TITLE
Click/Tap not working properly with buttons on RAC

### ISSUE THREAD

**Issue by eashish93** [adobe/react-spectrum#5000]
### Provide a general summary of the issue here

On mobile view, when you click/tap any RAC button while your mouse/finger is halfway on it, it's not clickable. I created a video demo for the problem. 

https://github.com/adobe/react-spectrum/assets/13780952/9def5be4-fcf8-4d7c-a161-a58809a35b1b

### 🤔 Expected Behavior?

It should be clickable from anywhere. Normal buttons are working fine. 

### 😯 Current Behavior

Described above.

### 🖥️ Steps to Reproduce

Can be reproduce via video demo. For reference: 
- Open this page: https://react-spectrum.adobe.com/react-aria/Button.html
- Open dev console and switch to mobile view.
- Now try clicking on any button with only just 15-20% of overlap of your mouse on button. It will only work, when mouse overlap is more than 50%. 

### Version

adobe/react-spectrum@3.29.0 (Aug 2023 release)

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

Mac OS

**Comment by reidbarber** [comment]
This is due to the pointer event's 1px x 1px rect not overlapping the button's rect.

https://github.com/adobe/react-spectrum/blob/30f172864ab9170d9be9cd317ed4d74ffdec2341/packages/%40react-aria/interactions/src/usePress.ts#L439-L445

I think this is expected behavior. There is no radiusX/radiusY associated with those events in Chrome's Device Mode.

**Comment by eashish93** [comment]
Ok. I just tried without chrome dev tools, so it's working fine.
