### ISSUE TITLE
RAC: Multi select with Shift is not working in Virtualized GridList  

### ISSUE THREAD

**Issue by piecyk** [adobe/react-spectrum#5067]
### Provide a general summary of the issue here

When testing GridList with virtualization library like `@tanstack/react-virtual` kinda looks like it works 🎉  

One issue noticed, when using selectionBehavior `replace` and selecting multi rows with Shift. If we select item from current render items then it works, issue is when selecting one and scroll down a bit to new rendered items, then it breaks, item is focused but no selection.

https://github.com/adobe/react-spectrum/assets/82964/6472cbf9-6cc3-4b11-bd00-c19339c19d5f

Also when scrolling focus is changing, is there some autofocus enabled?

### 🤔 Expected Behavior?

Items should be selected.

### 😯 Current Behavior

Items are not selected and row is focused.

### 🖥️ Steps to Reproduce

https://codesandbox.io/s/friendly-tamas-3zpl6q?file=/src/App.js

### Version

1.0.0-beta.0

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

MacOS

**Comment by devongovett** [comment]
Virtualization is not going to work with the current component implementation. GridList must know about all of the items in order to implement selection, but you are only passing a subset of the items in. That's why shift select doesn't work: by the time you scroll down, you've removed many of the previously visible items from the GridList entirely so it cannot determine what the ids of the items in-between were.

For virtualization to work correctly, it would need to be implemented _inside_ the GridList rather than outside. You could do this by dropping down to the [useGridList](https://react-spectrum.adobe.com/react-aria/useGridList.html) hook API instead of using the component. Eventually we may add support for virtualization to the components too but it's not on our short term roadmap.

**Comment by devongovett** [comment]
Without selection some features would still be broken. For example, if you use the Home and End keys to navigate to the first/last row, it would only take you to the currently visible rows not the complete set of items.

**Comment by piecyk** [comment]
ehh got stuck a bit here, was reading aria Virtualizer impl and noticed that focused item should be preserved, done that, but still something is not right when trying to reorder items, was trying to add virtualization to simple example https://react-spectrum.adobe.com/react-aria/useDraggableCollection.html#reordering

https://codesandbox.io/s/reorderablelistbox-tanstack-react-virtual-5245lz?file=/src/App.tsx
