### ISSUE TITLE
[RAC] Add `placeholder` prop support to `ComboBox` component

### ISSUE THREAD

**Issue by clemensheithecker** [adobe/react-spectrum#5100]
### Provide a general summary of the feature here

Add support for a `placeholder` prop in the `ComboBox` component, similar to the `Select` component.

### 🤔 Expected Behavior?

When no item is selected in the `ComboBox`, it should optionally display a placeholder text (e.g., "Select an item" or "Type to select an item"). This placeholder should be customizable via a `placeholder` prop.

### 😯 Current Behavior

Currently, the `ComboBox` component does not support a `placeholder` prop. The input is empty when no item is selected.

### 💁 Possible Solution

The `Select` component supports a placeholder by using the `SelectValue` component to render the current value or a placeholder if no value is selected. A similar approach can be adapted for the `ComboBox` component:

1. Check if there's a selected item in the `ComboBox`.
2. If not, render the provided placeholder.

### 🔦 Context

The `useComboBox` hook from React Aria already supports the `placeholder`. This indicates that the underlying logic is in place, but it hasn't been surfaced at the React Aria Components level in `ComboBox`.

In applications where users interact with the ComboBox component, having a placeholder provides a clearer call to action and enhances user experience. The absence of a placeholder in the ComboBox component can lead to ambiguity for users who might not be familiar with the component's functionality.

### 💻 Examples

```tsx
<ComboBox placeholder="Type to select an item">
  {/* ...items... */}
</ComboBox>
```

When no item is selected, the input should display "Type to select an item".

**Comment by snowystinger** [comment]
You can do this with the `Input` element https://codesandbox.io/s/musing-cache-3ntmpc?file=/src/App.js

We do discourage the usage of `placeholders` in Spectrum as they are not very accessible; see https://spectrum.adobe.com/page/text-field/#Don%E2%80%99t-use-placeholder-text

**Comment by emlai** [comment]
This seems to be working now: https://codesandbox.io/s/bitter-morning-nchy6t?file=/src/App.js

**Comment by snowystinger** [comment]
Great, I'll close this out then. Thanks!

**Comment by clemensheithecker** [comment]
I would like to reopen this issue due to an unresolved TypeScript definition problem. While the `placeholder` prop works in runtime, it is missing from the `ComboBoxProps<T>` TypeScript interface, causing type errors in TS projects. This was not apparent in the JavaScript example shared.

Here's a [CodeSandBox](https://codesandbox.io/s/competent-voice-mjtz4l?file=/src/App.tsx) (React Aria Components 1.0.0-beta.2) demonstrating the issue. Can we update the TypeScript definitions to include `placeholder`? For context, the `SelectProps` type already includes `placeholder`.

**Comment by devongovett** [comment]
As rob mentioned before, you can put placeholder on the `Input` element rather than the top level `ComboBox`. Looks like this is the case for all of our textfield-like components.

**Comment by danmichaelo** [comment]
> We do discourage the usage of `placeholders` in Spectrum as they are not very accessible; see https://spectrum.adobe.com/page/text-field/#Don%E2%80%99t-use-placeholder-text

The guide seems to discourage use of placeholders for instructions, which I agree with. But a placeholder for a ComboBox can also be used to communicate that no value has been selected. It therefore seems a bit odd to not support placeholders altogether officially (i.e. not mentioning them in [the ComboBox documentation](https://react-spectrum.adobe.com/react-aria/ComboBox.html)). The workarounds seems to work however.

**Comment by snowystinger** [comment]
The guide you're looking at is specific to the Spectrum implementation. It was either too dim or looked like a value itself, for example, if the placeholder was "Empty", is that saying there is no value selected, or is there an option which is called "Empty" (next to "Full" for example). Placeholders are coming back in the updated Spectrum 2, [feat: Support placeholders in S2 components](https://github.com/adobe/react-spectrum/pull/8692/files#top), it's still a grey area. Having and not having them, neither is really great.

If you require a value though, it's recommended to use isRequired with a visual indication and form validation with a description/error message so users know what is required and what state the field is in.

If you're using React Aria Components, you can put the placeholder on the Input. It's a little different than Select because Select doesn't have a text input in it so there is no native place for a placeholder. So it supports the prop at the top level. Will bring up with the team if we want to revisit this, but for now, I think it's fine.
