### ISSUE TITLE
Table throws error unless first Column has isRowHeader (Remix 1.19.3)

### ISSUE THREAD

**Issue by njackson** [adobe/react-spectrum#5140]
### Provide a general summary of the issue here

The `Table` component throws the following error if the first Column does not have isRowHeader=true:
`Error: A table must have at least one Column with the isRowHeader prop set to true`

### 🤔 Expected Behavior?

It should be possible to render a Table without the first Column having isRowHeader=true in a Remix app if another column has it set.

### 😯 Current Behavior

In Remix 1.19.3, the `Table` component throws an error if the first Column doesn't have isRowHeader=true. It doesn't matter if any other Column has the value set, we still get the error.

In a vanilla React app, it seems to render without error.

### 🖥️ Steps to Reproduce

```
<Table>
  <TableHeader>
    <Column>Header 1</Column>
    <Column isRowHeader>Header 2</Column>
  </TableHeader>
  <TableBody>
    <Row>
      <Cell>Cell 1</Cell>
      <Cell>Cell 2</Cell>
    </Row>
  </TableBody>
</Table>
```

It appears to work fine with a simple React app: https://codesandbox.io/s/heuristic-cray-4xtwdk

But in Remix the error is thrown unless the first Column has isRowHeader=true, regardless of whether any other Columns have it set: https://codesandbox.io/p/sandbox/xenodochial-leaf-9xkgm8

### Version

react-aria 3.26.0 / react-aria-components 1.0.0-beta.0

**Comment by snowystinger** [comment]
Remix appears to be updating the table over and over, once per column. It calls that function updateColumns first with no columns, then with 1, then with 2, then with 3 and so on. In a regular react app, it only gets called once with the complete set.
I don't know enough about Remix to know why that happens. I assume it has something to do with the SSR nature of Remix combined with our portalling of collections in order to build our collections, but I don't have enough knowledge yet. @reidbarber have you run into this in Nextjs or anything?
