### ISSUE TITLE
React Aria Components - Popover adding unnecessary offset when used with animation

### ISSUE THREAD

**Issue by deebov** [adobe/react-spectrum#5195]
### Provide a general summary of the issue here

As you can see in [the codesandbox](https://codesandbox.io/s/determined-dust-gx53rd?file=/src/styles.css) the popover is adding unnecessary offset. However, after you resize the window it get into the correct position without the offset. (You have to enable "Emulate a focused page" in the deb tools so that the popover does not hide when you resize).

https://github.com/adobe/react-spectrum/assets/28673719/6c5d6d4e-abe9-4334-8d03-8244b0b3a38d

### 🤔 Expected Behavior?

The popover's edge should be the same as the trigger's respective to the placement (left, right, top, bottom, center).

### 😯 Current Behavior

The popover renders with a small offset.

### 🖥️ Steps to Reproduce

1. Go to https://codesandbox.io/s/determined-dust-gx53rd?file=/src/styles.css
2. Click the button
3. And you should see that the popover is rendered with an offset.

### Version

1.0.0-beta.0

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

macOS

**Comment by snowystinger** [comment]
Looks like transform animations such as scale don't trigger resize observers. I'm not entirely sure what we can do about this. We wouldn't just wait for the animation to end and check again, that'd result in a jarring jump from the wrong position to the correct one.

We could set 'right' instead of 'left' when positioned 'bottom right', but that wouldn't solve the problem for centered elements.

You could create a wrapper element that is already the "correct" size, then transform the contents of it. I know that's less ideal.

We could check for an animation and then use raf polling to adjust the position each frame, that might keep it in the right spot in relation to the trigger while the animation is happening.

open to other ideas

**Comment by deebov** [comment]
Hey @snowystinger! Thanks for the quick reply and the suggestion.

I've successfully applied your suggestion and it works as expected. So I'll be closing this issue for now.
