### ISSUE TITLE
Tooltip is not triggered on hover over an ActionButton that has isDisabled state changed from true to false

### ISSUE THREAD

**Issue by zhengaoran** [adobe/react-spectrum#5199]
### Provide a general summary of the issue here

After tooltip is warmed up, hover over an ActionButton does not trigger the tooltip if it has a recent isDisabled state change from true to false.

https://github.com/adobe/react-spectrum/assets/73000688/53e155c0-94b1-40a4-a422-f78e688e44e8

### 🤔 Expected Behavior?

Tooltip should be triggered

### 😯 Current Behavior

Tooltip is not shown, have to mouse out and mouse in again to trigger the tooltip.

### 🔦 Context

Zoom In and Out Buttons. At max zoom in level, zoom in button would be disabled, and on click of zoom out button will reset isDisabled state for zoom in.

### 🖥️ Steps to Reproduce

https://codesandbox.io/s/rsp-actionbutton-tooltip-issue-tjm9xk

1. Click on button1 to disable itself
2. Hover over button2 and wait for tooltip to be displayed (warm up)
3. Click on button2 to enable button1 again.
4. Hover over button1, and tooltip is not get triggered

### Version

3.18.0

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

Mac OS

**Comment by LFDanLu** [comment]
This issue happens because the disabled state is set directly on the ActionButton and thus `useTooltipTrigger`'s [isDisabled](https://github.com/adobe/react-spectrum/blob/dd2d59863a219503b5a3836eab319fe96e99fe86/packages/%40react-aria/tooltip/src/useTooltipTrigger.ts#L126-L130) doesn't actually change, resulting in useHover not calling [triggerHoverEnd](https://github.com/adobe/react-spectrum/blob/dd2d59863a219503b5a3836eab319fe96e99fe86/packages/%40react-aria/interactions/src/useHover.ts#L193-L198) and thus the tooltip trigger thinks it is still hovered until a full hover enter -> hover leave is performed on the non disabled trigger. A workaround you could do is also pass `isDisabled` to Tooltip trigger [like so](https://codesandbox.io/s/rsp-actionbutton-tooltip-issue-forked-6k8znn) but we can  potentially look to improve this in `useTooltipTrigger` by disabling hover on press start maybe

**Comment by LFDanLu** [comment]
closing for now since this has a workaround
