### ISSUE TITLE
inputProps.required is undefined when isRequired = true is passed to useTextField

### ISSUE THREAD

**Issue by charliearaya** [adobe/react-spectrum#5370]
### Provide a general summary of the issue here

`inputProps.required` is `undefined `when isRequired = true is passed to `useTextField`

### 🤔 Expected Behavior?

`inputProps.required` is true as well

### 😯 Current Behavior

`inputProps.required` is undefined

### 💁 Possible Solution

Should I use `aria-required` ?

### 🖥️ Steps to Reproduce

pass isRequired = true to useTextField

### Version

3.29.1

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

Windows 10, 64x

**Comment by reidbarber** [comment]
I'm not seeing that issue here for `3.29.1`: https://codesandbox.io/s/cranky-darkness-4zgkgj?file=/src/App.js

Are you able to reproduce this in a codesandbox? Also, this behavior may change in the upcoming release, so maybe check if you are using nightlies. In the upcoming release, `validationBehavior` will be factored into which gets put on the element.

https://github.com/adobe/react-spectrum/blob/0b541f48848eb43f74ae57e8b21dc4455d95040b/packages/%40react-aria/textfield/src/useTextField.ts#L168-L169

**Comment by charliearaya** [comment]
I want to use inputProps.required to show an asterisk on the label. I cant get it to work on the example either:
https://codesandbox.io/embed/nifty-davinci-njq2rp

**Comment by reidbarber** [comment]
Sorry, I had was using isReadOnly in the sandbox instead of isRequired. 

What gets included in `inputProps` is an implementation detail that could change, so I would recommend just relying on `props.isRequired` to render your asterisk. This is what we do in for our fields in React Spectrum.

**Comment by reidbarber** [comment]
Going to close this, but feel free to include any follow-up questions or discussions here!
