### ISSUE TITLE
RAC Menu - put onClick on items

### ISSUE THREAD

**Issue by emlai** [adobe/react-spectrum#5403]
### Provide a general summary of the feature here

I want to wrap the Menu component in an API design where `onClick` is passed to the `MenuItem`s.

### 🤔 Expected Behavior?

`onClick` on `MenuItem` is called.

### 😯 Current Behavior

`onClick` on `MenuItem` is not called.

### 🔦 Context

We are implementing a menu component and want to use react-aria-components Menu in its implementation.

### 💻 Examples

How our component is to be used:
```
<Menu>
  <MenuItem onClick={...}>Foo</MenuItem>
  <MenuItem onClick={...}>Bar</MenuItem>
</Menu>
```

**Comment by reidbarber** [comment]
Menu has the `onAction` prop:

onAction | (key: Key) => void | Handler that is called when an item is selected.
-- | -- | --

You can find this under Menu -> Events: https://react-spectrum.adobe.com/react-aria/Menu.html#menu-1

All of our collection components follow this API for things like action or selection. You can probably find some more discussion in issue or discussions, including this comment: https://github.com/adobe/react-spectrum/discussions/5058#discussioncomment-6973863

**Comment by reidbarber** [comment]
None of the RAC components support an `onClick` handler, so there isn't a clean way to do this, but if this is more of a case where you need to retrofit existing legacy components, you could do something like you have there.

Two cases the snippet you provided wouldn't handle:
- supporting user-provided keys instead of just the auto-generated ones
- supporting dynamic collections. You could get access to the collections (see [Accessing state](https://react-spectrum.adobe.com/react-aria/advanced.html#accessing-state) in the advanced customization guide).

Needing to include the click event itself would make this even tougher. 

I would recommend creating a [discussion](https://github.com/adobe/react-spectrum/discussions) to see if anyone else can chime in with recommendations.
