### ISSUE TITLE
[RAC] Input component doesn't take isDisabled prop

### ISSUE THREAD

**Issue by IHIutch** [adobe/react-spectrum#5406]
### Provide a general summary of the issue here

There is no `isDisabled` prop on the `Input` component

### 🤔 Expected Behavior?

Similar to other "native" components, like `Button`, it seems like `Input` should accept `isDisabled`. I recognize that does accept a `disabled` prop, it breaks my expectations because most components use `isDisabled`. 

I'd also argue that I think the inverse is also true, that because `disabled` is a native prop, I don't expect it to work like the contrived `isDisabled`, which adds various data attributes

### 😯 Current Behavior

`isDisabled` is not supported and `disabled` is used for this component instead

### 💁 Possible Solution

To be consistent with other components, it seems like only `isDisabled` should be supported. But I certainly wouldn't mind if both `disabled` and `isDisabled` worked.

### 🔦 Context

I'm building https://draft-ui.com/, a shadcn/ui-like library for RAC, and building examples of how to customize various components. `Input` is the only component I've found so far that that uses `disabled` instead of `isDisabled`.

### 🖥️ Steps to Reproduce

https://stackblitz.com/edit/stackblitz-starters-ewhscg?file=src%2FApp.tsx

### Version

1.0.0-rc.0

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

MacOS 13.4.1

**Comment by snowystinger** [comment]
Input is really meant to be used as a child of components, such as TextField, or NumberField, etc. You can put isDisabled on those. Input shouldn't be used on its own. It accepts`InputHTMLAttributes<HTMLInputElement>`, which is why you can pass `disabled`. However, I would discourage that in favor of passing it to the overall component, which may choose what disabled means specific to that component.

This is also why Input doesn't have a standalone docs page, it's only included as a child of other components.

See https://react-spectrum.adobe.com/react-aria/TextField.html#input

**Comment by IHIutch** [comment]
Fair enough, I do note that here: https://draft-ui.com/docs/components/input. The reason I've added it to these docs, is that you can style it independently, which is why I was adding a "disabled" example.

But that's why I was surprised using `disabled` added `data-disabled="true"`. It makes sense, it just felt inconsistent.

**Comment by snowystinger** [comment]
I can definitely understand that. I've gotten it confused a few times. Label/Heading/Keyboard all work this way, and I raised it with Group as well, which is the odd one out with its own docs page. It would be hard to change now, unfortunately, mostly due to how our hooks work by returning HTMLAttributes. So I'm not sure what we could do about it.

**Comment by IHIutch** [comment]
No worries, appreciate the discussion!
