### ISSUE TITLE
Add the ability to define the width of the popover in ComboBox/AutoComplete

### ISSUE THREAD

**Issue by dannify** [adobe/react-spectrum#5430]
### Provide a general summary of the feature here

Pickers currently allow for a custom width using the `menuWidth` prop see [docs](https://react-spectrum.adobe.com/react-spectrum/Picker.html#custom-widths)

We want to allow this option in ComboBox and AutoComplete. It should always default to the width of the input, as it does now, however if the prop `menuWidth` is set, use that instead.

Note: menuWidth needs to be >= width of the input. If the prop is < the input, default to the min-width and ignore the prop.

### 🤔 Expected Behavior?

Allow the popover width to be customizable.

### 😯 Current Behavior

No option to control this

### 💁 Possible Solution

Similar to 
https://github.com/adobe/react-spectrum/blob/5dac45cf72f92048aedf730abec8626eb6094cf6/packages/%40react-spectrum/picker/src/Picker.tsx#L137-L140

### 🔦 Context

Use case of combobox and autocomplete where the content of the options needs more room to display. Truncation might not always be the right answer.

### 💻 Examples

<img width="188" alt="image" src="https://github.com/adobe/react-spectrum/assets/10407036/51f49137-4a59-423b-b3b4-b48c08fa3a64">

### 🧢 Your Company/Team

Adobe/Sign

**Comment by sookmax** [comment]
@dannify Hi! I want to take a stab at this.

By the way, just to make sure I understood everything correctly, by `AutoComplete` you mean `SearchAutocomplete` under  the pickers category in React Spectrum, right? I'm asking this because I don't see it under the pickers category in current docs, but I DO see it (tagged as alpha) when I run `yarn start:docs` on main branch.
