### ISSUE TITLE
Why isn't `SideNav` published?

### ISSUE THREAD

**Issue by vixalien** [adobe/react-spectrum#5437]
### Provide a general summary of the issue here

I've looked through the code, and it seems the code about `SideNav` is already in the codebase. However, the component itself isn't published. I'm wondering if this is a bug or an intentional omission.

### 🤔 Expected Behavior?

I would expect the `@react-spectrum/sidenav` package to be exported.

### 😯 Current Behavior

The package is not exported :(

### 🖥️ Steps to Reproduce

Try to install `@react-spectrum/sidenav`

### Version

3.32.2"

### What browsers are you seeing the problem on?

Other

### If other, please specify.

N/A

### What operating system are you using?

linux

**Comment by snowystinger** [comment]
This is intentional. We did not finish working on it due to other priorities and it's not in a publishable state. The API is not how we want it and it does not have all of its accessibility features which we deem necessary for an initial release. We've been meaning to remove it from the codebase so that it doesn't confuse people.
