### ISSUE TITLE
`TabList` is only able to render `Tab` elements

### ISSUE THREAD

**Issue by neefrehman** [adobe/react-spectrum#5468]
### Provide a general summary of the issue here

When trying to compose slightly more complex tab-based UIs, there may be reasons to nest elements inside `TabList` that aren't `Tab`s. A recent example that I've run into is loading states for tabs, when they need to be conditionally rendered based on data coming from a network request. In these cases, `TabList` renders no children at all. There also doesn't seem to be anything in the documentation about this requirement, so for now I'm considering a bug.

### 🤔 Expected Behavior?

`TabList` should render any children provided to it.

### 😯 Current Behavior

`TabList` only renders `Tab` elements

### 🔦 Context

I recently tried to implement `Tabs`, where the number of tabs depends on a network request. I had hoped to render our 
data-aware skeleton components to handle this, which could receive a loading state to be displayed until the data arrives. Unfortunately, when doing this we were unable to render the loading states or the subsequent tabs. Instead, I had to decouple the loading states and place them as a sibling of `TabList`, which is a little clunky in terms of DX.

We have also run into a situation where nesting a maximum width container under `TabList` would have enabled a better horizontal scrolling experience for the `TabPanels` for our users, though for similar reasons we were unable to achieve this.

### 🖥️ Steps to Reproduce

Minimal repro here: https://codesandbox.io/s/bold-brook-rczk7c?file=/src/App.js

### Version

react-aria-components@1.0.0-rc.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What operating system are you using?

MacOS

**Comment by devongovett** [comment]
This is expected due to accessibility limitations. The ARIA tablist role only allows elements with the tab role as children. Any other elements won't be accessible to screen readers and may interfere with focus behavior. We are planning to add development mode warnings for stuff like this in the future.

I'd suggest swapping out the tablist entirely during the loading state. If only a single tab is loading, you can put the loading indicator inside the tab instead, but keep in mind that any elements inside a tab are presentational only and won't be accessible to screen reader users. See https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tab_role#all_descendants_are_presentational

For the scrolling case, consider wrapping the tablist in another container rather than placing that inside the tablist.

**Comment by neefrehman** [comment]
@devongovett thanks for the response! I'll try and use the alternatives you suggested, and look forward to the dev mode warnings for similar scenarios.
