### ISSUE TITLE
runAfterTransition calls addEventListener/removeEventListener on a null target

### ISSUE THREAD

**Issue by VillePakarinenPosti** [adobe/react-spectrum#5563]
### Provide a general summary of the issue here

I'm using the provided hooks from the `React-Aria` in a project and ran into errors regarding `runAfterTransition` related functionality in the production error-monitoring.

> Cannot read properties of null (reading 'removeEventListener')

> Cannot read properties of null (reading 'addEventListener')

> null is not an object (evaluating 't.target.addEventListener')

The error reports varies based on the clients browser/platform but the original root-cause seems to be related to adding/removing `transitioncancel` event handler on a null-target.

https://github.com/adobe/react-spectrum/blob/414f408531c211deb68a14c57d34c43ff963c457/packages/%40react-aria/utils/src/runAfterTransition.ts#L39

https://github.com/adobe/react-spectrum/blob/414f408531c211deb68a14c57d34c43ff963c457/packages/%40react-aria/utils/src/runAfterTransition.ts#L56

### 🤔 Expected Behavior?

Event handlers gracefully handling `event.target ==='null'`

### 😯 Current Behavior

The actual root-cause for `event.target` being `null` in this scenario is unknown but the interface for `TransitionEvent` states that the target-property is either `EventTarget | null`.  Currently the possibility of `null` case is not being handled.

### 💁 Possible Solution

I was reading through the implementation of `runAfterTransition` and a naive solution would just be to skip `addEventHandler` `removeEventHandler` in case the `event.target` ends up being `null`. 

However this got me thinking about a scenario where `event.target` will be defined for the original `transitionrun` event but possibly being `null` for the `transitionend`. Could it be that the global list of elements that are currently transitioning would cause a memory leak in this scenario? Maybe `transitionsByElement` should also be a WeakMap instead.

### 🖥️ Steps to Reproduce

Unfortunately I'm not exactly sure what is the root-cause for `event.target` being `null`, but based on the `TransitionEvent` interface it's real possibility.

### Version

react-aria: ^3.28.0

### What browsers are you seeing the problem on?

Chrome, Safari

### What operating system are you using?

Android, IOS

**Comment by snowystinger** [comment]
Looks like something that should be addressed. It would have been caught when we enabled ts strictmode checking for this package.

It looks like we sort of account for this
> // The transitioncancel event must be registered on the element itself, rather than as a global
      // event. This enables us to handle when the node is deleted from the document while it is transitioning.
      // In that case, the cancel event would have nowhere to bubble to so we need to handle it directly.

but maybe instead of relying on removeEventListener, we should make use of `once` https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#once

Thanks for the issue

Would you be willing to try submitting a fix?

**Comment by VillePakarinenPosti** [comment]
Sure thing! Opened [PR](https://github.com/adobe/react-spectrum/pull/5569) that you could check out.

**Comment by subvertallchris** [comment]
Hello! I appear to be encountering this bug while programmatically adding new `NumberInput` components to a view. I'm using Next.js although this is in a client component. I'm using `1.0.2-nightly.4425`, have not tried the two newer releases since then, but I wanted to bring it to your attention since the related PR was merged two weeks ago. Any chance there's a workaround in the meantime?
