### ISSUE TITLE
Ability to conditionally select if Table supports DnD

### ISSUE THREAD

**Issue by jaknas** [adobe/react-spectrum#5609]
### Provide a general summary of the issue here

I'd like to decide when Table component supports DnD or not. Let's say that in my app I have a feature like `editMode`, which when enabled should turn on DnD feature for all Tables on the page.

Currently, I have to reach out to conditionally mount 2 different tables, one with `dragAndDropHooks` and other without. This causes some performance issues since I basically tear down whole table and re-create it.

### 🤔 Expected Behavior?

I'd like to be able to conditonally pass if a table supports DnD

### 😯 Current Behavior

If I remove `dragAndDropHooks`, Table errors because hooks cannot be called conditionally. 

### 💁 Possible Solution

I would be OK with always passing `dragAndDropHooks`, but have a way to disable dragging and dropping rows for the user. 

### 🖥️ Steps to Reproduce

Will add later, but hopefully you know what I mean.

### Version

1.0.0-rc.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What operating system are you using?

MacOS Sonoma

**Comment by LFDanLu** [comment]
I think this should be possible if we introduce a `isDisabled` prop to `dragAndDropHooks`. This would also require some changes to `useDraggableItem` so accept `isDisabled` from the user so that it doesn't just look at the selectionManager to determine if a item is disabled for dragging. For the drop side of things, we could probably just override the `acceptedDropTypes` to return an empty array. 

Depending on your current use case you might be able implement this behavior already by conditionally disabling all keys in your Table and modifying the `acceptedDropTypes` provided to the `useDragAndDrop` hook when you want to disable DnD for your table. Not 100% if there would be any bugs with that though
