### ISSUE TITLE
React aria component Select multiple

### ISSUE THREAD

**Issue by federicocappellotto97** [adobe/react-spectrum#5635]
### Provide a general summary of the feature here

In the Select component at the moment is not possible to choose multiple values

### 🤔 Expected Behavior?

From a select you can choose multiple values from the Popover listbox

### 😯 Current Behavior

Now i can choose only one value

### 🔦 Context

I’m trying to build a multiple select

**Comment by vinayavodah** [comment]
Facing the same. Its not clear on how to do multiple selection.

**Comment by reidbarber** [comment]
Related to https://github.com/adobe/react-spectrum/issues/2140

**Comment by yihuiliao** [comment]
There was also a discussion post related to this a couple years ago: https://github.com/adobe/react-spectrum/discussions/2218

**Comment by snowystinger** [comment]
I'm going to close this one as we won't be supporting it in Select due to accessibility concerns pointed out in previous discussions and issues. If you need behavior like a native select with multiple, then ListBox can be used.

There are some other suggestions in the linked discussion and issue as well.
