### ISSUE TITLE
Large bundle size when using Button component

### ISSUE THREAD

**Issue by rvanlaarhoven** [adobe/react-spectrum#5639]
### Provide your feedback here.

I noticed a ~175kb jump in bundle size after adding a `Button` (`react-aria-components`) in a fresh Next.js project. I ran a bundle analyzer check and it seems like it bundles the complete lib (seeing `dnd`, `datepicker` and others), so I'm guessing tree shaking is not working as expected. Seems to be the same problem for `Tabs`.

As mentioned in https://github.com/adobe/react-spectrum/issues/4356, I also tested the build with `swcMinify: false`, which does not have a positive effect 

<img width="571" alt="Screenshot 2023-12-29 at 10 00 57" src="https://github.com/adobe/react-spectrum/assets/1857585/284edc69-1ac6-40fb-8d1c-861a7b1ca716">

### 💻 Code Sample

It's easily reproduceable by creating a fresh Next.js project (`npx create-next-app@latest`), accept al the defaults and add this in a new page:

```tsx
import { Button } from 'react-aria-components'

export default function Page() {
  return (
    <Button>
      Test
    </Button>
  )
}
```

### Version

react-aria-components v1.0.0 & v1.0.1-nightly.4385

### What operating system are you using?

Mac OS 14.1.1

**Comment by IonelLupu** [comment]
@rvanlaarhoven  oh. lol. I just created a big discussion topic on the NextJS repo about this as I discovered this issue too: https://github.com/adobe/react-spectrum/discussions/5654

**Comment by IonelLupu** [comment]
The NextJS team created an [issue](https://github.com/vercel/next.js/issues/60246) from my discussion about this and they are investigating, but I think it's also worth investigating it from the react-aria-components side. 

I checked the file used by react-aria-components that is used to load each component: `node_modules/react-aria-components/dist/module.js` and I think react-aria-components needs to use es6 import/export instead of bundling every component in one file. 

In the current setup, we are relying on 3rd party tersers to remove dead code whereas using import/export, it can be done automatically.

cc @devongovett @snowystinger @LFDanLu @dannify

**Comment by IonelLupu** [comment]
@devongovett @snowystinger @LFDanLu  this is a massive issue in my opinion

**Comment by devongovett** [comment]
It seems pretty normal with "use client" in the page, but without that it includes everything. That makes me think this is a Next.js issue rather than anything we can fix. I'm not sure why it would work differently. react-aria-components already includes a "use client" as well, so the only thing that is different is moving that up by one level (into the page component).

With "use client":
<img width="1544" alt="image" src="https://github.com/adobe/react-spectrum/assets/19409/c2a97deb-f6f0-43b3-8360-28236884effe">

Without "use client":
<img width="1544" alt="image" src="https://github.com/adobe/react-spectrum/assets/19409/ea32f1d3-87f1-44f1-92ce-7ceb73de4e44">

**Comment by IonelLupu** [comment]
@devongovett  I can help with this if this is a direction react-aria may go. Just let me know some steps where I can begin from and I can create a PR. ES6 imports/exports might be the way to go 🤔

**Comment by devongovett** [comment]
I'm starting to think that putting "use client" inside of React Aria Components might have been a mistake, and that it may be better in general for "use client" to be added by the _consumer_ of our components (e.g. in the page or component that uses them). Using React Aria components from server components usually doesn't work well anyway, because most of them usually require some kind of event handler (e.g. `onPress`, `onSelectionChange`, etc.). As soon as you try passing a function from a server component to a client component you'll get a build error from Next.js and need to add "use client" to your page/component anyway. Doing it this way also results in more optimal bundles as we see in this issue. As a result it might best if we removed "use client" from React Aria Components and recommended it be added in your own code when using them.

**Comment by IonelLupu** [comment]
> I'm starting to think that putting "use client" inside of React Aria Components might have been a mistake, and that it may be better in general for "use client" to be added by the _consumer_ of our components (e.g. in the page or component that uses them). Using React Aria components from server components usually doesn't work well anyway, because most of them usually require some kind of event handler (e.g. `onPress`, `onSelectionChange`, etc.). As soon as you try passing a function from a server component to a client component you'll get a build error from Next.js and need to add "use client" to your page/component anyway. Doing it this way also results in more optimal bundles as we see in this issue. As a result it might best if we removed "use client" from React Aria Components and recommended it be added in your own code when using them.

@devongovett if this improves the bundle size, then yes, let's do it. Let's leave the `use client` to users. Do you want me to submit a PR?

**Comment by windmaomao** [comment]
> @devongovett This is a weird issue indeed. Nextjs doesn't have a problem with other libraries (Ant Design for example). Can't really pin point where the issue is from. Maybe it's related to a similar issue MUI had in the past where they come up with path imports as a fix: https://mui.com/material-ui/guides/minimizing-bundle-size/#option-one-use-path-imports ?

I also notice this , ex. 404 pages, which shouldn't know anything about what i'm doing. 

<img width="615" alt="Screen Shot 2024-02-02 at 10 51 53" src="https://github.com/adobe/react-spectrum/assets/1700809/c70fda28-dbe6-4944-965c-cb84ead217dc">

**Comment by windmaomao** [comment]
By adding a `Input` test component, i see there's a 50K jump in nextJS bundle.

**Comment by huozhi** [comment]
👋 Hey everyone, we landed an optimization solution (PR https://github.com/vercel/next.js/pull/62238) into the new canary release (14.1.1-canary.63) which can optimize the packages like `react-aria-components` size in client bundle.
Sharing some testing result:

If we compare the `react-aria-components` the reproduction from https://github.com/vercel/next.js/issues/60246, you'll see the result being optimized a lot, 134KB being tree-shaked out.

#### After
```
Route (app)                              Size     First Load JS
┌ ○ /                                    324 B           127 kB
├ ○ /_not-found                          872 B          86.5 kB
└ ○ /other-page                          174 B           127 kB
```

#### Before
```
Route (app)                              Size     First Load JS
┌ ○ /                                    325 B           261 kB
├ ○ /_not-found                          870 B          86.5 kB
└ ○ /other-page                          176 B           261 kB
```

🙏 Feel free to try the new versions of Next.js to see if it helps. Lmk if there's any issue still remained
