### ISSUE TITLE
ComboBox with useAsyncList breaks on down arrow key press

### ISSUE THREAD

**Issue by eoin-pledge-io** [adobe/react-spectrum#5680]
### Provide a general summary of the issue here

Typing into the ComboBox filters the list as expected but when I type a value that does not match anything and then quickly press the down arrow twice I get a TypeError `Cannot read properties of null (reading 'type')`.

### 🤔 Expected Behavior?

When I press the down arrow quickly after filtering the list when there are no matching items, nothing happens.

### 😯 Current Behavior

When I press the down arrow quickly after filtering the list when there are no matching items, a `TypeError` occurs.

### 💁 Possible Solution

![Screenshot 2024-01-10 at 16 03 57](https://github.com/adobe/react-spectrum/assets/135844822/f5678b68-7f8b-41ad-8b7e-ee589c489cec)

The `TypeError` occurs in the [ListKeyboardDelegate class](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/selection/src/ListKeyboardDelegate.ts#L173) and is being caused by the key existing in the collection but then not being able to find the item in the collection based on that key.

### 🖥️ Steps to Reproduce

Code Sandbox: https://codesandbox.io/p/sandbox/brave-williamson-l4nz2v?file=%2Fsrc%2FApp.js

**Code Sandbox: Error Reproduction**

https://github.com/adobe/react-spectrum/assets/135844822/1d2c419b-d0e3-43f1-9db0-2dcf75e08d35

**Async Example in React Aria Docs: Error Reproduction**

https://github.com/adobe/react-spectrum/assets/135844822/7b49a431-f563-422f-805e-9288a8c45f0a

### Version

react-aria-components@1.0.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What operating system are you using?

macOS Ventura 13.13.1

**Comment by LFDanLu** [comment]
Thanks for catching this, [that line you've highlighted](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/selection/src/ListKeyboardDelegate.ts#L173) (and others like it in the keyboard delegate) should probably check that the item is non-null since the collection is empty during that time. We didn't have this problem in React Spectrum's ComboBox because it uses `ListLayout` instead of the `ListKeyboardDelegate`.

**Comment by sookmax** [comment]
@LFDanLu Hi, I've noticed `./packages/@react-aria/selection`, which contains `ListKeyboardDelegate.ts` is not included in the `paths` for `typescript-strict-plugin` in `tsconfig.json` yet. 

And since this issue will be fixed automatically if we introduce strict types to the directory `./packages/@react-aria/selection`, would it be better to prioritize said strict typing over adding a non-null check for this particular issue? (well, I see a lot of other TS errors in `./packages/@react-aria/selection` as well.. so maybe it's too daunting of a task? 😅 But I mean if we're eventually going to do it then I think .. better do it sooner than later?)
