### ISSUE TITLE
ComboBox inside of a Popover doesn't close when clicked outside of the Popover

### ISSUE THREAD

**Issue by tilpoe** [adobe/react-spectrum#5684]
### Provide a general summary of the issue here

I don't know if this is a bug or expected behaviour but i noticed, that if you have a ComboBox inside of a Popover, you can only close it by clicking outside, when the click still is inside of the parent Popover. If you click anywhere else on the screen, the ComboBox will stay opened. When you check this behaviour on a Select component, it works as expected (or at least expected from me) - the Select dropdown closes as soon as you click **anywhere** outside of it.

### 🤔 Expected Behavior?

If a ComboBox is inside of a Popover, it should still close as soon as one clicks **anywhere** outside of it. It works like that for the select component.

### 😯 Current Behavior

If a ComboBox is inside of a Popover, it only closes if your "outside click" is still inside of the parent popover.

### 🖥️ Steps to Reproduce

https://codesandbox.io/p/sandbox/quirky-architecture-nndhrz

1. Click on "Open Me" - a popover will open.
2. Open the select dropdown and click (a) outside of the dropdown, but still inside the parent popover -> the dropdown will close (b) outside of the dropdown and outside of the parent popover -> the dropdown will also close (expected behaviour)
3. Open the combobox dropdown and click (a) outside of the dropdown, but still inside the parent popover -> the dropdown will close (b) outside of the dropdown and outside of the parent popover -> the dropdown will **not** close

### Version

1.0.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What operating system are you using?

Mac OS 13.2.1 (22D68)

**Comment by LFDanLu** [comment]
Oh interesting, so the reason for this bug is that the Combobox is considered a `nonModal` since focus remains in the field which means we won't close it like a typical overlay when clicking/interacting outside of it via https://github.com/adobe/react-spectrum/blob/c3a4d63041997068c3306dc73174f7d29b44ccbe/packages/%40react-aria/overlays/src/usePopover.ts#L89. Instead we rely on blurring away from the input field here: https://github.com/adobe/react-spectrum/blob/c3a4d63041997068c3306dc73174f7d29b44ccbe/packages/%40react-aria/combobox/src/useComboBox.ts#L169 which confirms the combobox selection if any and closes the menu: https://github.com/adobe/react-spectrum/blob/c3a4d63041997068c3306dc73174f7d29b44ccbe/packages/%40react-stately/combobox/src/useComboBoxState.ts#L329. However, with the ComboBox being within a open Popover, clicks outside the Popover will be intercepted by a [underlay](https://github.com/adobe/react-spectrum/blob/c3a4d63041997068c3306dc73174f7d29b44ccbe/packages/react-aria-components/src/Popover.tsx#L155), resulting in focus not moving away from the ComboBox's input.

Not entirely sure the best way we should go about addressing this, perhaps we could track overlays that are `nonModal`s in `useOverlay` and close them in the case an outside interaction is detected by a lower level overlay element: https://github.com/adobe/react-spectrum/blob/c3a4d63041997068c3306dc73174f7d29b44ccbe/packages/%40react-aria/overlays/src/useOverlay.ts#L105-L109?

**Comment by LFDanLu** [comment]
Note for whoever picks this up in the future: this also happens with RSP ComboBox within a dialog as well

**Comment by LFDanLu** [comment]
Thanks for bringing up that up, it is indeed the same issue. I'll close this one favor of that one!
