### ISSUE TITLE
Listbox grid: Cannot read properties of undefined (reading 'key')

### ISSUE THREAD

**Issue by ritz078** [adobe/react-spectrum#5722]
### Provide a general summary of the issue here

When you are in first or last row of a grid, and you press Up Arrow or Down Arrow, you get the error 

```
Cannot read properties of undefined (reading 'key')
```

I guess it's because react aria doesn't check if an element exists.

### 🤔 Expected Behavior?

Even if there is no row above/below, it should not throw an error.

### 😯 Current Behavior

When you are in first or last row of a grid, and you press Up Arrow or Down Arrow, you get the error 

### 🖥️ Steps to Reproduce

Go to https://reactspectrum.blob.core.windows.net/reactspectrum/e41c580879cdfce063bafec4e756b712ef60af87/storybook-17/index.html?path=/story/cardview-grid-layout--dynamic-cards&providerSwitcher-express=false.

https://github.com/adobe/react-spectrum/assets/5389035/ca037d25-cf52-44b1-ab27-114977b6ba2c

### Version

3.31.1

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

MacOS

**Comment by LFDanLu** [comment]
Haha, we really need to return to CardView and its associated code sometime, hopefully sooner rather than later. I think the above issue can just be fixed by double checking that the rows looked up are non-null before the final return, or even earlier by checking that the `indexRowAbove`/`indexRowBelow` doesn't fall outside the range of `this.collection.rows[indexRowAbove]`.
