### ISSUE TITLE
Select - React ARIA

### ISSUE THREAD

**Issue by anevins12** [adobe/react-spectrum#5728]
### Provide your feedback here.

First of all, thanks for providing this library.

I had a couple of queries regarding the Select - React ARIA component that I've come across:

- How come you're using the value of the control (the element with `role="combobox"`) in the accessible name? For example, selecting "Snake" then puts "Snake" in the accessible name. This is at odds with a native `<select>` and the [APG select-only examples](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-select-only/) where the value is not used in the accessible name.
- Why do you suggest that if a control does not have a visible label then some ARIA can be used? This would not be an accessible solution to non-screen reader users such as some people with cognitive disabilities. That's when a form could fall under WCAG SC. 3.3.2 Labels or Instructions and labels would not be optional.

### 🔦 Context

Accessibility 

### 💻 Code Sample

https://react-spectrum.adobe.com/react-aria/Select.html

**Comment by devongovett** [comment]
We currently implement an [older ARIA pattern](https://www.w3.org/WAI/ARIA/apg/patterns/listbox/examples/listbox-collapsible/) for select, not a combobox. We discussed potentially migrating to the combobox pattern for this, but there seemed to be limited benefits for a significant amount of work and testing. See #4091.

Perhaps the language could be clarified, but what we mean by the section on labeling is that if you have a your own external label (rather than using the builtin one) you need to reference it via `aria-labelledby` or provide it via `aria-label` so that it is _also_ accessible to screen reader users. Having no visual label at all should be avoided, as you said.

**Comment by anevins12** [comment]
Appreciate the explanation.
