### ISSUE TITLE
Add example of typeahead functionality

### ISSUE THREAD

**Issue by obliviga** [adobe/react-spectrum#5740]
### 🙋 Documentation Request

The docs say that the typeahead feature is supported. It would be nice to see an example of that.

**Comment by reidbarber** [comment]
In the docs, typeahead is referring to typing typing `Pa` and having focus move to the `Panda` item in the collection:

<img width="258" alt="Listbox with Panda focused" src="https://github.com/adobe/react-spectrum/assets/8961049/c5f36663-806b-4cc8-901a-466b6d06f165">

You may be thinking of the feature of having an item auto-filled into the a Combobox/Searchautocomplete as you type. There is an issue for that at https://github.com/adobe/react-spectrum/issues/878. I believe it wasn't included in Combobox's initial release due to issues with screen readers.
