### ISSUE TITLE
Pass `name` attribute to `<FileTrigger />`

### ISSUE THREAD

**Issue by alexcarpenter** [adobe/react-spectrum#5751]
### Provide a general summary of the feature here

Would like the ability to pass a name attribute to the `<FileTrigger />` component.

### 🤔 Expected Behavior?

```jsx
<FileTrigger
  onSelect={(e) => {
    let files = Array.from(e);
    let filenames = files.map((file) => file.name);
    setFile(filenames);
  }}
  name="files"
>
  <Button>Select a file</Button>
</FileTrigger>
```

Should output:

```html
<input type="file" class="react-aria-Input" data-rac="" style="display: none;" name="files">
```

### 😯 Current Behavior

Name is not a valid prop and does not get forwarded to the input.

Example: https://codesandbox.io/p/sandbox/distracted-cache-fq2262?file=%2Fsrc%2FApp.js%3A9%2C7-18%2C21

### 💁 Possible Solution

Workaround at the moment is to use a ref and set the attribute is useEffect

```jsx
let ref = useRef<HTMLInputElement>(null)
useEffect(() => {
  ref.current?.setAttribute('name', 'media')
}, [])
<FileTrigger
  ref={ref}
>
  <Button>Select a file</Button>
</FileTrigger>
```

### 🔦 Context

Looking to use this in a form that accepts files.

**Comment by yihuiliao** [comment]
This has been discussed previously (https://github.com/adobe/react-spectrum/discussions/5486) which I recommend looking through in addition to the PR since there is more information there but in short, due to some complications, we decided not to support forms in FileTrigger. We'd like to create a separate file input component in the future, but due to other priorities, this is something we have not been able to work on.
