### ISSUE TITLE
Escaping HTML tags in JSDoc

### ISSUE THREAD

**Issue by RBilly** [adobe/react-spectrum#6027]
Storybook uses JSDoc to generate description for a component properties.
When using HTML tags in the JSDoc comment without escaping it, it can cause issues.

```
 /**
   * The <form> element to associate the button with.
   * The value of this attribute must be the id of a <form> in the same document.
   */
  form?: string,
```
This throws an error because it can't render a `<form>` inside a `<p>` element but we don't want to actually render an html `<form>` in the description.
The effect can be seen here:
https://react-spectrum.adobe.com/react-aria-starter/index.html?path=/docs/button--docs
and here:
https://react-spectrum.adobe.com/react-aria-tailwind-starter/index.html?path=/docs/button--docs

_Originally posted by @RBilly in https://github.com/adobe/react-spectrum/discussions/6026_

**Comment by reidbarber** [comment]
We can surround these with backticks. This should also fix them being rendered in IDEs.

**Comment by sookmax** [comment]
Haha it's funny to me that I fixed this exact issue for [RAC docs](https://react-spectrum.adobe.com/react-aria/Button.html#props) in the past with https://github.com/adobe/react-spectrum/pull/5614, but didn't realize there were whole different comment-parsing and processing going on in the starter story docs.

Interestingly both RAC docs and storybook docs use the same underlying markdown parser [markdown-to-jsx](https://www.npmjs.com/package/markdown-to-jsx). What's different, however, is that storybook docs doesn't allow the user to pass options to said `markdown-to-jsx`. This point is important because this issue can easily be solved by passing [options.disableParsingRawHTML](https://www.npmjs.com/package/markdown-to-jsx#optionsdisableparsingrawhtml) to `markdown-to-jsx`.

This is how storybook renders the description rows in `<ArgTypes>` doc block component:
https://github.com/storybookjs/storybook/blob/bfa05701390eea3954e853de4208f18b6862cd68/code/ui/blocks/src/components/ArgsTable/ArgRow.tsx#L103-L107

So no way to pass said `options.disableParsingRawHTML` to `<Markdown>` in storybook docs.

[A similar issue](https://github.com/storybookjs/storybook/issues/25165) seems to have been reported in storybook repo, but got closed with a comment effectively saying 'use `` ` `` to avoid the issue'.

So I guess that's the way to fix it as @reidbarber mentioned above!
