### ISSUE TITLE
Unable to capture press events

### ISSUE THREAD

**Issue by Itherael** [adobe/react-spectrum#6086]
### Provide a general summary of the issue here

When attempting to attach an event listener to the document to capture the click event, we've observed that the listener fails to trigger when the element is removed from the DOM via a press event from `useButton`/`usePress`. Nevertheless, we are able to capture the event successfully if we employ a native button with the `onclick` event handler.

### 🤔 Expected Behavior?

The event listener should trigger when the element is clicked, whether utilising the `onPress` event from `useButton`/`usePress` or the native `onclick` event.

### 😯 Current Behavior

The event listener is not being triggered when the element is clicked using the `onPress` event from `useButton/usePress`. The event listener is triggered when the element is clicked using the native `onclick` event.

### 🔦 Context

We are using analytics tools to track user interactions with the page. However, when utilising the `useButton`/`usePress` hooks, the events are not captured if the element disappears, such as when the user is redirected to another page. However, these tools successfully capture events when using the native `onclick` event. The provided CodeSandbox offers a simplified demonstration of this issue.

### 🖥️ Steps to Reproduce

The following CodeSanbox attaches an event listener to the document to capture the click event. It includes two buttons: one utilises the `useButton`/`usePress` hooks, and the other employs the native `onclick` event. When clicking these buttons, we toggle their visibility to simulate the element disappearing from the DOM.

Instructions:
1.  Access the CodeSandbox: https://codesandbox.io/s/lpm5mm
2. Click on the "Standard button." The buttons will hide, and a log will be displayed on the page.
3. Click on "Show buttons again." The buttons will reappear, and the log will be displayed again.
4. Click on the "Aria button." The buttons will hide, and the log won't be updated, indicating that the event listener is not being triggered.

### Version

@react-aria/button@3.9.3

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What operating system are you using?

macOS 14.2.1

**Comment by devongovett** [comment]
onPress is fired during the native pointerup event, which happens before the click event. So it makes sense that if you hide the button the click event wouldn't fire (it is already gone at that point).

You could try capturing pointerup in addition to click. But the problem with this approach to analytics in general is that there are a lot of events that could trigger actions you want to track other than mouse events. For example, keyboard events trigger actions as well, and it depends on the component which exact interactions trigger which events (eg some fire on pointer down, some on key up, etc). Just tracking clicks globally is too low level.

We usually recommend doing this inside the component rather than having a single listener for the whole page. That way, you can attach your handler directly to `onPress`, or `onAction`, or `onSelectionChange`, or whatever the actual high level action is. This gives you much more accurate information to track.

For example you could have a helper that wraps events like this:

```jsx
<Button onPress={trackEvent("sign_up_button", theRealOnPressHandler)}>
```

Then it also works with other events like `onAction` on menus, and `onSelectionChange` in combo boxes and it doesn't matter which native event triggered them.

**Comment by Itherael** [comment]
Thanks @devongovett. Unfortunately, due to the structure of our project, manually adding track event handlers to every component isn't feasible at the moment(long story).
To provide context, [Fullstory](https://www.fullstory.com/) is a tool we use to record the user session interacting with our UI. However, it encounters difficulties when buttons disappear from view. Our application has a script loaded that enables FullStory to capture all screen events, regardless of the components involved.

We're facing a challenge here because while using native buttons works fine with the tool, React Aria offers numerous valuable features, with accessibility being the most critical one. However, we cannot change how the onPress function operates internally nor adjust its usage to include a track event.

**Comment by devongovett** [comment]
Not really sure what we could do here there. Maybe you could delay updating the DOM until after the click event with a setTimeout or something?

**Comment by Itherael** [comment]
We were aware of using `setTimeout` to defer execution to the next event loop. However, we wanted to explore other options before considering going with `setTimeout`. It appears there aren't any alternatives on Aria's side. Thanks for the support and clarification! 😄

**Comment by snowystinger** [comment]
closing as resolved, let us know if you run into other issues
