### ISSUE TITLE
ComboBox list items not scrolling

### ISSUE THREAD

**Issue by upender7270** [adobe/react-spectrum#6241]
### Provide a general summary of the issue here

I am integrating comboBox with my React app, 
React - v18
Node - v20.7.0
OS - Ubuntu 22.04.4 LTS 

```
"@adobe/react-spectrum": "^3.34.1",
"@react-spectrum/combobox": "^3.12.3",
"@react-spectrum/provider": "^3.9.5",
```

https://github.com/adobe/react-spectrum/assets/43287621/bb3c03d0-d057-44b3-b541-b13c841104ef

### 🤔 Expected Behavior?

Should be able to scroll the items in the list box

### 😯 Current Behavior

Unable to scroll items in list box

### 🖥️ Steps to Reproduce

1. Clone the repo - https://github.com/upender7270/react-combobox
2. `yarn`
3. `yarn storybook`
4. Open dynamic or static story of the combobox

### Version

3.34.1

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

Ubuntu

**Comment by RajaTheKing826** [comment]
Yah yah I've also faced this issue many times. 
Someone please look into this.

**Comment by snowystinger** [comment]
Possibly related [scrollIntoViewport: improve scrolling behavior for elements with multiple scrollable parents](https://github.com/adobe/react-spectrum/pull/6187#top)

**Comment by reidbarber** [comment]
@snowystinger just tested with the nightly and I still saw this issue, so seems unrelated.

**Comment by sookmax** [comment]
I was also looking into this issue at the moment, and realized [PopoverWrapper](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-spectrum/overlays/src/Popover.tsx#L88) was being rendered too many times (this can be verified with [React Developer Tools](https://chromewebstore.google.com/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi)). And this infinite rendering of `<PopoverWrapper>` seems to be the reason why we're unable to scroll.

It looks like the root cause of this chain rendering is the invocation of `updatePosition()` inside the `onResize()` callback here:
https://github.com/adobe/react-spectrum/blob/72775d272be04cfa32d26ec821bc68513d92a72b/packages/%40react-aria/overlays/src/useOverlayPosition.ts#L195-L204

If the above `updatePosition()` is commented out, you'll see the working scroll:


https://github.com/adobe/react-spectrum/assets/71210554/46a0c1ea-64bc-4682-9f0b-9132e0bf6692

**Comment by youssrikrap-cpi** [comment]
I'm experiencing the same issue. When the list is long enough and a scrollbar is rendered, the `resize` event from [VisualViewport](https://developer.mozilla.org/en-US/docs/Web/API/VisualViewport) is triggered very often causing `updatePosition` to be called very often as well. This in turn causes the list to be unscrollable. It does not seem to be related to scrolling itself, since the `resize` event is triggering right after opening the ComboBox (see my second recording). 

So far, I've only seen this happen when `shouldFlip` is set to `false` and `isNonModal` is set to `true` in ComboBox (as @sookmax already brought up in [another issue](https://github.com/adobe/react-spectrum/issues/5653#issuecomment-1923969355)). Setting `shouldFlip` to `true` (default behavior) or `isNonModal` to `false` doesn't seem to result in the repeated `resize` events.


This recording shows scroll state resetting:

https://github.com/adobe/react-spectrum/assets/101109442/3c36bcb0-4f86-44a5-992c-e6feff4d2762



And this recording shows a `console.log` whenever `resize` is triggered on `visualViewport`.

https://github.com/adobe/react-spectrum/assets/101109442/caac9ca8-b2e5-40c7-af44-b18f293ee8e2

**Comment by dsmmcken** [comment]
If it helps, I've noticed that rolling back one version to 3.33.1 fixes it, so it must have been introduced by a commit between that and 3.34.0.

**Comment by snowystinger** [comment]
Looks like we broke this in https://github.com/adobe/react-spectrum/pull/5808

**Comment by devongovett** [comment]
This is now fixed in the latest patch release.
