### ISSUE TITLE
ComboBox input clears when the text inside it is longer than its width and starts to scroll horizontally

### ISSUE THREAD

**Issue by nkalpak** [adobe/react-spectrum#6362]
### Provide a general summary of the issue here

When rendering the `ComboBox` as it is directly taken from the [starter kit](https://react-spectrum.adobe.com/react-aria/ComboBox.html#starter-kits), when you write enough text inside the input to overflow horizontally, the entire input will reset.

### 🤔 Expected Behavior?

The input shouldn't reset

### 😯 Current Behavior

The input resets

### 💁 Possible Solution

I've investigated a bit and found the code in `useComboBoxState.ts:237` to look suspicious. When adding both the `selectedKey` and `inputValue` to make the ComboBox controlled, the input is no longer cleared.

### 🖥️ Steps to Reproduce

1. Go to this [codesandbox](https://codesandbox.io/p/sandbox/laughing-water-q2gltg?file=%2Fsrc%2FComboBox.tsx%3A48%2C5)
2. Try typing "Strawberry" into the input
3. Observe that the input is cleared when you reach the point that the text starts overflowing horizontally

### Version

1.2.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What operating system are you using?

MacOS

**Comment by yihuiliao** [comment]
I think this has been fixed with https://github.com/adobe/react-spectrum/pull/6461. I tried out the example above locally with the latest on main and wasn't able to reproduce the issue anymore. The fix will be out in our next release so I would make sure to update once that is available and double check to make sure it isn't still an issue. I'm going to close this as fixed but if you find that it is still a problem after release, please feel free to reopen it.
