### ISSUE TITLE
Warning: React does not recognize the `allowFocusWhenDisabled` prop on a DOM element.

### ISSUE THREAD

**Issue by wigsnes** [adobe/react-spectrum#6448]
### Provide a general summary of the issue here

Using the useNumberField hook, and the increment/decrement props have 'allowFocusWhenDisabled', it is not typed but makes react error. I have a similar problem with 'excludeFromTabOrder', but that is typed so I can remove it myself.

```Warning: React does not recognize the `allowFocusWhenDisabled` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `allowfocuswhendisabled` instead. If you accidentally passed it from a parent component, remove it from the DOM element.```

### 🤔 Expected Behavior?

To not error

### 😯 Current Behavior

It gives error message.

### 💁 Possible Solution

Either remove the prop or type it so I can exclude it myself. I can probably fix this by ignoring the type, but should not be like it is now.

### 🖥️ Steps to Reproduce

Use any react framework. Create a numberField component with buttons to increment and decrement. Check console for error.

### Version

^3.32.1

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

macOS

**Comment by sookmax** [comment]
Are you perhaps using `useNumberField()` with plain HTML `<button>`s?

It looks like `allowFocusWhenDisabled` is meant to be handled by `useButton()`:
https://github.com/adobe/react-spectrum/blob/379e8d64f76c15bbb35f710c4150cc84e85b1d7e/packages/%40react-aria/button/src/useButton.ts#L100-L102

And the example from the docs uses RAC `<Button>` instead of html `<button>`:
https://react-spectrum.adobe.com/react-aria/useNumberField.html#example

I guess you can use html `<button>`s also, as long as you use them with `useButton()`.

**Comment by snowystinger** [comment]
@sookmax is correct, our numberfield is meant to be used with buttons which also use our hooks. If you do not include useButton, then some things will not work/won't be normalized across OS|browsers|input methods|etc
I'm going to close this as resolved. Let us know if you have any more questions.

**Comment by wigsnes** [comment]
We use the hook usePress on our buttons. We experienced some problems with useButton and usePress worked for our use case. Seems like it usePress does not handle this problem.

**Comment by snowystinger** [comment]
Can you say more about the issues you had with useButton? As that's the correct thing to use here and usePress would only be part of the picture
