### ISSUE TITLE
Prevent focus on press of a button

### ISSUE THREAD

**Issue by ritz078** [adobe/react-spectrum#6533]
### Provide a general summary of the feature here

I am developing a rich text editor. When text is selected and a formatting button in the toolbar is clicked, the mobile keyboard closes because the focus shifts to the button. To prevent this, I tried adding `event.preventDefault()` to `onMouseDown`, but this doesn't work because `usePress` employs various other events to change focus, making `onMouseDown` inaccessible.

It will be great to have a prop named `preventFocusOnPress` if we cannot have `onMouseDown`

### 🤔 Expected Behavior?

There should be a way to prevent focus on buttons.

### 😯 Current Behavior

There is no way to prevent focus on click of a button

### 🔦 Context

In text editors, even when you click a button, the focus should not shift from the main textbox but there is no way to do that in the current button hooks.

### 🧢 Your Company/Team

PSPDFKit

**Comment by LFDanLu** [comment]
We actually have [preventFocusOnPress](https://github.com/adobe/react-spectrum/blob/6e57855257f54738418f98c37efae798bf9fb4ad/packages/%40react-aria/button/src/useButton.ts#L58-L59) in useButton already but it is undocumented since it was more for specific use cases (calendar cells, combobox button, etc) and we didn't want it to be misused. I can bring it up with the team to see if we want to pivot on that and expose it fully.

**Comment by LFDanLu** [comment]
Talked with the team, we are ok with exposing it as public api, will need to document it and mention that it should only be used in particular use cases.

**Comment by ritz078** [comment]
This is great. Thank you for taking the time and coming up with a solution this fast.
