### ISSUE TITLE
Getting white space while scroll to the bottom of the combobox

### ISSUE THREAD

**Issue by NarendraKuruva** [adobe/react-spectrum#6594]
### Provide a general summary of the issue here

[Here is a reproducible code sandbox](https://codesandbox.io/p/sandbox/funny-knuth-88xnv7?file=%2Fsrc%2FComboboxV1%2FComboBox.tsx%3A317%2C17)

GIF Reference:- 
![Peek 2024-06-22 15-12](https://github.com/adobe/react-spectrum/assets/102137869/d3d68a1b-f4a6-4f56-adbd-db9d2dfaabc3)

I've copied the latest published (May 1st) combobox & list box components 

And I'm getting white space when scrolling

### 🤔 Expected Behavior?

Should not get any white space

### 😯 Current Behavior

Getting white space while scrolling to the end fast

### 🖥️ Steps to Reproduce

1. Open combobox
2. Scroll to the end of the combobox, to the last pagination
3. Close the combobox 
4. Open again and scroll to the end fast
5. You will be able to the whitespace

### Version

Not installed react-spectrum

### What browsers are you seeing the problem on?

Chrome

### If other, please specify.

Using specific nested packages

### What operating system are you using?

Ubuntu 22.04.4 LTS

**Comment by LFDanLu** [comment]
Its hard to tell what exactly is broken here since I can't easily tell what changes exist between the sandbox and the RSP ComboBox component. It seems like a 1:1 copy but there are styles that are missing because the Spectrum specific class names don't have their associated styles and there are other behavioral differences from the RSP ComboBox like the popover closing even with "Emulate a focused page" turned on. Can you try unifying the packages so they only use the monopakage import where possible so that there aren't any duplicate package issues? Might be easier to debug if you use the Item/etc implementations straight from `@adobe/react-spectrum` and then gradually change them to your custom implementation to see where the break happens.

**Comment by RajaTheKing826** [comment]
@LFDanLu  When i read the spectrum code the height of the popover is calculating in hooks instead of with css classnames so i think class names aren't the issue. Can you define what is unifying packages because we didn't install any duplicate package versions in the above codesandbox. 

So can you please check the code once and tell what we are missing.

**Comment by LFDanLu** [comment]
I don't think the class names would be the issue either but as I mentioned there are other behavior differences other that the additional whitespace that you are seeing that make me think that there are other changes to the copied code that I can tell from a glance or something else in the setup (duplicate packages/etc) that are causing these issues. Duplicate packages can arise due to each installed package pulling its own version of various dependencies that aren't deduplicated by the package manager automatically. I would recommend you start with first using the ComboBox as is from React Spectrum's `@adobe/react-spectrum` package, then slowly replace the implementation bit by bit and see when/where it breaks. 

That being said, if you are trying to create your own combobox, I'd highly recommend using the React Aria Components version of it rather than copying the React Spectrum implementation. The React Spectrum implementation comes with many Spectrum Design specific behaviors and may be difficult to untangle and customize. Virtualization support is being worked on for React Aria Components as a whole as well so soon there will be parity between the two.

**Comment by dannify** [comment]
Please use the React Spectrum component directly since it does not display this issue or use the RAC version if you need to style it in a different way. If you can create this issue with the latest version of React Spectrum, please reopen this issue with the code sandbox or stack blitz example.
