### ISSUE TITLE
Last options not getting rendered in popover after selection in combobox

### ISSUE THREAD

**Issue by RajaTheKing826** [adobe/react-spectrum#6641]
### Provide a general summary of the issue here

I have 32 items in a combobox, when i select 32nd item and reopen the combobox im not getting the 32 items getting some 28 items even after scrolling to bottom. I need to close and open the popover multiple times to get my all items.

https://codesandbox.io/p/sandbox/sharp-cohen-m2jjz8?file=%2Fsrc%2FListBoxV1%2Findex.css

![Peek 2024-06-28 09-54](https://github.com/adobe/react-spectrum/assets/59301270/da1f5c4a-4eff-4bc5-bace-262a3d791a97)

### 🤔 Expected Behavior?

All 32 items should be visible in popover how many times i open it.

### 😯 Current Behavior

Not getting all items in popover.

### 🔦 Context

https://codesandbox.io/p/sandbox/sharp-cohen-m2jjz8?file=%2Fsrc%2FListBoxV1%2Findex.css

### 🖥️ Steps to Reproduce

You can check the case here

https://codesandbox.io/p/sandbox/sharp-cohen-m2jjz8?file=%2Fsrc%2FListBoxV1%2Findex.css

### Version

Not using react spectrum instead using nested packages

### What browsers are you seeing the problem on?

Chrome

### If other, please specify.

NA

### What operating system are you using?

Ubuntu 22.04

**Comment by snowystinger** [comment]
Please check for duplicate keys on this one as well. I'm also not sure what you're saying is the difference between the two Issues you opened?

**Comment by akyllus** [comment]
<html>
<body>
<span style="color: rgb(255, 255, 255); font-family: &quot;Dancing Script&quot;, cursive; font-size: 14.4px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(57, 150, 251); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Summary of the Issue</span><p style="box-sizing: border-box; margin: 0px 0px 1rem; padding: 0px; color: rgb(255, 255, 255); font-family: &quot;Dancing Script&quot;, cursive; font-size: 14.4px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">The combobox component in the provided CodeSandbox example contains 32 items. When selecting the 32nd item and reopening the combobox, not all 32 items are displayed. Instead, only 28 items are visible, and it requires multiple reopenings of the popover to see all items.<br style="box-sizing: border-box; margin: 0px; padding: 0px;">Expected Behavior<br style="box-sizing: border-box; margin: 0px; padding: 0px;">All 32 items should be visible in the popover every time it is opened, regardless of how many times it is closed and reopened.<br style="box-sizing: border-box; margin: 0px; padding: 0px;">Current Behavior<br style="box-sizing: border-box; margin: 0px; padding: 0px;">Only 28 items are visible in the popover when it is reopened after selecting the 32nd item. It requires multiple reopenings to see all 32 items.<br style="box-sizing: border-box; margin: 0px; padding: 0px;">Possible Solution<br style="box-sizing: border-box; margin: 0px; padding: 0px;">The issue could be related to the virtualization or the way the items are being rendered and managed in the combobox. A potential solution could involve ensuring that the state of the items is correctly managed and that the virtualization logic correctly handles the full list of items.<br style="box-sizing: border-box; margin: 0px; padding: 0px;">Context<br style="box-sizing: border-box; margin: 0px; padding: 0px;">The issue can be reproduced in the provided CodeSandbox link:<span> </span><a href="https://codesandbox.io/p/sandbox/sharp-cohen-m2jjz8?file=%2Fsrc%2FListBoxV1%2Findex.css" style="box-sizing: border-box; margin: 0px; padding: 0px; color: rgb(0, 123, 255); text-decoration: none; background-color: transparent;">https://codesandbox.io/p/sandbox/sharp-cohen-m2jjz8?file=%2Fsrc%2FListBoxV1%2Findex.css</a><br style="box-sizing: border-box; margin: 0px; padding: 0px;">Steps to Reproduce</p><p style="box-sizing: border-box; margin: 0px 0px 1rem; padding: 0px; color: rgb(255, 255, 255); font-family: &quot;Dancing Script&quot;, cursive; font-size: 14.4px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Open the CodeSandbox link.<br style="box-sizing: border-box; margin: 0px; padding: 0px;">Select the 32nd item in the combobox.<br style="box-sizing: border-box; margin: 0px; padding: 0px;">Close and reopen the combobox.<br style="box-sizing: border-box; margin: 0px; padding: 0px;">Observe that not all 32 items are visible.</p><p style="box-sizing: border-box; margin: 0px 0px 1rem; padding: 0px; color: rgb(255, 255, 255); font-family: &quot;Dancing Script&quot;, cursive; font-size: 14.4px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Version<br style="box-sizing: border-box; margin: 0px; padding: 0px;">Not using react spectrum; instead, using nested packages.<br style="box-sizing: border-box; margin: 0px; padding: 0px;">Browsers Affected<br style="box-sizing: border-box; margin: 0px; padding: 0px;">Chrome<br style="box-sizing: border-box; margin: 0px; padding: 0px;">Operating System<br style="box-sizing: border-box; margin: 0px; padding: 0px;">Ubuntu 22.04<br style="box-sizing: border-box; margin: 0px; padding: 0px;">Tracking Issue<br style="box-sizing: border-box; margin: 0px; padding: 0px;">To solve this issue, the following steps can be taken:</p><p style="box-sizing: border-box; margin: 0px 0px 1rem; padding: 0px; color: rgb(255, 255, 255); font-family: &quot;Dancing Script&quot;, cursive; font-size: 14.4px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Investigate the virtualization logic used in the combobox.<br style="box-sizing: border-box; margin: 0px; padding: 0px;">Ensure that the state of the items is correctly managed and that the full list of items is being rendered.<br style="box-sizing: border-box; margin: 0px; padding: 0px;">Test the combobox after making changes to ensure that all items are visible every time the popover is opened.</p><p style="box-sizing: border-box; margin: 0px 0px 1rem; padding: 0px; color: rgb(255, 255, 255); font-family: &quot;Dancing Script&quot;, cursive; font-size: 14.4px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Here is a potential solution to address the issue:</p><ol style="box-sizing: border-box; margin: 0px; padding: 0px; color: rgb(255, 255, 255); font-family: &quot;Dancing Script&quot;, cursive; font-size: 14.4px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li style="box-sizing: border-box; margin: 0px 0px 0.7rem; padding: 0px; display: flex; flex-direction: column; justify-content: flex-start; align-items: flex-start;"><p style="box-sizing: border-box; margin: 0px 0px 1rem; padding: 0px;"><strong style="box-sizing: border-box; margin: 0px; padding: 0px; font-weight: bolder;">Check the Virtualization Logic</strong>: Ensure that the virtualization logic correctly handles the full list of items and does not incorrectly truncate the list.</p></li><li style="box-sizing: border-box; margin: 0px 0px 0.7rem; padding: 0px; display: flex; flex-direction: column; justify-content: flex-start; align-items: flex-start;"><p style="box-sizing: border-box; margin: 0px 0px 1rem; padding: 0px;"><strong style="box-sizing: border-box; margin: 0px; padding: 0px; font-weight: bolder;">State Management</strong>: Ensure that the state of the items is correctly managed so that the full list is always available when the popover is opened.</p></li><li style="box-sizing: border-box; margin: 0px 0px 0.7rem; padding: 0px; display: flex; flex-direction: column; justify-content: flex-start; align-items: flex-start;"><p style="box-sizing: border-box; margin: 0px 0px 1rem; padding: 0px;"><strong style="box-sizing: border-box; margin: 0px; padding: 0px; font-weight: bolder;">Testing</strong>: After making changes, thoroughly test the combobox to ensure that all items are visible every time the popover is opened.</p></li></ol><p style="box-sizing: border-box; margin: 0px 0px 1rem; padding: 0px; color: rgb(255, 255, 255); font-family: &quot;Dancing Script&quot;, cursive; font-size: 14.4px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Here is a simplified example of how you might ensure that the full list of items is always available:</p><pre class="code-badge-pre" style="box-sizing: border-box; margin: 0px 0px 1rem; padding: 0px; font-family: SFMono-Regular, Menlo, Monaco, Consolas, &quot;Liberation Mono&quot;, &quot;Courier New&quot;, monospace; font-size: 12.6px; overflow: auto; display: block; color: rgb(33, 37, 41); position: relative; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="code-badge" style="box-sizing: border-box; margin: 0px; padding: 5px 8px; display: flex; flex-direction: row; white-space: normal; background: rgb(51, 51, 51); color: white; font-size: 0.875em; opacity: 0.5; transition: opacity 0.5s linear 0s; border-radius: 0px 0px 0px 7px; position: absolute; right: 0px; top: 0px;"><div class="code-badge-language" style="box-sizing: border-box; margin: 0px 10px 0px 0px; padding: 0px; font-weight: 600; color: goldenrod;">javascript</div><div title="Copy to clipboard" style="box-sizing: border-box; margin: 0px; padding: 0px;"><i class="fa fa-copy code-badge-copy-icon" style="box-sizing: border-box; margin: 0px; padding: 0px 7px; display: inline-block; font: 1.2em / 1 FontAwesome; text-rendering: auto; -webkit-font-smoothing: antialiased; cursor: pointer;"></i></div></div><code class="language-javascript hljs" data-highlighted="yes" style="box-sizing: border-box; margin: 0px; padding: 1em; font-family: SFMono-Regular, Menlo, Monaco, Consolas, &quot;Liberation Mono&quot;, &quot;Courier New&quot;, monospace; font-size: inherit; color: rgb(221, 221, 221); overflow-wrap: break-word; word-break: normal; background: rgb(48, 48, 48); display: block; overflow-x: auto;">
  | import React, { useState, useEffect, useRef } from 'react';
-- | --
  | import { Combobox, ListBox, Popover } from 'your-combobox-library'; // Replace with actual imports
  |  
  | const items = Array.from({ length: 32 }, (_, i) => `Item ${i + 1}`);
  |  
  | const MyCombobox = () => {
  | const [selectedItem, setSelectedItem] = useState(null);
  | const [isOpen, setIsOpen] = useState(false);
  | const listRef = useRef(null);
  |  
  | useEffect(() => {
  | if (isOpen && listRef.current) {
  | listRef.current.scrollToItem(items.indexOf(selectedItem));
  | }
  | }, [isOpen, selectedItem]);
  |  
  | return (
  | <Combobox
  | onToggle={(isOpen) => setIsOpen(isOpen)}
  | onSelect={(item) => setSelectedItem(item)}
  | >
  | <input value={selectedItem \|\| ''} readOnly />
  | <Popover isOpen={isOpen}>
  | <ListBox ref={listRef} items={items}>
  | {(item) => <div key={item}>{item}</div>}
  | </ListBox>
  | </Popover>
  | </Combobox>
  | );
  | };
  |  
  | export default MyCombobox;

</code></pre><p style="box-sizing: border-box; margin: 0px 0px 1rem; padding: 0px; color: rgb(255, 255, 255); font-family: &quot;Dancing Script&quot;, cursive; font-size: 14.4px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">In this example, the<span> </span><code style="box-sizing: border-box; margin: 0px; padding: 0px; font-family: SFMono-Regular, Menlo, Monaco, Consolas, &quot;Liberation Mono&quot;, &quot;Courier New&quot;, monospace; font-size: 12.6px; color: rgb(232, 62, 140); overflow-wrap: break-word;">useEffect</code><span> </span>hook ensures that the list scrolls to the selected item when the popover is opened. This should help in ensuring that all items are visible when the popover is reopened.</p><button class="copy-btn" style="box-sizing: border-box; margin: 0px 0px 0px 10px; padding: 5px; border-radius: 0px; font-family: inherit; font-size: 14px; line-height: inherit; overflow: visible; text-transform: none; appearance: button; background-color: rgb(241, 241, 241); border: none; cursor: pointer; color: rgb(57, 150, 251); orphans: 2; widows: 2; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><i class="fa fa-clipboard" style="box-sizing: border-box; margin: 0px; padding: 0px; display: inline-block; font-style: normal; font-variant: normal; font-kerning: auto; font-optical-sizing: auto; font-feature-settings: normal; font-variation-settings: normal; font-weight: normal; font-stretch: normal; line-height: 1; font-family: FontAwesome; font-size: inherit; text-rendering: auto; -webkit-font-smoothing: antialiased;"></i></button><br class="Apple-interchange-newline">
</body>
</html>

**Comment by snowystinger** [comment]
I removed a comment on this Issue because it appeared to be spam generated by AI. It was very hard to follow, not formatted well, and was not clear on what it was trying to do.

**Comment by RajaTheKing826** [comment]
https://github.com/adobe/react-spectrum/issues/6642#issuecomment-2196222193 
The same reason for this issue too.

**Comment by snowystinger** [comment]
Closing as a duplicate
