### ISSUE TITLE
react aria <MyRadioGroup> orientation='horizontal' is not working

### ISSUE THREAD

**Issue by tadiraman** [adobe/react-spectrum#6791]
### Provide a general summary of the issue here

orientation='horizontal' is not working. I tried to change in dom, then i can see this working but via code when passed like this. Strange!
![image](https://github.com/user-attachments/assets/b6c7c2f5-2334-4277-b204-a3e3f0f2d6ee)

```
{
  render: () => {
    const [value, setValue] = useState<string>('');
    //const options = ['Walk', 'Bike', 'Car', 'Transit'];
    const options: RadioProps[] = [{
      name: 'Walk'
    }, {
      name: 'Bike'
    }, {
      name: 'Car'
    }, {
      name: 'Transit'
    }];
    return <>
                <h2>Check for👉 Enabled: Selected, Un-Selected</h2>
                <RadioSelect label={'Label for Radio Group'} description={'Description for RadioGroup'} orientation={"horizontal"} options={options} onChange={val => {
        setValue(val);
      }} />
                <h3>👉'OnChange Value: ': {value}</h3>

            </>;
  }
}
```

### 🤔 Expected Behavior?

This is the expected behaviour

![image](https://github.com/user-attachments/assets/f0e669b3-d001-4646-823d-8f5e8403fb4a)

### 😯 Current Behavior

orientation is vertical, even when 'horizontal' is passed for the orientation prop
![image](https://github.com/user-attachments/assets/ce9e72a5-ccb8-4347-892e-cd0a4c1862eb)

### 🖥️ Steps to Reproduce

```
<MyRadioGroup label="Favorite avatar" orientation="horizontal">
  <Radio value="wizard">Wizard</Radio>
  <Radio value="dragon">Dragon</Radio>
</MyRadioGroup>
```

### Version

"react-aria": "3.21.0",     "react-aria-components": "^1.0.1",

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

Windows

**Comment by snowystinger** [comment]
We don't control the styling of your radio group. You can see the styles we apply in our documentation though just beneath the example https://react-spectrum.adobe.com/react-aria/RadioGroup.html#orientation perhaps you can base your implementation on it?

**Comment by tadiraman** [comment]
@snowystinger The styling specified in the docs(see below) doesn't work when applied. That's the reason I raised this issue.

```
.react-aria-RadioGroup {
  &[data-orientation=horizontal] {
    flex-direction: row;
    align-items: center;
  }
}
```

**Comment by snowystinger** [comment]
Can you provide a codesandbox or stackblitz to demonstrate your issue? It's working in the docs and I don't have enough information from your description. Thank you for your patience while we figure out what's going on together.

**Comment by yihuiliao** [comment]
Here's a [codesandbox](https://codesandbox.io/p/sandbox/flamboyant-meitner-wqhmrv?file=%2Fsrc%2FApp.js&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clzu7d7lu00063b6ixqcstvrg%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clzu7d7lt00023b6itb3msmv9%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clzu7d7lu00033b6itmxhirnp%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clzu7d7lu00053b6i8d0ec981%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clzu7d7lt00023b6itb3msmv9%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzu7d7lt00013b6ixlsk47pn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clzx9xjuw00023b6jo6ou6y4s%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clzu7d7lt00023b6itb3msmv9%2522%252C%2522activeTabId%2522%253A%2522clzx9xjuw00023b6jo6ou6y4s%2522%257D%252C%2522clzu7d7lu00053b6i8d0ec981%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzu7d7lu00043b6igoh9bywt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clzu7d7lu00053b6i8d0ec981%2522%252C%2522activeTabId%2522%253A%2522clzu7d7lu00043b6igoh9bywt%2522%257D%252C%2522clzu7d7lu00033b6itmxhirnp%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clzu7d7lu00033b6itmxhirnp%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) of `<MyRadioGroup>` styled with `orientation=horizontal`. Maybe you can use this to figure out the difference between your code and this codesandbox. Otherwise, I'm going to close this issue but feel free to reopen if you're still encountering any problems!
