### ISSUE TITLE
[RAC] Add layout="grid" to GridList

### ISSUE THREAD

**Issue by staticshock** [adobe/react-spectrum#6886]
### Provide a general summary of the feature here

ListBox supports [vertical grid](https://react-spectrum.adobe.com/react-aria/ListBox.html#vertical-grid) layouts, which allows me to use all the arrow keys to navigate around items. In GridList, it looks like I can only use up/down arrows. I'd love to see similar to support for keyboard navigation between the two.

### 🤔 Expected Behavior?

Right now left/right arrows in a GridView are used to focus on interactive children. I'm not sure if something similar would still be possible if my proposal were to be implemented.

### 😯 Current Behavior

Up/down arrows navigate between items, left/right arrows navigate within an item.

### 🔦 Context

I'm trying to use a GridView to implement interactive cards for objects in my system. I chose a GridView because the cards have interactive children, and I chose a grid layout because that's pretty natural for cards. Is there a more suitable collection component I should have used? Or should I hand-roll?

**Comment by LFDanLu** [comment]
GridList actually supports something called `keyboardNavigationBehavior` which will make `Tab` focus the elements in the item instead of using ArrowLeft/Right. Combined with `layout=grid` you can get the following behavior: https://reactspectrum.blob.core.windows.net/reactspectrum/f56a78746d0fd804267cb5ab17e2675f33f13e5e/storybook/index.html?path=/story/react-aria-components--grid-list-example&args=layout:grid;keyboardNavigationBehavior:tab&providerSwitcher-express=false. Does that roughly fit your ask here?

**Comment by staticshock** [comment]
Ahh, this landed just a couple of months ago via #6486! It's exactly what I wanted for Christmas, I just didn't notice it yet because I was on RAC 1.2.0! Thanks!
