### ISSUE TITLE
usePress wrapper on a text input swallows space key presses

### ISSUE THREAD

**Issue by Katherraptor** [adobe/react-spectrum#6942]
### Provide a general summary of the issue here

When a text input is wrapped in a `usePress` wrapper to trigger input focus typing any letter into the input works except the space key. Space characters are never added to the input.

### 🤔 Expected Behavior?

Space character should be added to the text input

### 😯 Current Behavior

Nothing, the keydown event is `preventDefault`ed and the event is canceled before the input is changed.

### 💁 Possible Solution

This function:
https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/interactions/src/usePress.ts#L950
is evaluating the keyboard event as a not valid input key, a possible solution could be `target.type === 'text'` should be added to the conditional on line 952 

### 🔦 Context

I've built a filter bar that includes an input element as well as chips for already selected filters. Clicking/pressing anywhere around the input or between the chips should trigger focusing the input to allow interacting with the filter bar as a whole component instead of forcing users to hunt for the right trigger.

### 🖥️ Steps to Reproduce

https://codesandbox.io/p/sandbox/old-sun-5tzvpw

steps to reproduce:
- click into the input
- type space (input does not update)

### Version

react-aria: 3.34.3

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

MacOS Sonoma 14.6.1

### 🧢 Your Company/Team

Netflix/Platform

**Comment by snowystinger** [comment]
Can you explain your use case more? I'm not sure when you'd put a usePress on a Text input. The codesandbox calls focus, but the input would already have focus the moment you click on it regardless of that call.

**Comment by snowystinger** [comment]
I think `usePress` might be too much for this use case. I understand the appeal of it, but you don't want any of the keyboard handling it does.
One quick option would be to delete the keyboard handling from the usePress' returned props. Like so https://codesandbox.io/p/sandbox/old-sun-forked-vz7pvd
We realized that advanced use cases may choose to do things like this.

However, it may be easier to tackle this yourself. Then you can ignore clicks on the input itself since it doesn't need to focus itself. You may also find it easier to distinguish between the 'x' buttons on the tags compared to the rest of the input. Also, if the tags themselves are focusable, then clicking on them probably also shouldn't marshall focus to the input.
