### ISSUE TITLE
Update state when visibleRange changes in <RangeCalendar>

### ISSUE THREAD

**Issue by dlsso** [adobe/react-spectrum#6964]
### Provide a general summary of the feature here

1. Ideally, I would like `state.visibleRange` to be available in `<RangeCalendar>`, up-to-date and usable in the manner shown in "Context" below.
2. If that is not reasonable, I would like state from `useRangeCalendarState` to be updated when the visible range changes in `<RangeCalendar>`  (I specifically want access to an up-to-date value of the current month).

### 🤔 Expected Behavior?

Focusing on scenario 2 above, I have found that if I use `useRangeCalendarState` I can access the value I need, but it does not get updated. If I have a component like this I would expect `state` to be updated when navigating through the months in the calendar. 
```
function RangeCalendarComponent(props: any) {
  let { locale } = useLocale();
  let state = useRangeCalendarState({
    ...props,
    locale,
    createCalendar,
  });

  return (
    <RangeCalendar
      {...props}
      locale={useLocale().locale}
      createCalendar={createCalendar}

    >
      <header>
        <Button slot='previous'>◀</Button>
        <Heading />
        <Button slot='next'>▶</Button>
      </header>
      <div>Price {priceList[state.visibleRange.start.month]}</div>
      <CalendarGrid>{(date) => <CalendarCell date={date} />}</CalendarGrid>
    </RangeCalendar>
  );
}
```

### 😯 Current Behavior

`state` does not change changing the visible month of the calendar. I have tested with `useEffect` and it retains the initial value.

### 💁 Possible Solution

Update `state` when `visibleRange` changes.

### 🔦 Context

In my specific case I would like to display a price on on the calendar. Assume the price list is an array and I just need to access the correct one. If the value was available I could do something like this:

```
          <RangeCalendar>
            <header>
              <Button slot='previous'>◀</Button>
              <Heading />
              <Button slot='next'>▶</Button>
            </header>
            <div>Price {priceList[state.visibleRange.start.month])}</div>    {/*  This state property is not available */}
            <CalendarGrid>{(date) => <CalendarCell date={date} />}</CalendarGrid>
          </RangeCalendar>
```

**Comment by LFDanLu** [comment]
Is this implementation a pure hooks one or a React Aria Components one? I'm able to get the visible range month updating via this sandbox: https://codesandbox.io/p/sandbox/crazy-rain-kgzdzf?file=%2Fsrc%2FApp.js%3A19%2C31

**Comment by dlsso** [comment]
> Is this implementation a pure hooks one or a React Aria Components one? I'm able to get the visible range month updating via this sandbox: https://codesandbox.io/p/sandbox/crazy-rain-kgzdzf?file=%2Fsrc%2FApp.js%3A19%2C31. The example comes from https://react-spectrum.adobe.com/react-aria/RangeCalendar.html#state

Thank you very much. Using `RangeCalendarStateContext` appears to give updated state where `useRangeCalendarState` does not.

Do you happen to know why that is? I encountered `useRangeCalendarState` first in the docs and not expect a second way to get the state, so I apologize for asking for a feature which does exist.

**Comment by LFDanLu** [comment]
No worries! In general, if you are using our React Aria Components or React Spectrum components directly you won't need to worry about calling any of the stately/aria hooks yourself. But here is where I think your confusion is here:

If you are using RangeCalendar from the React Aria Components library (which I believe you are but lemme know if the one in the RangeCalendar example is also a custom wrapper of sorts), then it handles calling `useRangeCalendarState` for you internally and uses said returned calendar state with the `useRangeCalendar` hook so that various interactions (like advancing the month) update the calendar's state appropriately. For instance, the calendar's "next" button has `onPress: () => state.focusNextPage(),` passed to it by `useRangeCalendar` meaning it will call one of the calendar's state's updaters when clicked, updating the internal tracked date value. 

However, when you call `useRangeCalendar` yourself outside of the RangeCalendar component, you've set up a separate instance of the calendars state yourself but note that you don't actually call or pass that state you set up anywhere except for in your div. That means your copy of the calendar state isn't actually being updated on any interactions, you are just always reading its initialized state. Lemme know if that makes sense.

**Comment by dlsso** [comment]
Yes, I'm using `RangeCalendar` from `'react-aria-components'`. 

Thank you very much for explaining! I believe that all makes sense, and looking at the docs again I see that `useRangeCalendarState` only seems to be used in conjunction with `useRangeCalendar` so I'm guessing it works as I was hoping if it's in that context.

There was no mention of how to access state on the `RangeCalendar` page though, so I found the hook and expected it to work, not realizing all the other hooks stuff existed and is all designed to go together.

If you search "rangecalendar state" in the docs you get multiple hits for `useRangeCalendarState` and none for `RangeCalendarStateContext`. So if I have any feedback it would be to mention it on the `RangeCalendar` page.

**Comment by LFDanLu** [comment]
No problem! Thank you for the feedback, we can definitely look at making that more clear in the docs.
