### ISSUE TITLE
Range Date Picker

### ISSUE THREAD

**Issue by harsharavindra** [adobe/react-spectrum#7158]
### Provide a general summary of the feature here

We are trying to implement a RangeDatePicker with two separate input field and calendar to select `start` and `end` date. I was trying to find some example or documentation which is helpful to implement this, but I couldn't. 

Please guide me if I am missing anything
<img width="957" alt="Screenshot 2024-10-08 at 12 32 51 PM" src="https://github.com/user-attachments/assets/639f5dd4-d21b-493c-9962-270cc6939c3c">

### 🤔 Expected Behavior?

Two separate calendar to pick start and end date

### 😯 Current Behavior

Currently, we have to choose both start and end date from a single calendar.

### 🔦 Context

<img width="957" alt="Screenshot 2024-10-08 at 12 32 51 PM" src="https://github.com/user-attachments/assets/bf5b8295-5eea-42ea-9aa8-2e6710a7dbfb">

### 💻 Examples

https://carbondesignsystem.com/components/date-picker/code/

https://www.npmjs.com/package/react-datepicker

**Comment by LFDanLu** [comment]
This previous issue feels related: https://github.com/adobe/react-spectrum/issues/4723. In short, I think it would require a fair amount of rewiring/modification of the current hooks to implement this experience due to the presence of two separate input fields and a number of assumptions we make when the user clicks on a cell in the calendar since we support range selection via drag

**Comment by LFDanLu** [comment]
Closing since we probably won't be able to pull this into our priorities but happy for others to take a stab if interested!
