### ISSUE TITLE
`getSymbols` throws when using `roundingIncrement` >= 2

### ISSUE THREAD

**Issue by macarie** [adobe/react-spectrum#7168]
### Provide a general summary of the issue here

When a `roundingIncrement` >= 2 is used, `getSymbols` throws when creating `symbolFormatter`:
https://github.com/adobe/react-spectrum/blob/bebc9764ab07ac86f54ce0c2982da5baa17cbb50/packages/%40internationalized/number/src/NumberParser.ts#L258

### 🤔 Expected Behavior?

It should not allow the `NumberFormat` constructor to throw if the user's options are correct.

### 😯 Current Behavior

The constructor throws because the options are incompatible, as the function forcefully overrides `minimumSignificantDigits` and `maximumSignificantDigits`.

The error thrown (in Chrome) is:
```
Uncaught TypeError: RoundingType is not fractionDigits
```
Which seems to be a V8 internal error (?).

### 💁 Possible Solution

Setting `roundingIncrement` to `undefined` solves the issue, but I'm unsure if it has any side effects or causes any other issues. I've tried running the Jest test suite locally and the results are fine.

I've also tried spreading `intlOptions` at the end, so that `minimumSignificantDigits` and `maximumSignificantDigits` can get overridden, but the `can still get all plural literals with minimum significant digits` test fails when doing that.

### 🖥️ Steps to Reproduce

https://stackblitz.com/edit/vitejs-vite-ku6pdw?file=src%2FApp.tsx

Change `roundingIncrement` to `2`, `5`, or some other allowed value in `src/App.tsx`.

### Version

main

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

macOS

**Comment by snowystinger** [comment]
Thanks for the issue. It would appear that those values (roundingIcrement etc) were added recently to Chrome and didn't make it into Node 18, which is what we run our tests against right now.

I think that it's fine to restore those to default values for the line which is blowing up because that's a function to find all possible symbols which might appear in a formatted number, which doesn't really matter if we set rounding. Finding a few extra symbols won't hurt anything.
