### ISSUE TITLE
Style-able scrollbar/scrollarea component

### ISSUE THREAD

**Issue by musjj** [adobe/react-spectrum#7286]
### Provide a general summary of the feature here

A scroll area component with a style-able scrollbar.

### 🔦 Context

The native scrollbar offers very little freedom in customization. Even with the best styling attempts, they will still look inconsistent between platforms/browsers. 

This problem can only be solved by using a custom component that allows full control over the looks of the scrollbar. But an adhoc, homegrown implementation will surely be fraught with accessibility issues and platform bugs. So it would be really great if a high quality, battle-tested implementation could be included in React Aria/Spectrum.

### 💻 Examples

A good example would be the `ScrollArea` component from Radix: https://www.radix-ui.com/primitives/docs/components/scroll-area

**Comment by devongovett** [comment]
Building custom scrollbars from scratch is not a good idea because operating systems have lots of user preferences for things like always showing vs only while scrolling, overlay vs track, thickness, high contrast colors, etc. These preferences are not exposed to CSS or JavaScript so it is impossible to respect them. See this post for a longer description of these considerations: https://ericwbailey.website/published/dont-use-custom-css-scrollbars/

CSS does have some properties for basic scrollbar customization of the native scrollbars rather than rebuilding them from scratch. If you are going to customize at all, I'd recommend this route instead of building something custom. https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_scrollbars_styling

Going to close this issue. We aren't planning on supporting this in our libraries.
