### ISSUE TITLE
Export ListCollection from react-stately/list so it can be used externally with useCollection

### ISSUE THREAD

**Issue by martinhootsuite** [adobe/react-spectrum#7305]
### Provide a general summary of the feature here

Sometimes we need to extract collection items from children, but we don't need to use any state function. It would be helpful to have a Collection implementation exported from the library

### 🤔 Expected Behavior?

The ListCollection class would be exported from the library.

### 😯 Current Behavior

It isn't exported

### 🔦 Context

I'm trying to incorporate the Collections API in some components that aren't using any react stately state hook

**Comment by snowystinger** [comment]
Thanks for the issue. That ListCollection is actually part of our old Collections. I know our hooks docs still reference the old Collections, I'm looking for our issue/backlog item to update them and will link it here once I find it.

I'm going to close this as won't do because it's old collections.

If you tell us more about what you're trying to accomplish, maybe we will have some other suggestions.

**Comment by martinhootsuite** [comment]
@snowystinger Thank you. Could you please clarify a little bit more on what is the old Collections and what is the new preferred approach?

Currently our design system uses Collections for many components (dropdown-menus, lists, tabs), so, trying to maintain the same API for other components with subitems, I wanted to have a way of using useCollection without having to go to an unneeded state hook. 

What would be your recommendation? (What I did was copying the ListCollection class to our project to be used in the factory for useCollection, but it would be better not having a fork of that inside the project)

**Comment by martinhootsuite** [comment]
Thank you
