### ISSUE TITLE
OTP component request

### ISSUE THREAD

**Issue by thorbde** [adobe/react-spectrum#7374]
### Provide a general summary of the feature here

Requesting an OTP (one time password) component from React Aria. It's a component type that would greatly benefit from being "standardized" across the web, since multiple different password managers attempt to autofill them. 

Example in ShadCN: https://ui.shadcn.com/docs/components/input-otp

Perhaps this can be achieved with current input components, but it would be very beneficial to have an example of how to achieve this in a semantic, accessible way.

### 🤔 Expected Behavior?

-

### 😯 Current Behavior

-

### 🔦 Context

-

**Comment by snowystinger** [comment]
You could probably do something like this https://github.com/adobe/react-spectrum/discussions/5718

**Comment by musjj** [comment]
I think that would work for certain designs, but not all. For example, look at shadcn's [implementations](https://ui.shadcn.com/docs/components/input-otp):

![Image](https://github.com/user-attachments/assets/d3c3c13e-83b0-4fdc-8627-ca928f028577)

![Image](https://github.com/user-attachments/assets/1b3cbcac-b13a-4ab0-ba1d-ca5207c6c678)

**Comment by snowystinger** [comment]
Sure you can, https://codesandbox.io/p/sandbox/ndg84w
I've included a hooks based version as well in case you need finer control

The trick to the shadcn is that the boxes aren't actually part of the input and the input itself is hidden. You can see this by inspecting the DOM. Also, they have a funny behavior, if you click and drag on the OTP, you can select some unexpected ranges because the font size/spacing of the hidden input doesn't match the visuals on top. There are probably some improvements that could be made for that. For now though it supports copy and paste as because of that.
