### ISSUE TITLE
`TableView` has two borders at the bottom

### ISSUE THREAD

**Issue by kaitoukid-1412** [adobe/react-spectrum#7428]
### Provide a general summary of the issue here

![{4C5AE59F-C1E1-4728-999F-90CB58781991}](https://github.com/user-attachments/assets/afb341d0-24c9-4232-a49c-42bf2c9799ac)
![{21FA06C8-602C-43C0-9344-382374B90CFB}](https://github.com/user-attachments/assets/70ccc272-5670-4b6c-88c2-90a8ce29186e)
![{7425E830-EA6A-4C28-B2C3-9699E77928AE}](https://github.com/user-attachments/assets/121c61f2-c482-44fe-a1e4-6f9afc58a373)

```
https://react-spectrum.adobe.com/react-spectrum/TableView.html
https://opensource.adobe.com/spectrum-css/?path=/docs/components-table--docs
```

### 🤔 Expected Behavior?

.

### 😯 Current Behavior

.

### 🖥️ Steps to Reproduce

.

### Version

Current

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

Window

**Comment by snowystinger** [comment]
This isn't a bug, it's working as intended. If you increase or decrease the height of the table, it'll go away. It's only happening because the height of the table happens to be just a tiny bit larger than the sum of the row heights, so the bottom row's border is doubled up with the table's bottom border.

This can also happen during the normal course of using the table if you scroll and line up the bottom border of an item just above the table's border.

The reason it doesn't happen in the spectrum CSS version you linked is because that is a native `table` element which comes with benefits such as border collapsing.

We cannot use the `table` element though because our component is virtualized and `table` cannot handle that.
