### ISSUE TITLE
useSlider() and useSliderState() for a Slider component

### ISSUE THREAD

**Issue by chungwu** [adobe/react-spectrum#763]
I'd like to implement `useSlider()` for @react-aria and `useSliderState()` for @react-stately.  I believe the first step is to draft an RFC?

Before I get started, though, if folks from the Spectrum team had already thought about what the API would look like, it'd be very helpful to get a brain dump first!

**Comment by devongovett** [comment]
Hey, thanks for opening this! Let me review the API doc that we have internally, and follow up here tomorrow.

One thing is that so far, since we've all been working on Spectrum internally, the Storybook and unit tests are pretty set up around that. I think you could start with a basic version and not worry about the Spectrum styles if you want. We can work on the Spectrum specific bits later on. As long as there's a basic version of a component using the hooks somewhere, you could use that as the example in Storybook and in the tests in the meantime.

**Comment by snowystinger** [comment]
FYI, some work has been done around draggable handle type things in relation to splitview. They have some similar behaviors, so you may find this PR good to look at https://github.com/adobe/react-spectrum/pull/37
https://www.w3.org/TR/wai-aria-practices-1.1/#windowsplitter
https://www.w3.org/TR/wai-aria-practices-1.1/#slider
https://www.w3.org/TR/wai-aria-practices-1.1/#slidertwothumb

**Comment by chungwu** [comment]
Thanks for the pointer!  I was planning on using `useDrag1D()`; is the plan to replace it with `useMove()`?  Should I be incorporating `useMove()` or go ahead with just `useDrag1D()` for now (since slider only requires 1D movement anyway)?

**Comment by majornista** [comment]
An important note regarding mobile accessibility. There is currently no way to detect the increment and decrement swipe gestures dispatched by VoiceOver on iOS with javascript, so the expected behavior for mobile screen reader users will not work with a pure javascript WAI-ARIA implementation of the slider design pattern. In HTML, we should implement the slider control using an `input[type="range"]`, or for a two, or more, thumb slider, an `input[type="range"]` for each value being controlled.

**Comment by chungwu** [comment]
@majornista thanks! Do you mean there should be a visually-hidden `input[type="range"]` (as there is for checkbox etc) for each thumb?  Should the focus / key event listeners be on the input instead of the thumb (as in WAI-ARIA examples), so that it can be controlled via VoiceOver?  (Sorry, this is new territory for me :sweat_smile:)

**Comment by snowystinger** [comment]
> Thanks for the pointer! I was planning on using `useDrag1D()`; is the plan to replace it with `useMove()`? Should I be incorporating `useMove()` or go ahead with just `useDrag1D()` for now (since slider only requires 1D movement anyway)?

I had planned to make it more general, I don't think that hook is one of our API's for v3 yet, so we should probably try to make it the more general case.

Also, *if you can find it* there is a series of commits where I experimented with building sliders on top of this... but my git-fu isn't good enough to track that down anymore :(

**Comment by devongovett** [comment]
@chungwu here's a rough draft of the API we were thinking about.

```ts
import {ValueBase, RangeInputBase} from '@react-types/shared';

interface SliderProps extends ValueBase<number>, RangeInputBase<number> {
  isDisabled?: boolean,
  // text label
  children?: ReactNode,
  // format options for the number formatter used to render the value label
  formatOptions?: Intl.NumberFormatOptions,
  // onChange would be called as the user drags.
  // onChangeEnd could be used if you only need to know the value after the drag completes.
  onChangeEnd?: (value: number) => void
}

interface SliderState {
  value: number,
  setValue(value: number): void,
  // possibly more useful methods here?
}

function useSliderState(props: SliderProp): SliderState;

interface SliderAria {
  // props for the label element
  labelProps: LabelHTMLAttributes<HTMLLabelElement>,
  // props for the hidden <input type="range">
  inputProps: InputHTMLAttribute<HTMLInputElement>
}

function useSlider(props: SliderProps, state: SliderState): SliderAria;
```

Eventually we'd also have a range slider, and possibly support for multiple more than two handles if needed (e.g. gradient inputs), but we can start simple.

I think the pieces are:

* `useMove` - new name for `useDrag1D`, moved into `@react-aria/interactions` and updated to use pointer events with fallbacks for touch since it only supports mouse events right now. I don't think I would start here though. Perhaps you can try out `useDrag1D` as it is to start?
* `useSliderState` - state in `@react-stately/slider`. Holds the current slider value. You can use the `useControlledState` hook to store it and handle calling the onChange handler. There may be some other state/methods we haven't thought about that end up here as well.
* `useSlider` - hook in `@react-aria/slider`. Handles events for dragging, and updates DOM props/ARIA props for the label/hidden range input. There may be more here, so we'll follow up with more info about the a11y implementation soon.

Hopefully that's enough to get you started. Let us know if you have any questions. We can also set up a quick video call if that's easier.

**Comment by devongovett** [comment]
Also if it helps there's some docs from the Spectrum design team here which might be useful to visualize all the pieces we're thinking about here. https://spectrum.adobe.com/page/slider/

**Comment by devongovett** [comment]
Awesome! We did have an API for a `RangeSlider` in addition to the normal `Slider`. Basically the difference is rather than exposing a number it exposes a `RangeValue<number>`.

```ts
interface RangeSlider extends SliderBase<RangeValue<number>> {}
```

Perhaps we could have three component APIs, from simple to more advanced:

* `Slider` - a simple slider with a single thumb
* `RangeSlider` - a range slider with two thumbs
* `MultiSlider` (name TBD) - base slider with support for any number of thumbs.

Perhaps at the react-aria level though we'd just support the advanced one via `useSlider`, similar to what you have. i.e. under the hood sliders can always have 1 or more thumbs. Then `Slider` and `RangeSlider` could easily be built with a simpler API at the Spectrum/design system level.

Overall your API looks good! I think perhaps (if possible) the returned values from the hooks that aren't props objects could live in the stately layer (e.g. `offsetPercents`)? We usually try to keep the ARIA hooks as close to just DOM props as possible. Plus, things like offset percents are useful outside just the web (e.g. could be used in react-native), so putting them in Stately would make sense to share that logic too. For the ones returned by `useSliderThumb`, perhaps these could live as methods on the state object? Like `getValueForThumb(index)` or something?

**Comment by snowystinger** [comment]
> Anyway, just an initial stab! Lots of open questions to be figured out, but probably the main one is whether the "Thumb" component should be exposed, or just remain an internal detail...

I think I'd be inclined to have Thumbs be exposed for composing. This would allow people to put attributes on them like data-*, particularly useful to the automated testing crowd. It could also be used to attach Tooltips. It also follows a lot of our decisions with other components to expose more of the internals. RadioGroup is a great example you brought up. Many things can be controlled at the Group level, but you can also dive into individual Radio's easily.

**Comment by majornista** [comment]
> @majornista thanks! Do you mean there should be a visually-hidden `input[type="range"]` (as there is for checkbox etc) for each thumb? Should the focus / key event listeners be on the input instead of the thumb (as in WAI-ARIA examples), so that it can be controlled via VoiceOver? (Sorry, this is new territory for me 😅)

@chungwu Correct. We use a visually hidden `input[type="range"]` for each thumb, so that focus goes to the html5 input instead of some generic DOM element. Browser-implemented `input[type="range"]` elements can handle the increment and decrement gesture events triggers by screen readers as [`stepUp`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/stepUp) and [`stepDown`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/stepDown).

Labelling the input within a simple Slider is easy. The `id` prop for the component can get propagated to the rendered `id` attribute on the `input`, and a `<label>` can reference this `IDREF` using the `for`/`htmlFor` attribute. Alternatively, an `aria-label` or `aria-labelledby` prop on the component can get propagated to the `input` directly.

With a `RangeSlider`, the component should be labelled using a `fieldset` or WAI-ARIA `role="group"` that contains two `input[type="range"]`s with `aria-label="Minimum"`/`aria-label="Maximum"` (strings should be localized with default values), and `aria-labelledby` referencing the external label and the input itself. 

Form controls in React-Spectrum, include a `label` prop and render the `label` as part of the component, to ensure that things layout correctly and that the internal controls get appropriately labelled for accessibility.

I alway explicitly set `aria-valuetext` on `input[type="range"]`, even if it is just a numeric value, because some screen readers announce the input value as a percent between the `min` and `max`, but it should be possible to explicitly set the `aria-valuetext`, and tooltip text, independently. So that a slider for a time range, for example, can communicate a time as a string to someone using assistive technology.

It is not necessary to add `aria-valuemin`, `aria-valuemax` or `aria-valuenow` for the simple Slider use case, because those values will be the same as `min`, `max` and `value` for the input. However, for the RangeSlider use case, each `input` will have `min` and `max` relative to the entire slider range, but `aria-valuemin` and `aria-valuemax` can be used to communicate the range limits for each input. The "Minimum" input will have `aria-valuemin` equal to the `min` for the RangeSlider, and `aria-valuemax` equal to the `value` of the "Maximum" input. The "Maximum" input will have `aria-valuemax` equal to the `max` for the RangeSlider, and `aria-valuemin` equal to the `value` of the "Minimum" input. 

I agree with @snowystinger that it having thumbs exposed for composing may be useful.

**Comment by chungwu** [comment]
Thanks for the feedback, everyone!  Makes a lot of sense :smile: 

@majornista to clarify on aria-label for the multi-thumb use case...  It'd look something like...

```tsx
<div role="group" aria-labelledby="label">
  <div id="label">Whatever I passed to label prop</div>
  <div className="thumbs">

    <div className="thumb">
      <div className="thumb-knob"/>
      <input type="range" aria-label="Minimum" aria-valuemin/max/now=.../>
    </div>

    <div className="thumb">
      <div className="thumb-knob"/>
      <input type="range" aria-label="Maximum" aria-valuemin/max/now=.../>
    </div>

  </div>
</div>
```

Specifically,
* Do we need `role="slider"` on anything?
* Do we need any aria labeling on the "thumb-knob" -- the visible graphical thumb that you drag with a cursor?
* Would validation stuff (aria-required / invalid / errormessage etc) go on each range input?

Thanks!

**Comment by majornista** [comment]
@chungwu You're close. I would use a `label` for the `div` with  `id="label"` and have its `for`/`htmlFor` attribute point to the `id` attribute on the first `input`, which could be assigned on the React component, but if not be generated internally. Each `input` should have `aria-labelledby="label THE-GENERATED-ID-FOR-THE-INPUT"`. So that the Min should announce as "label Minimum", and the Max should announce as "label Maximum".

**Comment by majornista** [comment]
@chungwu, 

1. You shouldn't need `role="slider"` on anything, because the `input[type="range"]` has that role implicitly.
2. Visible graphics or `div`s other than the input, like the thumb-knob, are presentational and shouldn't have any `aria-` labelling.
3. Validation stuff, like aria-required or invalid, should go on the inputs, because that's what will receive focus, although I'm not sure there is a use case for aria-required on a Slider. For error messaging, we should be able to set `aria-describedby` on each of the `input`s with an `IDREF` referencing the HTML element containing the error message text content.

**Comment by chungwu** [comment]
Hi all!  Finally got around to pulling together a draft PR for this :smile: 

You'll find it in #809 

I built the react-aria and react-stately hooks, and a few toy components using those hooks, and some Storybook stories, so we can get a feel for how the component interactions work, and what the DX is like in using these hooks.
