### ISSUE TITLE
Focus Ring enables when switching tabs with mouse

### ISSUE THREAD

**Issue by tomByrer** [adobe/react-spectrum#791]
# 🐛 Bug Report 

When checking out your [Radio Group](https://react-spectrum.adobe.com/react-spectrum/RadioGroup.html), I noticed the blue Focus Ring is enabled when I:

1. Select radio item
2. Use mouse to click on another browser tab.
3. Use mouse to click on the Radio Group tab to return to the page
4. The Focus Ring is shown, when it was not shown at initial selection.

## 💁 Possible Solutions

* Can be helpful to know what 'last selection' was when navigating in the middle of filling out forms for those with attention disorders (like me ;) ).
  * Should be [documented](https://github.com/adobe/react-spectrum/blob/main/packages/@react-aria/focus/docs/FocusRing.mdx#introduction).
* Want to be consistent
  * Needs automated tab-switching test, maybe visual-diff?
  * Extra code in RocusRing to ensure a check for tab-swtich is done before enabling.

I'm indifferent, but I lean towards the first option which is an increase of usability IMHO.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.0.2
| Browser          | Firefox & Vivaldi (Chromium)
-- | --
| Operating System | Win10

## 🧢 Your Company/Team

Web users

**Comment by majornista** [comment]
@tomByrer I'm pretty sure this is the expected behavior for when the window blurs, as when switching tabs or cycling focus from end of page, through the browser chrome, and back into the page. In order to evaluate whether to show the focus ring when no keyboard or pointer event is detected before the focus event, which happens when the user tabs into the page from the browser chrome, or when focus is restored to the page when shifting between tabs, we assume keyboard focus by default.

See: https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/interactions/src/useFocusVisible.ts#L98-L102 and https://github.com/adobe/react-spectrum/blob/87324e905565ca2964c3f766b40dc6788e3b5615/packages/%40react-aria/interactions/src/useFocusVisible.ts#L80-L96
