### ISSUE TITLE
Having a href prop on button component 

### ISSUE THREAD

**Issue by sylvesteraswin** [adobe/react-spectrum#808]
# ❔ Question

Is it advisable to use the button component to render an anchor tag by passing a href prop? 

This means I can have 2 elements which look like a button visually but one will fire an in page action and the other will navigate to a new page.

## 🔦 Context

https://react-spectrum.adobe.com/react-spectrum/Button.html

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

**Comment by majornista** [comment]
Since it's a fairly common use case to have a call to action link that looks like a button (look to the "New issue" button on this page for an example), we support `href` when the `elementType="a"`. For accessibility, the link, visually styled as a button, is identified as a button using `role="button"`, and can be activated using either the Enter or Space key, like a `button` of `type="button"`. Recognizing that there may be a difference of opinion, with a valid case to be made that if the control opens a new URL it should always be identified as `role="link"`, we chose to have the button's role match the element's appearance.

**Comment by devongovett** [comment]
Going to close this. Appears this is working as indented.
