### ISSUE TITLE
Unknown element in collection

### ISSUE THREAD

**Issue by theankurkedia** [adobe/react-spectrum#830]
# 🐛 Bug Report 

Running the example given https://react-spectrum.adobe.com/react-aria/useMenu.html gives an error.

```
Unknown element <MenuItem> in collection.
Menu
/src/Menu.jsx:9:14
   6 | 
   7 | export function Menu(props) {
   8 |   // Create state based on the incoming props
>  9 |   let state = useTreeState({ ...props, selectionMode: "none" });
     |              ^
  10 | 
```

## 💻 Code Sample
[codesandbox](https://codesandbox.io/s/jovial-curie-byjuy)

**Comment by LFDanLu** [comment]
Heya, I took a look at your codesandbox (thanks for attaching that by the way) and it looks like you are missing the `Item` import from the example. If you add the `"@react-stately/collections": "3.0.2"` dependency to your package.json and add
`import {Item} from '@react-stately/collections';` to your App.js instead of doing `import {MenuItem as Item ...}` it should work.

**Comment by devongovett** [comment]
Going to close this. If you are still having issues, feel free to reopen.

**Comment by theankurkedia** [comment]
Thanks @LFDanLu , it worked.
