### ISSUE TITLE
[@react-aria/overlays, et al] Hooks that do not generate content via `React.createElement`?

### ISSUE THREAD

**Issue by Westbrook** [adobe/react-spectrum#857]
# 🙋 Feature Request
I'm looking into reusing the logic in `@react-aria` and `@react-stately` in Spectrum Web Components where our renderer does not rely on a virtual DOM environment. As such hooks like `useSelect` which generate content internally via `createElement` stand as a blocker to leveraging hooks in this context.

I'm trying to decide whether it would be better to receive an interface via which this sort of element creation could be overridden locally (particularly in a context like mine where the components expect to be working with vanilla DOM), whether overriding functionality like `createElement` is simply a requirement of leveraging these bindings more broadly, or whether getting a larger number of `...Props` values out of the return from the hook would make this process easier to manage.

## 🤔 Expected Behavior
Deep React centric behavior isn't required to leverage hooks across other contexts.

## 😯 Current Behavior
Hooks often require the use of `React.createElement` under the covers.

## 💁 Possible Solution
- Export more `...Props` values from the `useSelect` hook? Similar to `labelProps`, et al, they could be leveraged by the end user in preparing their HTML
- Offer an interface that allows end users control over how DOM creation happens internal to the hooks.
- Tell me I'm over complicating `createElement` and that overriding it isn't that hard. I've seen relatively short "versions of it, but I'm worried that this is the above water part of the iceberg.
- Investigate a lower level of abstraction that would allow for the portability of the state/aria context currently exposed via the hooks to be accessible via hooks as well as approaches taken by other renderers.

## 🔦 Context
I'm attempting to leverage hooks in Web Components via Haunted.js and `lit-html`.

## 💻 Examples
https://github.com/adobe/spectrum-web-components/pull/717

## 🧢 Your Company/Team
Adobe Spectrum

**Comment by devongovett** [comment]
I don't think the hooks should ever be creating React elements, but some of them do consume JSX elements. Our [collections API](https://react-spectrum.adobe.com/react-stately/collections.html) uses JSX elements to build a collection of items that can be rendered incrementally (e.g. virtualized). The collection is also used to track items that are focused and selected.

We'd need an alternative to this for non-VDOM environments. I assume you'll be passing options via some alternative method, e.g. a list of option objects or DOM children? Under the hood, the `useSelectState` hook calls `useCollection` which is what converts the JSX children into a [Collection](https://react-spectrum.adobe.com/react-stately/Collection.html). Collection is the interface that all other parts work with. It provides a few methods to access objects for each item by a unique key. The selection/focus management hooks use this to keyboard navigate within the collection and represent which items are selected. So, theoretically, you could implement the Collection interface in a different way rather than using JSX elements, and everything else should work. I think we'd need to add an option to `useSelectState` and the other hooks to pass a pre-built collection in rather than building it from JSX children.

If you're passing a list of objects in, it should be fairly simple to provide a wrapper around them implementing the expected interface. If a list of DOM nodes, it could work similarly, but virtualization wouldn't be possible since all elements are already in the DOM. That may be ok depending on your use case.

**Comment by Westbrook** [comment]
Maybe I'm tracking the compiled code incorrectly, but it does seem like there are React components being created. When you see something like:
```
_react.createElement(VisuallyHidden ...
```
In https://unpkg.com/browse/@react-aria/select@3.1.0/dist/module.js is there a better reference than "creating React elements" that I could use to discuss what's going on here?

Maybe I've not added something to the arguments that would prevent running that code?

**Comment by devongovett** [comment]
Ah got it. `HiddenSelect` is an actual React component as opposed to a hook. You'd need to create an analogous component to handle rendering those elements. We could perhaps create a hooks version of it as well, e.g. `useHiddenSelect` to return the props for the necessary elements that you could use in your own rendering. I think we wrapped it up in a component to make it easier for people since there's no reason to style any of those elements, but it makes sense to provide a hooks version for non-react users. 👍

**Comment by Westbrook** [comment]
Great! I wasn't using them _directly_, they just came along for the ride, so a version where it was a data hook instead of element hooks would be what I think I'm looking for here, for sure.

**Comment by devongovett** [comment]
> I wasn't using them directly, they just came along for the ride

Wait, so if you weren't rendering a `HiddenSelect`, how was `React.createElement` being called?

Making a hooks version of this was a bit challenging because there's so many elements here, but I made a version with most of the challenging parts. You'll need to handle rendering the actual elements, including all of the `<option>` elements. In addition, the hook can't conditionally return different results depending on the size of the collection, so that'll also be up to the implementor. See #917 for details. Let me know if that works for you.
