### ISSUE TITLE
Missing required argument in useButton (in useSelect example) and other doc findings

### ISSUE THREAD

**Issue by tristandubbeld** [adobe/react-spectrum#870]
# 🙋 Documentation Request

When going through the docs to create a select component with Typescript I noticed that [in the example](https://react-spectrum.adobe.com/react-aria/useSelect.html#example) the `ref` argument was missing in the useButton hook.

Going through the docs I found some other small things:

- In [the collections example](https://react-spectrum.adobe.com/react-stately/collections.html#sections-1) `item.name` is used but it seems like it should be `section.name`.
- A few imports are missing in [the useListBox example](https://react-spectrum.adobe.com/react-aria/useListBox.html#example).

I'm working on a PR right now, so it should be solved soon. Let me know your thoughts!

**Comment by tristandubbeld** [comment]
I noticed that in other examples imports are also missing (e.g. in the `useSelect` example `useSelect` is not imported), so I'm guessing this is intended?

**Comment by LFDanLu** [comment]
@tristandubbeld Thanks for helping fix this! Some of the missing imports that you may find (such as the `useSelect` one you mentioned) aren't in the examples because they are imported further up in the mdx file. Adding the same import to the example then results in a build error due to duplicate declarations unfortunately, something we'll have to figure out a fix for.
