### ISSUE TITLE
Set opacity for background. 

### ISSUE THREAD

**Issue by joepuzzo** [adobe/react-spectrum#872]
# 🙋 Documentation Request

Hey guys love the library. I want to make a component without custom css however it seems there is no way to set the opacity of the background color. Is there a way im not aware of ?

**Comment by snowystinger** [comment]
what component are you trying to set the opacity for the background color?
Is it missing a token?

**Comment by dannify** [comment]
Hey @joepuzzo thanks! For our components, we only allow colors defined by Spectrum so that they follow the design guidelines. Can you give me some more information on what you are trying to do?

**Comment by joepuzzo** [comment]
View Component

**Comment by snowystinger** [comment]
Gotcha, so it looks like we do not currently support that, see https://github.com/adobe/react-spectrum/blob/main/packages/%40react-spectrum/utils/src/styleProps.ts#L138
Opacity is not supported by spectrum design, which is why we don't support it. This component is meant to facilitate building Spectrum layouts. If you need something else, you can use a Styling framework of your choice, we do not prevent that.
