### ISSUE TITLE
Quiet TextArea doesn't resize according to value/defaultValue

### ISSUE THREAD

**Issue by vonstring** [adobe/react-spectrum#885]
# 🐛 Bug Report 

Quiet TextArea doesn't resize when given a large value/defaultValue.

## 🤔 Expected Behavior

TextArea should show the full content of the string given.

## 😯 Current Behavior

TextArea only shows about a line and a half. Manually modifying the content of the TextArea by typing into it makes it resize.

## 💁 Possible Solution

Resize the TextArea when the value changes, not just when typing.

## 🔦 Context

I'm making a subtitling tool using textareas, and the quiet ones look beautiful when I type them in, but bad/truncated when I load long subtitles into them.

## 💻 Code Sample

    function App() {
      return (<Provider theme={defaultTheme}>
        <TextArea isQuiet defaultValue={"foo ".repeat(300)}/>
      </Provider>)
    }

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.1.0
| Chrome | 84.0.4147.105 (Official Build) (64-bit)
| Windows | 10

**Comment by dannify** [comment]
Hey @vonstring, thanks for filing this. It looks like we are only checking the size on a change event. We probably should move this check to a `useEffect` instead.

**Comment by zidian257** [comment]
I'd like to give a try on this 😄

**Comment by Jav3k** [comment]
Hello. Why only isQuiet mode supports autoresize?
[Here](https://spectrum.adobe.com/page/text-area/#Height) in the screenshot, textarea is not in isQuiet mode. And it says that 
> If height is undefined, the height of a text area is dynamic and grows with the input text.

What should I do if I need autoresizing in normal mode. I tried working with ref and scrollHeight. But it was unsuccessful.


My component:
```ts
type Props = {
  value: string;
  onChange: (newValue: string) => void;
};

export const CustomTextArea = ({ value, onChange }: Props): ReactElement => {
  return (
    <TextArea
      value={value}
      onChange={onChange}
      flex
      flexGrow={1}
      label="Custom Label"
      isRequired
      necessityIndicator="icon"
      type="text"
      inputMode="text"
      // isQuiet
    />
  );
};
```

[codesandbox](https://codesandbox.io/s/autumn-river-71gkf?file=/src/App.tsx)

**Comment by snowystinger** [comment]
It was deemed too unusable to have the quiet textareas scroll. You just can’t tell that the text disappears into an overflow because there is no affordance for it. That’s why the quiet textarea expands as content is added.

As for why it's not working for you, you have a TextArea with a flex grow and you're not specifying a height for it, so it won't auto resize, it'll just fill the space its parent allocates at a rate of 1 until it's filled, then stop (this will appear instantaneous as it happens in layout phase, see CSS Flex https://css-tricks.com/snippets/css/a-guide-to-flexbox/).
You'd need to duplicate some of the logic that's in isQuiet, but I don't know how much you want to do this. A non-quiet text area has a 'resize' affordance in the bottom corner that allows uses to resize as they need.
