### ISSUE TITLE
text selection is active when dismissing dialog overlay in firefox

### ISSUE THREAD

**Issue by stefanprobst** [adobe/react-spectrum#919]
# 🐛 Bug Report 

After dismissing the dialog overlay in [the `useDialog` docs example](https://react-spectrum.adobe.com/react-aria/useDialog.html#example) by clicking outside, text selection is active, i.e. just moving the mouse will select text. Happens in Firefox, not in Chrome.

## 🤔 Expected Behavior

Text selection should not be active after dismissing dialog.

## 😯 Current Behavior

Here's a video:

![react-aria-dialog](https://user-images.githubusercontent.com/20753323/89713942-77208680-d99b-11ea-858f-ac20c2c8a6a3.gif)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.1.0
| Browser          | Firefox 79
| Operating System | Ubuntu 18.04

**Comment by snowystinger** [comment]
Yep, totally does this. It does not do it in our DialogTrigger page though https://react-spectrum.adobe.com/react-spectrum/DialogTrigger.html#dismissable
Probably good to see what the difference is between the two. Nothing obvious has jumped out at me yet.

**Comment by snowystinger** [comment]
Reopening as we are reverting the original fix for this after finding new issues because of it.
Instead, we're looking at two different approaches. A short term would be moving our useModal.mdx example underlay to a sibling of the dialog, that way we can place `text-select: none` on it. This isn't great for people because it's not immediately clear why we need that.
A longer term solution will be based around the difference between this fiddle in Chrome vs FF. We may need to detect FF.
https://jsfiddle.net/snowystinger/ceta7fqo/17/
Output from Chrome the two different elements being clicked are
Foo:
```
foo pointerup capture
body got pointerup
body got mouseup
```

Bar:
```
bar pointerup capture
body got pointerup
bar mouseup capture
body got mouseup
```


VS Firefox
Foo:
```
foo pointerup capture
body got pointerup
```

Bar:
```
bar pointerup capture
body got pointerup
bar mouseup capture
body got mouseup
```
