### ISSUE TITLE
Why is react-spectrum using onPress instead of onClick?

### ISSUE THREAD

**Issue by ivanjeremic** [adobe/react-spectrum#923]
Like in the title I wonder why is react-spectrum using onPress instead of onClick?

**Comment by snowystinger** [comment]
We use press in order to normalize across different modes of interaction. See https://react-spectrum.adobe.com/react-aria/usePress.html#features
It also attempts to match us with what React is experimenting with, this way, if/when they ship, we'll be able to replace our work with the React implementation 
https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/interactions/src/usePress.ts#L16

**Comment by snowystinger** [comment]
Further information here https://react-spectrum.adobe.com/blog/building-a-button-part-1.html
