### ISSUE TITLE
How React Spectrum and Spectrum CSS relates and how they can work together ?

### ISSUE THREAD

**Issue by aozora** [adobe/react-spectrum#976]
# ❔ Question

I'm building a new web app using React Spectrum and Spectrum CSS: what's the best strategy to avoid duplicated and redundant styles?

## 🔦 Context

I see that every component uses CSS modules to generate isolated styles, plus by wrapping the App with the Provider component the app wrapper gets the spectrum styles too.
However eventual HTML elements defined outside the app component (i.g. the html element itself) cannot get the spectrum styles unless I manually add the Spectrum CSS modules, but doing this I see that several CSS variables get defined twice.
Since the React edition of Spectrum doesn't cover all the components in the Spectrum design system that already exists in the CSS edition, I'd like to use both editions together to compensate for the React one.

## 💻 Code Sample

You can see a demo here: https://react-showtime.vercel.app/
Source code here: https://github.com/aozora/react-showtime

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | latest
| spectrum-css   | latest
| create-react-app   | latest
| Browser          | Firefox
| Operating System | macOS latest

**Comment by dannify** [comment]
Hey @aozora. Sorry for the delay on this. Currently there is no easy way to dedupe the styles from both packages. We are working with the Spectrum CSS team to better align our approaches however even then, because of our css modules approach, there will always be duplicated styles. Our aim is to continue to build up our suite of components to match those in Spectrum CSS.
