### ISSUE TITLE
Intentional for DialogTrigger to not accept function as 2nd child when type is popover? (have link to live code sample)

### ISSUE THREAD

**Issue by cheapsteak** [adobe/react-spectrum#985]
# ❔ Question

Is it intentional for the popover type to not accept a function as its second child?
E.g. this doesn't work:
```tsx
<DialogTrigger isDismissable type="popover" placement="bottom">
  <ActionButton>
    Some Button
  </ActionButton>
  {(close) => (...contents...)}
</DialogTrigger>
```

The contents do not show up
![image](https://user-images.githubusercontent.com/743976/90592240-1ec76100-e1b3-11ea-83de-7d85c0a0e0bd.png)

Repro (make sure the iframe is wide enough so it uses the popover mode rather than the modal mode): https://stackblitz.com/edit/react-zgsb4s?file=src%2FApp.js

**Comment by LFDanLu** [comment]
@cheapsteak Ahhh, good catch, yeah that wasn't intentional. Looks like https://github.com/adobe/react-spectrum/blob/main/packages/@react-spectrum/dialog/src/DialogTrigger.tsx#L158 is probably just missing the same kind of `{typeof content === 'function' ? content(state.close) : content}` logic that the other dialog types already have.

**Comment by cheapsteak** [comment]
Ahh awesome, I wasn't sure if it was an accessibility thing or something
Thanks for the quick triage, and looking forward to the update!  🙏
